const fs = require('fs');
let code = fs.readFileSync('e:/CrimeMatrix/frontend/src/utils/translate.js', 'utf8');

const additions = {
  en: `    settings: "Settings", personal_preferences: "Personal preferences", saving: "Saving...", saved: "Saved!", save_changes: "Save Changes", profile: "Profile", edit_profile: "Edit Profile", opening: "Opening...", language: "Language", primary_language: "Primary Language", secondary_language: "Secondary Language", ui_language: "UI Language (App)", theme: "Theme", notifications: "Notifications", voice_settings: "Voice Settings", voice_assistant: "Voice Assistant", speed: "Speed", auto_transcribe: "Auto-transcribe", offline_sync: "Offline Sync", enable_offline: "Enable Offline", sync_frequency: "Sync Frequency", storage_used: "Storage Used", clear_cache: "Clear Cache", cleared: "Cleared!", device_management: "Device Management", this_device: "This Device", active: "Active", last_sync: "Last sync", minutes_ago: "minutes ago", sync_now: "Sync Now", synced: "Synced!", other_devices: "Other Devices", tablet: "Tablet", desktop: "Desktop", manage_devices: "Manage Devices", light: "Light", dark: "Dark", system: "System", push: "Push", email: "Email", sound: "Sound", whisper: "Whisper",`,
  ta: `    settings: "அமைப்புகள்", personal_preferences: "தனிப்பட்ட விருப்பங்கள்", saving: "சேமிக்கப்படுகிறது...", saved: "சேமிக்கப்பட்டது!", save_changes: "மாற்றங்களைச் சேமி", profile: "சுயவிவரம்", edit_profile: "சுயவிவரத்தைத் திருத்து", opening: "திறக்கப்படுகிறது...", language: "மொழி", primary_language: "முதன்மை மொழி", secondary_language: "இரண்டாம் நிலை மொழி", ui_language: "UI மொழி (பயன்பாடு)", theme: "தீம்", notifications: "அறிவிப்புகள்", voice_settings: "குரல் அமைப்புகள்", voice_assistant: "குரல் உதவியாளர்", speed: "வேகம்", auto_transcribe: "தானியங்கு படியெடுத்தல்", offline_sync: "ஆஃப்லைன் ஒத்திசைவு", enable_offline: "ஆஃப்லைனை இயக்கு", sync_frequency: "ஒத்திசைவு அதிர்வெண்", storage_used: "பயன்படுத்தப்பட்ட சேமிப்பு", clear_cache: "தற்காலிக சேமிப்பை அழி", cleared: "அழிக்கப்பட்டது!", device_management: "சாதன மேலாண்மை", this_device: "இந்த சாதனம்", active: "செயலில்", last_sync: "கடைசி ஒத்திசைவு", minutes_ago: "நிமிடங்களுக்கு முன்", sync_now: "இப்போது ஒத்திசை", synced: "ஒத்திசைக்கப்பட்டது!", other_devices: "பிற சாதனங்கள்", tablet: "டேப்லெட்", desktop: "டெஸ்க்டாப்", manage_devices: "சாதனங்களை நிர்வகி", light: "ஒளி", dark: "இருண்ட", system: "கணினி", push: "தள்ளு", email: "மின்னஞ்சல்", sound: "ஒலி", whisper: "விஸ்பர்",`,
  kn: `    settings: "ಅமைப்புகள்", personal_preferences: "ವೈಯಕ್ತಿಕ ಆದ್ಯತೆಗಳು", saving: "ಉಳಿಸಲಾಗುತ್ತಿದೆ...", saved: "ಉಳಿಸಲಾಗಿದೆ!", save_changes: "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ", profile: "ಪ್ರೊಫೈಲ್", edit_profile: "ಪ್ರೊಫೈಲ್ ಎಡಿಟ್ ಮಾಡಿ", opening: "ತೆರೆಯಲಾಗುತ್ತಿದೆ...", language: "ಭಾಷೆ", primary_language: "ಪ್ರಾಥಮಿಕ ಭಾಷೆ", secondary_language: "ದ್ವಿತೀಯ ಭಾಷೆ", ui_language: "UI ಭಾಷೆ (ಅಪ್ಲಿಕೇಶನ್)", theme: "ಥೀಮ್", notifications: "ಅಧಿಸೂಚನೆಗಳು", voice_settings: "ಧ್ವನಿ ಸೆಟ್ಟಿಂಗ್‌ಗಳು", voice_assistant: "ಧ್ವನಿ ಸಹಾಯಕ", speed: "ವೇಗ", auto_transcribe: "ಸ್ವಯಂ ನಕಲು", offline_sync: "ಆಫ್‌ಲೈನ್ ಸಿಂಕ್", enable_offline: "ಆಫ್‌ಲೈನ್ ಸಕ್ರಿಯಗೊಳಿಸಿ", sync_frequency: "ಸಿಂಕ್ ಆವರ್ತನ", storage_used: "ಬಳಕೆಯಾದ ಶೇಖರಣೆ", clear_cache: "ಕ್ಯಾಶ್ ತೆರವುಗೊಳಿಸಿ", cleared: "ತೆರವುಗೊಳಿಸಲಾಗಿದೆ!", device_management: "ಸಾಧನ ನಿರ್ವಹಣೆ", this_device: "ಈ ಸಾಧನ", active: "ಸಕ್ರಿಯ", last_sync: "ಕೊನೆಯ ಸಿಂಕ್", minutes_ago: "ನಿಮಿಷಗಳ ಹಿಂದೆ", sync_now: "ಈಗ ಸಿಂಕ್ ಮಾಡಿ", synced: "ಸಿಂಕ್ ಮಾಡಲಾಗಿದೆ!", other_devices: "ಇತರ ಸಾಧನಗಳು", tablet: "ಟ್ಯಾಬ್ಲೆಟ್", desktop: "ಡೆಸ್ಕ್‌ಟಾಪ್", manage_devices: "ಸಾಧನಗಳನ್ನು ನಿರ್ವಹಿಸಿ", light: "ಬೆಳಕು", dark: "ಕತ್ತಲೆ", system: "ವ್ಯವಸ್ಥೆ", push: "ಪುಶ್", email: "ಇಮೇಲ್", sound: "ಧ್ವನಿ", whisper: "ವಿಸ್ಪರ್",`,
  te: `    settings: "సెట్టింగులు", personal_preferences: "వ్యక్తిగత ప్రాధాన్యతలు", saving: "సేవ్ చేయబడుతోంది...", saved: "సేవ్ చేయబడింది!", save_changes: "మార్పులను సేవ్ చేయండి", profile: "ప్రొఫైల్", edit_profile: "ప్రొఫైల్‌ను సవరించండి", opening: "తెరవబడుతోంది...", language: "భాష", primary_language: "ప్రాథమిక భాష", secondary_language: "ద్వితీయ భాష", ui_language: "UI భాష (యాప్)", theme: "థీమ్", notifications: "నోటిఫికేషన్‌లు", voice_settings: "వాయిస్ సెట్టింగులు", voice_assistant: "వాయిస్ అసిస్టెంట్", speed: "వేగం", auto_transcribe: "ఆటో-ట్రాన్స్‌క్రైబ్", offline_sync: "ఆఫ్‌లైన్ సమకాలీకరణ", enable_offline: "ఆఫ్‌లైన్‌ను ప్రారంభించండి", sync_frequency: "సమకాలీకరణ ఫ్రీక్వెన్సీ", storage_used: "ఉపయోగించిన నిల్వ", clear_cache: "కాష్ క్లియర్ చేయండి", cleared: "క్లియర్ చేయబడింది!", device_management: "పరికర నిర్వహణ", this_device: "ఈ పరికరం", active: "క్రియాశీల", last_sync: "చివరి సమకాలీకరణ", minutes_ago: "నిమిషాల క్రితం", sync_now: "ఇప్పుడే సమకాలీకరించండి", synced: "సమకాలీకరించబడింది!", other_devices: "ఇతర పరికరాలు", tablet: "టాబ్లెట్", desktop: "డెస్క్‌టాప్", manage_devices: "పరికరాలను నిర్వహించండి", light: "కాంతి", dark: "చీకటి", system: "సిస్టమ్", push: "పుష్", email: "ఇమెయిల్", sound: "ధ్వని", whisper: "విస్పర్",`,
  hi: `    settings: "सेटिंग्स", personal_preferences: "व्यक्तिगत प्राथमिकताएँ", saving: "सहेजा जा रहा है...", saved: "सहेज लिया गया!", save_changes: "परिवर्तन सहेजें", profile: "प्रोफ़ाइल", edit_profile: "प्रोफ़ाइल संपादित करें", opening: "खुल रहा है...", language: "भाषा", primary_language: "प्राथमिक भाषा", secondary_language: "द्वितीयक भाषा", ui_language: "UI भाषा (ऐप)", theme: "थीम", notifications: "सूचनाएं", voice_settings: "वॉयस सेटिंग्स", voice_assistant: "वॉयस असिस्टेंट", speed: "गति", auto_transcribe: "ऑटो-ट्रांसक्राइब", offline_sync: "ऑफ़लाइन सिंक", enable_offline: "ऑफ़लाइन सक्षम करें", sync_frequency: "सिंक आवृत्ति", storage_used: "उपयोग किया गया स्टोरेज", clear_cache: "कैश साफ़ करें", cleared: "साफ़ किया गया!", device_management: "डिवाइस प्रबंधन", this_device: "यह डिवाइस", active: "सक्रिय", last_sync: "अंतिम सिंक", minutes_ago: "मिनट पहले", sync_now: "अभी सिंक करें", synced: "सिंक किया गया!", other_devices: "अन्य उपकरण", tablet: "टैबलेट", desktop: "डेस्कटॉप", manage_devices: "उपकरण प्रबंधित करें", light: "रोशनी", dark: "अंधेरा", system: "सिस्टम", push: "पुश", email: "ईमेल", sound: "ध्वनि", whisper: "विस्पर",`
};

for (const lang of ['en', 'ta', 'kn', 'te', 'hi']) {
  const marker = new RegExp("\\\\b" + lang + ":\\\\s*\\\\{");
  code = code.replace(marker, "\\n  " + lang + ": {\\n" + additions[lang] + "\\n");
}

fs.writeFileSync('e:/CrimeMatrix/frontend/src/utils/translate.js', code);
console.log('Translations injected!');
