export const alerts = [
  {
    id: 'ALT-001',
    type: 'whisper',
    title: 'FIR #4521 matches unsolved case #4489',
    description: 'MO fingerprint shows identical entry method and timing pattern. Suspect Ravi Kumar linked to both cases.',
    timestamp: '12 min ago',
    status: 'new',
    priority: 'high',
    caseId: 'FIR #4521',
    district: 'Bengaluru Urban',
    x: 420, y: 310,
  },
  {
    id: 'ALT-002',
    type: 'cross-district',
    title: 'Cross-district theft pattern detected',
    description: 'Similar MO identified in Bengaluru and Mysuru districts. 3 cases linked by entry method.',
    timestamp: '28 min ago',
    status: 'new',
    priority: 'high',
    caseId: 'Multiple',
    district: 'Bengaluru → Mysuru',
    x: 350, y: 360,
  },
  {
    id: 'ALT-003',
    type: 'evidence',
    title: 'New evidence linked to FIR #4515',
    description: 'CCTV footage from Electronic City parking lot shows suspect vehicle matching case description.',
    timestamp: '1 hr ago',
    status: 'pending',
    priority: 'medium',
    caseId: 'FIR #4515',
    district: 'Bengaluru Urban',
    x: 415, y: 345,
  },
  {
    id: 'ALT-004',
    type: 'ai',
    title: 'AI: High-risk area alert — Malleshwaram',
    description: 'Predictive analysis shows 78% probability of theft incident in next 48 hours based on historical patterns.',
    timestamp: '2 hrs ago',
    status: 'new',
    priority: 'high',
    caseId: 'Prediction',
    district: 'Bengaluru Urban',
    x: 410, y: 305,
  },
  {
    id: 'ALT-005',
    type: 'fir-match',
    title: 'FIR #4519 matches suspect vehicle',
    description: 'Vehicle KA-05-CD-5678 involved in Mysuru Road accident matches registered vehicle of suspect.',
    timestamp: '3 hrs ago',
    status: 'pending',
    priority: 'medium',
    caseId: 'FIR #4519',
    district: 'Mysuru',
    x: 300, y: 400,
  },
  {
    id: 'ALT-006',
    type: 'whisper',
    title: 'Repeat offender spotted — Mohammed Ali',
    description: 'Post-release surveillance detected suspect near Whitefield commercial area. Known robbery target zone.',
    timestamp: '4 hrs ago',
    status: 'resolved',
    priority: 'medium',
    caseId: 'Surveillance',
    district: 'Bengaluru Urban',
    x: 445, y: 325,
  },
  {
    id: 'ALT-007',
    type: 'ai',
    title: 'AI: Network expansion detected',
    description: 'Deepak Reddy network shows new associate connection. Recommend investigation of linked phone number.',
    timestamp: '5 hrs ago',
    status: 'new',
    priority: 'low',
    caseId: 'INV-001',
    district: 'Bengaluru Urban',
    x: 430, y: 315,
  },
  {
    id: 'ALT-008',
    type: 'cross-district',
    title: 'Vehicle tracking alert — Hubballi',
    description: 'Suspect vehicle KA-01-AB-1234 detected on highway camera near Hubballi. Route analysis suggests movement towards Belgaum.',
    timestamp: '6 hrs ago',
    status: 'pending',
    priority: 'high',
    caseId: 'Tracking',
    district: 'Hubballi',
    x: 280, y: 180,
  },
]

export const alertTypes = {
  whisper: { color: '#ef4444', label: 'Whisper Alert', icon: '🔴' },
  'fir-match': { color: '#f59e0b', label: 'FIR Match', icon: '🟡' },
  'cross-district': { color: '#8b5cf6', label: 'Cross-District', icon: '🟣' },
  evidence: { color: '#3b82f6', label: 'Evidence Link', icon: '🔵' },
  ai: { color: '#10b981', label: 'AI Notification', icon: '🟢' },
}
