export const suspects = [
  {
    id: 'SUS-001',
    name: 'Ravi Kumar',
    age: 32,
    initials: 'RK',
    gradient: 'linear-gradient(135deg, #ef4444, #dc2626)',
    district: 'Bengaluru Urban',
    status: 'At Large',
    riskScore: 92,
    cases: 5,
    lastActive: 'Jul 15, 2026',
    moMatches: 3,
    aliases: ['Ravi K', 'RK', 'Ravi the Fox'],
    address: '123 Malleshwaram, Bengaluru',
    phone: '+91 98765 43210',
    description: 'Known repeat offender specializing in residential break-ins. Targets upper-middle-class homes between 2-4 AM. Uses pry tools for rear door entry.',
    physicalDescription: 'Medium build, 5\'8", dark complexion, scar on left cheek',
    behavioralProfile: {
      personality: 'Calculating, patient, methodical',
      riskFactors: ['Repeat offender', 'Armed history', 'Cross-district operations'],
      patterns: ['Night-time operations', 'Solo or with one accomplice', 'Reconnaissance before hit'],
    },
    moFingerprint: {
      entryMethod: 'Rear door forced with pry tool',
      timing: '2:00-4:00 AM',
      targetProfile: 'Upper-middle-class residential',
      weapon: 'Knife (carried but rarely used)',
      escapePattern: 'Pre-parked motorcycle nearby',
      crimeSequence: 'Recon → Entry → Quick grab → Exit within 10 min',
    },
    timeline: [
      { date: '2024-03-15', event: 'First arrest — petty theft', type: 'arrest' },
      { date: '2024-06-20', event: 'Released on bail', type: 'release' },
      { date: '2025-01-10', event: 'Arrested — burglary Rajajinagar', type: 'arrest' },
      { date: '2025-04-15', event: 'Released — case closed', type: 'release' },
      { date: '2025-08-22', event: 'Linked to theft Malleshwaram', type: 'incident' },
      { date: '2026-07-16', event: 'Identified in FIR #4521', type: 'incident' },
    ],
    associates: [
      { name: 'Venkatesh R', relation: 'Accomplice', cases: 2, status: 'Arrested' },
      { name: 'Suresh M', relation: 'Supplier', cases: 1, status: 'Under watch' },
      { name: 'Prakash J', relation: 'Driver', cases: 3, status: 'At large' },
      { name: 'Lakshmi K', relation: 'Fence', cases: 2, status: 'Under investigation' },
    ],
  },
  {
    id: 'SUS-002',
    name: 'Mohammed Ali',
    age: 28,
    initials: 'MA',
    gradient: 'linear-gradient(135deg, #f59e0b, #d97706)',
    district: 'Bengaluru Urban',
    status: 'Arrested',
    riskScore: 78,
    cases: 3,
    lastActive: 'Jul 13, 2026',
    moMatches: 1,
    aliases: ['Mohammad A', 'MA'],
    address: '456 Whitefield Main Road',
    phone: '+91 87654 32109',
    description: 'Armed robbery suspect targeting commercial establishments. Uses knife as intimidation weapon. Arrested for Whitefield pharmacy robbery.',
    physicalDescription: 'Tall, 6\'1", lean build, tattoo on right arm',
    behavioralProfile: {
      personality: 'Impulsive, aggressive, substance-dependent',
      riskFactors: ['Drug dependency', 'Armed robbery history', 'Violent tendencies'],
      patterns: ['Evening operations', 'Targets cash-heavy businesses', 'Solo operations'],
    },
    moFingerprint: {
      entryMethod: 'Front entrance intimidation',
      timing: '9:00-11:00 PM',
      targetProfile: 'Small commercial establishments',
      weapon: 'Knife (actively brandished)',
      escapePattern: 'On foot, mixes with crowd',
      crimeSequence: 'Enter → Threaten → Grab cash → Flee',
    },
    timeline: [
      { date: '2025-02-10', event: 'Arrested — drug possession', type: 'arrest' },
      { date: '2025-05-15', event: 'Released', type: 'release' },
      { date: '2025-11-20', event: 'Robbery attempt — Koramangala', type: 'incident' },
      { date: '2026-07-13', event: 'Arrested — Whitefield robbery', type: 'arrest' },
    ],
    associates: [
      { name: 'Irfan S', relation: 'Lookout', cases: 1, status: 'At large' },
      { name: 'Rashid P', relation: 'Fence', cases: 2, status: 'Under watch' },
    ],
  },
  {
    id: 'SUS-003',
    name: 'Venkatesh Reddy',
    age: 45,
    initials: 'VR',
    gradient: 'linear-gradient(135deg, #8b5cf6, #7c3aed)',
    district: 'Bengaluru Rural',
    status: 'Under Investigation',
    riskScore: 65,
    cases: 4,
    lastActive: 'Jul 12, 2026',
    moMatches: 2,
    aliases: ['Venky', 'VR', 'Reddy Anna'],
    address: '789 Whitefield Main Road',
    phone: '+91 76543 21098',
    description: 'Insurance fraud specialist. Stages vehicle accidents and files multiple insurance claims. Operates a small network of claimants.',
    physicalDescription: 'Medium build, 5\'7", grey hair, wears glasses',
    behavioralProfile: {
      personality: 'Cunning, organized, risk-averse',
      riskFactors: ['Organized fraud ring', 'Multiple identities', 'Financial crimes'],
      patterns: ['Stages accidents', 'Files multiple claims', 'Uses middlemen'],
    },
    moFingerprint: {
      entryMethod: 'Staged vehicle accidents',
      timing: 'Varies',
      targetProfile: 'Insurance companies',
      weapon: 'None',
      escapePattern: 'Legal manipulation',
      crimeSequence: 'Stage accident → File claim → Collect → Repeat',
    },
    timeline: [
      { date: '2023-08-10', event: 'First fraud complaint', type: 'incident' },
      { date: '2024-01-15', event: 'Investigation initiated', type: 'investigation' },
      { date: '2024-06-20', event: 'Linked to 3 more claims', type: 'incident' },
      { date: '2026-07-12', event: 'New complaints filed', type: 'incident' },
    ],
    associates: [
      { name: 'Rajesh Sharma', relation: 'Claimant', cases: 3, status: 'Under investigation' },
      { name: 'Deepa N', relation: 'Medical fraud', cases: 2, status: 'Under watch' },
      { name: 'Kumar S', relation: 'Garage owner', cases: 4, status: 'Under investigation' },
      { name: 'Anita R', relation: 'Claimant', cases: 1, status: 'Under watch' },
      { name: 'Ganesh P', relation: 'Middleman', cases: 3, status: 'At large' },
      { name: 'Sunil T', relation: 'Insurance agent', cases: 2, status: 'Under investigation' },
    ],
  },
  {
    id: 'SUS-004',
    name: 'Suresh Patel',
    age: 38,
    initials: 'SP',
    gradient: 'linear-gradient(135deg, #10b981, #059669)',
    district: 'Mangaluru',
    status: 'Under Trial',
    riskScore: 55,
    cases: 2,
    lastActive: 'Jul 10, 2026',
    moMatches: 0,
    aliases: ['Suresh P'],
    address: '321 Mangaluru Central',
    phone: '+91 65432 10987',
    description: 'Domestic violence suspect. Currently under trial for assault charges. History of similar complaints.',
    physicalDescription: 'Heavy build, 5\'9", balding',
    behavioralProfile: {
      personality: 'Short-tempered, controlling',
      riskFactors: ['Domestic violence history', 'Repeat complaints'],
      patterns: ['Weekend incidents', 'Alcohol-related', 'Escalating pattern'],
    },
    moFingerprint: {
      entryMethod: 'Home entry',
      timing: 'Evenings/Weekends',
      targetProfile: 'Family members',
      weapon: 'Physical assault',
      escapePattern: 'N/A',
      crimeSequence: 'Verbal altercation → Physical violence → Victim files complaint',
    },
    timeline: [
      { date: '2024-11-10', event: 'First DV complaint', type: 'incident' },
      { date: '2025-03-15', event: 'Second complaint filed', type: 'incident' },
      { date: '2025-07-20', event: 'Charges filed', type: 'arrest' },
      { date: '2026-01-10', event: 'Trial initiated', type: 'investigation' },
    ],
    associates: [
      { name: 'Priya Patel', relation: 'Spouse (victim)', cases: 0, status: 'Victim' },
    ],
  },
  {
    id: 'SUS-005',
    name: 'Rajesh Sharma',
    age: 45,
    initials: 'RS',
    gradient: 'linear-gradient(135deg, #3b82f6, #2563eb)',
    district: 'Bengaluru Urban',
    status: 'At Large',
    riskScore: 82,
    cases: 6,
    lastActive: 'Jul 14, 2026',
    moMatches: 4,
    aliases: ['Raj S', 'RS', 'The Architect'],
    address: 'Unknown',
    phone: '+91 54321 09876',
    description: 'Cybercrime specialist operating phishing campaigns targeting tech companies. Uses sophisticated social engineering techniques.',
    physicalDescription: 'Unknown — operates remotely',
    behavioralProfile: {
      personality: 'Highly intelligent, methodical, risk-averse',
      riskFactors: ['Sophisticated cyber operations', 'International connections', 'Multiple attack vectors'],
      patterns: ['Phishing campaigns', 'Identity theft', 'Financial fraud'],
    },
    moFingerprint: {
      entryMethod: 'Phishing emails',
      timing: 'Business hours',
      targetProfile: 'Tech company employees',
      weapon: 'Social engineering',
      escapePattern: 'VPN + offshore servers',
      crimeSequence: 'Research → Craft email → Send → Harvest credentials → Exploit',
    },
    timeline: [
      { date: '2024-05-10', event: 'First phishing campaign detected', type: 'incident' },
      { date: '2024-09-15', event: 'Linked to 3 more campaigns', type: 'incident' },
      { date: '2025-02-20', event: 'International links identified', type: 'investigation' },
      { date: '2026-07-14', event: 'New campaign targeting Electronic City', type: 'incident' },
    ],
    associates: [
      { name: 'Unknown (Singapore)', relation: 'Server provider', cases: 0, status: 'Unknown' },
      { name: 'Anil K', relation: 'Email sender', cases: 3, status: 'Under investigation' },
      { name: 'Vikram S', relation: 'Data buyer', cases: 2, status: 'At large' },
      { name: 'Neha G', relation: 'Social engineer', cases: 4, status: 'At large' },
      { name: 'Ravi P', relation: 'Money mule', cases: 1, status: 'Arrested' },
    ],
  },
  {
    id: 'SUS-006',
    name: 'Kumar Swamy',
    age: 52,
    initials: 'KS',
    gradient: 'linear-gradient(135deg, #ec4899, #db2777)',
    district: 'Mysuru',
    status: 'Released',
    riskScore: 40,
    cases: 2,
    lastActive: 'Jun 2026',
    moMatches: 0,
    aliases: ['KS', 'Swamy'],
    address: '567 Mysuru Old City',
    phone: '+91 43210 98765',
    description: 'Released on parole after serving time for theft. Currently under surveillance.',
    physicalDescription: 'Short, 5\'4", grey hair, walks with limp',
    behavioralProfile: {
      personality: 'Reformed, cooperative',
      riskFactors: ['Prior conviction', 'Under parole conditions'],
      patterns: ['No new criminal activity detected'],
    },
    moFingerprint: {
      entryMethod: 'Unlocked doors',
      timing: 'Daytime',
      targetProfile: 'Residential — low security',
      weapon: 'None',
      escapePattern: 'Casual walk',
      crimeSequence: 'Identify target → Enter → Steal small items → Exit',
    },
    timeline: [
      { date: '2020-03-10', event: 'Arrested — theft', type: 'arrest' },
      { date: '2023-03-10', event: 'Released after sentence', type: 'release' },
      { date: '2023-06-15', event: 'Parole granted', type: 'release' },
    ],
    associates: [
      { name: 'Lakshmi W', relation: 'Wife', cases: 0, status: 'No record' },
    ],
  },
  {
    id: 'SUS-007',
    name: 'Imran Khan',
    age: 26,
    initials: 'IK',
    gradient: 'linear-gradient(135deg, #f97316, #ea580c)',
    district: 'Hubballi',
    status: 'At Large',
    riskScore: 70,
    cases: 3,
    lastActive: 'Jul 8, 2026',
    moMatches: 1,
    aliases: ['Imran K', 'IK'],
    address: '890 Hubballi Dharwad Road',
    phone: '+91 32109 87654',
    description: 'Serial theft suspect targeting parking lots and commercial complexes. Uses sophisticated tools for vehicle theft.',
    physicalDescription: 'Athletic build, 5\'10", tattoo on neck',
    behavioralProfile: {
      personality: 'Risk-taker, technically skilled',
      riskFactors: ['Vehicle theft specialist', 'Cross-district operations', 'Tool expertise'],
      patterns: ['Targets parking lots', 'Uses electronic tools', 'Night operations'],
    },
    moFingerprint: {
      entryMethod: 'Electronic bypass',
      timing: '10:00 PM - 2:00 AM',
      targetProfile: 'Two-wheelers in parking lots',
      weapon: 'None',
      escapePattern: 'On stolen vehicle',
      crimeSequence: 'Identify target → Bypass lock → Start → Ride away',
    },
    timeline: [
      { date: '2025-01-15', event: 'First vehicle theft', type: 'incident' },
      { date: '2025-05-20', event: 'Linked to 2 more thefts', type: 'incident' },
      { date: '2026-07-08', event: 'Latest incident — parking lot theft', type: 'incident' },
    ],
    associates: [
      { name: 'Sameer R', relation: 'Parts dealer', cases: 2, status: 'Under investigation' },
      { name: 'Farhan A', relation: 'Accomplice', cases: 1, status: 'At large' },
      { name: 'Zaid M', relation: 'Fence', cases: 3, status: 'At large' },
    ],
  },
  {
    id: 'SUS-008',
    name: 'Deepak Reddy',
    age: 35,
    initials: 'DR',
    gradient: 'linear-gradient(135deg, #6366f1, #4f46e5)',
    district: 'Bengaluru Urban',
    status: 'At Large',
    riskScore: 88,
    cases: 7,
    lastActive: 'Jul 15, 2026',
    moMatches: 5,
    aliases: ['Deepak R', 'DR', 'Ghost'],
    address: 'Unknown — multiple locations',
    phone: 'Multiple SIMs',
    description: 'Organized crime leader operating across multiple districts. Known for coordinating theft rings and managing networks of offenders.',
    physicalDescription: 'Medium build, 5\'9", always clean shaven',
    behavioralProfile: {
      personality: 'Charismatic leader, strategic thinker, paranoid',
      riskFactors: ['Organized crime leader', 'Multiple districts', 'Large network', 'Violent history'],
      patterns: ['Delegates operations', 'Uses multiple identities', 'Cross-district coordination'],
    },
    moFingerprint: {
      entryMethod: 'Coordinates multiple entry methods',
      timing: 'Varies by operation',
      targetProfile: 'Varies — residential, commercial, vehicles',
      weapon: 'Depends on operation',
      escapePattern: 'Pre-planned escape routes, multiple safe houses',
      crimeSequence: 'Plan → Assign → Execute → Collect → Distribute',
    },
    timeline: [
      { date: '2022-01-10', event: 'First organized crime link', type: 'incident' },
      { date: '2022-08-15', event: 'Network expansion detected', type: 'incident' },
      { date: '2023-03-20', event: 'Arrested — released on bail', type: 'arrest' },
      { date: '2023-09-10', event: 'Bail revoked — absconded', type: 'incident' },
      { date: '2024-04-15', event: 'Linked to 3 new operations', type: 'incident' },
      { date: '2025-11-20', event: 'Major theft ring busted', type: 'arrest' },
      { date: '2026-07-15', event: 'New network activity detected', type: 'incident' },
    ],
    associates: [
      { name: 'Ravi Kumar', relation: 'Operational head', cases: 5, status: 'At large' },
      { name: 'Prakash J', relation: 'Driver/logistics', cases: 3, status: 'At large' },
      { name: 'Lakshmi K', relation: 'Fence', cases: 2, status: 'Under investigation' },
      { name: 'Vikram S', relation: 'Cyber operations', cases: 2, status: 'At large' },
      { name: 'Suresh M', relation: 'Weapons supplier', cases: 1, status: 'Under watch' },
      { name: 'Anita R', relation: 'Safe house manager', cases: 0, status: 'Under surveillance' },
      { name: 'Ganesh P', relation: 'Money laundering', cases: 3, status: 'At large' },
      { name: 'Rashid P', relation: 'Recruitment', cases: 1, status: 'Under investigation' },
    ],
  },
]

export function getSuspectById(id) {
  return suspects.find((s) => s.id === id)
}
