export const investigations = [
  {
    id: 'INV-001',
    caseId: 'FIR #4521',
    title: 'Theft at Malleshwaram residence',
    status: 'active',
    priority: 'High',
    progress: 65,
    officer: 'SI Karthik',
    startDate: 'Jul 15, 2026',
    district: 'Bengaluru Urban',
    type: 'Theft',
    bookmarked: false,
    notes: [
      { id: 1, text: 'Initial scene investigation complete. No fingerprints found on primary entry point.', time: 'Jul 15, 10:30 AM', author: 'SI Karthik' },
      { id: 2, text: 'CCTV footage from neighbor shows suspect at 2:15 AM wearing dark jacket.', time: 'Jul 15, 2:00 PM', author: 'SI Karthik' },
      { id: 3, text: 'Suspect identified as Ravi Kumar, known repeat offender. Previous cases: FIR #4201, FIR #4356.', time: 'Jul 16, 9:00 AM', author: 'Inspector Deepak' },
    ],
    evidence: [
      { type: 'CCTV', description: 'Neighbor camera footage showing suspect at 2:15 AM', status: 'Analyzed' },
      { type: 'Phone Records', description: 'Cell tower data showing suspect near scene', status: 'Pending' },
      { type: 'Fingerprint', description: 'Partial print on rear door handle', status: 'Under review' },
      { type: 'Witness', description: 'Neighbor heard dog barking at 2:30 AM', status: 'Recorded' },
    ],
    timeline: [
      { date: 'Jul 15, 2026', event: 'FIR registered by victim', type: 'filing' },
      { date: 'Jul 15, 2026', event: 'Scene investigation completed', type: 'investigation' },
      { date: 'Jul 15, 2026', event: 'CCTV footage collected from 3 neighbors', type: 'evidence' },
      { date: 'Jul 16, 2026', event: 'Suspect identified from footage — Ravi Kumar', type: 'suspect' },
      { date: 'Jul 16, 2026', event: 'Cell tower data analysis initiated', type: 'investigation' },
    ],
    reasoning: [
      { step: 1, text: 'Entry method: Rear door forced open with pry tool', confidence: 95 },
      { step: 2, text: 'Timing: 2:00-4:00 AM consistent with suspect MO', confidence: 88 },
      { step: 3, text: 'CCTV confirms suspect presence at scene', confidence: 92 },
      { step: 4, text: 'Phone records place suspect in area during timeframe', confidence: 85 },
      { step: 5, text: 'Prior cases show identical entry method and timing', confidence: 90 },
    ],
    relatedCases: [
      { id: 'FIR #4201', title: 'Theft — Rajajinagar', connection: 'MO Match', similarity: 87 },
      { id: 'FIR #4356', title: 'Theft — Malleshwaram 5th Block', connection: 'Location', similarity: 72 },
      { id: 'FIR #4489', title: 'Robbery — Indiranagar', connection: 'Suspect Link', similarity: 65 },
    ],
    aiInsights: 'MO fingerprint matches 3 unsolved cases in Bengaluru North across the last 6 months. The entry method (rear door, same tool marks) and timing (2-4 AM) are consistent. Recommend cross-district alert for similar pattern.',
    suggestions: [
      'Cross-reference suspect phone records with cell tower data from other unsolved cases',
      'Check if suspect has been seen in Indiranagar area recently',
      'Request CCTV footage from main road cameras between 1-5 AM',
    ],
  },
  {
    id: 'INV-002',
    caseId: 'FIR #4515',
    title: 'Cyber fraud — Electronic City',
    status: 'active',
    priority: 'High',
    progress: 40,
    officer: 'Inspector Deepak',
    startDate: 'Jul 14, 2026',
    district: 'Bengaluru Urban',
    type: 'Cybercrime',
    bookmarked: true,
    notes: [
      { id: 1, text: 'Multiple victims reported unauthorized transactions after phishing emails.', time: 'Jul 14, 11:00 AM', author: 'Inspector Deepak' },
      { id: 2, text: 'Phishing email template matches known threat actor group "CyberShadow".', time: 'Jul 15, 10:00 AM', author: 'Cyber Cell' },
    ],
    evidence: [
      { type: 'Digital', description: 'Phishing email headers and content', status: 'Analyzed' },
      { type: 'Financial', description: 'Transaction records from 4 victim accounts', status: 'Under review' },
      { type: 'IP Address', description: 'VPN endpoint traced to Singapore', status: 'Pending' },
    ],
    timeline: [
      { date: 'Jul 14, 2026', event: 'First complaint received', type: 'filing' },
      { date: 'Jul 14, 2026', event: '3 more victims came forward', type: 'filing' },
      { date: 'Jul 15, 2026', event: 'Phishing email analysis initiated', type: 'investigation' },
      { date: 'Jul 15, 2026', event: 'Bank transaction freeze requested', type: 'investigation' },
    ],
    reasoning: [
      { step: 1, text: 'Phishing email originated from spoofed corporate domain', confidence: 90 },
      { step: 2, text: 'VPN endpoint in Singapore, but linguistic analysis suggests local operator', confidence: 75 },
      { step: 3, text: 'Similar campaigns targeting tech companies in Bengaluru', confidence: 85 },
    ],
    relatedCases: [
      { id: 'FIR #4485', title: 'Cybercrime — phishing attack', connection: 'Pattern Match', similarity: 78 },
      { id: 'FIR #4498', title: 'Fraud — online payment scam', connection: 'Technique', similarity: 62 },
    ],
    aiInsights: 'Pattern matches recent phishing campaigns targeting tech companies in Bengaluru. Email template similar to known threat actor group. Recommend coordinated investigation with cybercrime cell.',
    suggestions: [
      'Coordinate with Singapore authorities for VPN provider logs',
      'Analyze email header routing for origin clues',
      'Check if same infrastructure used in other recent phishing attacks',
    ],
  },
  {
    id: 'INV-003',
    caseId: 'FIR #4512',
    title: 'Missing person — Koramangala',
    status: 'active',
    priority: 'High',
    progress: 30,
    officer: 'SI Karthik',
    startDate: 'Jul 14, 2026',
    district: 'Bengaluru Urban',
    type: 'Missing',
    bookmarked: false,
    notes: [
      { id: 1, text: '22-year-old engineering student missing since July 12. Last seen leaving college.', time: 'Jul 14, 9:00 AM', author: 'SI Karthik' },
      { id: 2, text: 'Phone switched off since 4:45 PM on Jul 12. Last ping near MG Road.', time: 'Jul 14, 2:00 PM', author: 'SI Karthik' },
    ],
    evidence: [
      { type: 'CCTV', description: 'Campus exit footage at 4:32 PM', status: 'Analyzed' },
      { type: 'Phone', description: 'Last cell tower ping at 4:45 PM, MG Road area', status: 'Under review' },
    ],
    timeline: [
      { date: 'Jul 14, 2026', event: 'Missing person report filed', type: 'filing' },
      { date: 'Jul 14, 2026', event: 'Campus CCTV reviewed', type: 'evidence' },
      { date: 'Jul 15, 2026', event: 'Phone location analysis', type: 'investigation' },
    ],
    reasoning: [
      { step: 1, text: 'Last seen at college campus at 4:32 PM', confidence: 98 },
      { step: 2, text: 'Phone ping at MG Road at 4:45 PM — 30 min transit', confidence: 90 },
      { step: 3, text: 'No financial activity since disappearance', confidence: 85 },
    ],
    relatedCases: [],
    aiInsights: 'Phone activity ceased abruptly. No prior history of similar incidents. Recommend checking nearby hospitals and shelters.',
    suggestions: [
      'Issue missing person alert to all Bengaluru stations',
      'Check hospital admission records for matching description',
      'Review social media activity for distress signals',
    ],
  },
  {
    id: 'INV-004',
    caseId: 'FIR #4489',
    title: 'Robbery — Indiranagar',
    status: 'saved',
    priority: 'Medium',
    progress: 50,
    officer: 'SI Karthik',
    startDate: 'Jul 9, 2026',
    district: 'Bengaluru Urban',
    type: 'Theft',
    bookmarked: true,
    notes: [
      { id: 1, text: 'Two suspects on motorcycle threatened restaurant staff.', time: 'Jul 9, 11:00 PM', author: 'SI Karthik' },
    ],
    evidence: [
      { type: 'CCTV', description: 'Restaurant entrance footage', status: 'Analyzed' },
      { type: 'Vehicle', description: 'Partial plate number: KA-01-AB-****', status: 'Under review' },
    ],
    timeline: [
      { date: 'Jul 9, 2026', event: 'Robbery at 10:30 PM', type: 'filing' },
      { date: 'Jul 9, 2026', event: 'CCTV footage collected', type: 'evidence' },
      { date: 'Jul 10, 2026', event: 'Vehicle number partially identified', type: 'investigation' },
    ],
    reasoning: [
      { step: 1, text: 'Motorcycle-based robbery, helmet use suggests planning', confidence: 80 },
      { step: 2, text: 'Partial plate KA-01-AB narrows search', confidence: 70 },
    ],
    relatedCases: [
      { id: 'FIR #4521', title: 'Theft at Malleshwaram', connection: 'Suspect Link', similarity: 65 },
    ],
    aiInsights: 'MO matches robbery series in Bengaluru Urban. Same motorcycle-based approach.',
    suggestions: [
      'Run partial plate through RTO database',
      'Check for similar motorcycle robberies in surrounding areas',
    ],
  },
  {
    id: 'INV-005',
    caseId: 'FIR #4465',
    title: 'Missing juvenile — Hebbal',
    status: 'saved',
    priority: 'High',
    progress: 25,
    officer: 'SI Karthik',
    startDate: 'Jul 4, 2026',
    district: 'Bengaluru Urban',
    type: 'Missing',
    bookmarked: false,
    notes: [
      { id: 1, text: '16-year-old student missing. Left a note mentioning personal issues.', time: 'Jul 4, 10:00 AM', author: 'SI Karthik' },
    ],
    evidence: [
      { type: 'Document', description: 'Handwritten note found at home', status: 'Analyzed' },
      { type: 'Digital', description: 'Social media activity analysis', status: 'Under review' },
    ],
    timeline: [
      { date: 'Jul 4, 2026', event: 'Missing report filed', type: 'filing' },
      { date: 'Jul 5, 2026', event: 'Social media accounts reviewed', type: 'investigation' },
    ],
    reasoning: [
      { step: 1, text: 'Note suggests voluntary departure, not abduction', confidence: 70 },
      { step: 2, text: 'Social media shows recent distress signals', confidence: 65 },
    ],
    relatedCases: [],
    aiInsights: 'Juvenile may be at risk. Social media analysis shows recent distress signals.',
    suggestions: [
      'Issue missing person alert to all stations',
      'Check shelters and hospitals',
      'Contact school friends for information',
    ],
  },
]
