// Simple translation utility for CrimeMatrix UI
// Languages: en (English), ta (Tamil), kn (Kannada), te (Telugu), hi (Hindi)

const translations = {
  en: {
    settings: "Settings", personal_preferences: "Personal preferences", saving: "Saving...", saved: "Saved!", save_changes: "Save Changes", profile: "Profile", edit_profile: "Edit Profile", opening: "Opening...", language: "Language", primary_language: "Primary Language", secondary_language: "Secondary Language", ui_language: "UI Language (App)", theme: "Theme", notifications: "Notifications", voice_settings: "Voice Settings", voice_assistant: "Voice Assistant", speed: "Speed", auto_transcribe: "Auto-transcribe", offline_sync: "Offline Sync", enable_offline: "Enable Offline", sync_frequency: "Sync Frequency", storage_used: "Storage Used", clear_cache: "Clear Cache", cleared: "Cleared!", device_management: "Device Management", this_device: "This Device", active: "Active", last_sync: "Last sync", minutes_ago: "minutes ago", sync_now: "Sync Now", synced: "Synced!", other_devices: "Other Devices", tablet: "Tablet", desktop: "Desktop", manage_devices: "Manage Devices", light: "Light", dark: "Dark", system: "System", push: "Push", email: "Email", sound: "Sound", whisper: "Whisper",
    accept: "Accept",
    dismiss: "Dismiss",
    view: "View",
    alert: "Alert",
    priority: "Priority",
    status: "Status",
    alerts: "alerts",
    alert_feed: "Alert Feed",
    all_alerts: "All Alerts",
    new_alerts: "New Alerts",
    pending: "Pending",
    resolved: "Resolved",
    total_alerts: "Total Alerts",
    alerts_by_type: "Alerts by Type",
    recent_activity: "Recent Activity",
    crime_heatmap: "Crime Heatmap",
    whisper_alert: "Whisper Alert",
    fir_match: "FIR Match",
    cross_district: "Cross-District",
    evidence_link: "Evidence Link",
    ai_notification: "AI Notification",
    intelligence_alerts: "Intelligence Alerts",
    monitor_intel: "Monitor and respond to proactive intelligence",
    performance_summary: "Alert Performance Summary",
    pending_review: "Pending Review",
    alert_trend: "Alert Trend",
    alert_distribution: "Alert Distribution",
    total: "Total",
    recent_alerts: "Recent Alerts",
    more_details: "More details",
    // Analytics & Charts Translation
    crime_breakdown: "Crime Type Breakdown",
    cases_label: "cases",
    cases_by_crime_type: "Cases by Crime Type",
    todays_cases: "Today's Cases",
    live: "Live",
    total_cases: "Total Cases",
    theft: "Theft",
    fraud: "Fraud",
    cybercrime: "Cybercrime",
    assault: "Assault",
    other: "Other",
    top_districts: "Top Districts",
    by_case_count: "by case count",
    case_resolution: "Case Resolution",
    by_time_period: "by time period",
    total_resolved: "Total Resolved",
    avg_resolution: "Avg. Resolution",
    case_trend: "Case Trend",
    time_interval: "Time Interval:",
    weekly: "Weekly",
    monthly: "Monthly",
    yearly: "Yearly",
    vs_30_days: "vs 30 Days",
    cases_by_district: "Cases by District",
    investigation_calendar: "Investigation Calendar",
    hearings: "Hearings",
    shifts: "Shifts",
    cases_by_status: "Cases by Status",
    active: "Active",
    under_investigation: "Under Investigation",
    closed: "Closed",
    // Calendar Events
    court_hearing: "Court Hearing — FIR #4489",
    bail_review: "Bail Review — Case #4512",
    shift_handover: "Shift Handover — Morning",
    night_patrol: "Night Patrol Briefing",
    // Districts
    bengaluru_urban: "Bengaluru Urban",
    bengaluru_rural: "Bengaluru Rural",
    mysuru: "Mysuru",
    mangalaru: "Mangaluru",
    hubballi: "Hubballi",
    // Days/Periods
    days_label: "days",
    "0-30 days": "0-30 days",
    "31-60 days": "31-60 days",
    "61-90 days": "61-90 days",
    "91-180 days": "91-180 days",
    "180+ days": "180+ days",
    Sun: "Sun",
    Mon: "Mon",
    Tue: "Tue",
    Wed: "Wed",
    Thu: "Thu",
    Fri: "Fri",
    Sat: "Sat",

    // --- NEW COPILOT TRANSLATIONS ---
    analyzing: "Analyzing...",
    ai_copilot: "AI Copilot",
    hi_there: "Hi, there 👋",
    ask_copilot: "Ask me anything about cases, suspects, or investigations.",
    chat_history: "Chat History",
    new_chat: "New Chat",
    saved: "Saved",
    today: "Today",
    yesterday: "Yesterday",
    ask_anything_placeholder: "Ask me anything...",
    all_sources: "All Sources",
    fir_database: "FIR Database",
    suspects: "Suspects",
    evidence: "Evidence",
    stations: "Stations",
    context: "Context",
    referenced_sources: "Referenced Sources",
    actions: "Actions",
    related_cases: "Related Cases",
    generate_report: "Generate Report",
    export_conversation: "Export Conversation",
    save_to_case: "Save to Case",
    share_with_team: "Share with Team",
    robbery_indiranagar: "Robbery — Indiranagar",
    theft_koramangala: "Theft — Koramangala",
    cyber_fraud_ecity: "Cyber fraud — Electronic City",
    copilot_assistant_desc: "Your AI Investigation Assistant — trained on Karnataka police protocols, criminal databases, and legal frameworks.",
    quick_tasks: "Quick Tasks",
    suggested_prompt: "Suggested prompt",
    task_analyze_connections: "Analyze suspect connections",
    task_generate_report: "Generate investigation report",
    task_search_cross_district: "Search cross-district cases",
    suggested_prompt_text: "What are the common MO patterns in theft cases across Bengaluru district this month?",
    theft_malleshwaram: "Theft — Malleshwaram, Bengaluru",
    suspect_linked_3_cases: "Linked to 3 open cases",
    cctv_footage_main_road: "CCTV Footage — Main Road",
    captured_at_215_am: "Captured at 2:15 AM",
    malleshwaram_bengaluru: "Malleshwaram, Bengaluru",
    crime_hotspot_zone: "Crime hotspot zone",

    // --- NEW GRAPH TRANSLATIONS ---
    all_connections: "All Connections",
    criminal_network: "Criminal Network",
    gang_network: "Gang Network",
    evidence_links: "Evidence Links",
    select_node: "Select a Node",
    click_node_desc: "Click on any node in the graph to view details",
    risk: "Risk",
    cases: "Cases",
    connections: "Connections",
    view_full_profile: "View Full Profile",
    add_to_investigation: "Add to Investigation",
    // Graph Suspects
    ravi_kumar: "Ravi Kumar",
    deepak_reddy: "Deepak Reddy",
    mohammed_ali: "Mohammed Ali",
    imran_khan: "Imran Khan",
    venkatesh_reddy: "Venkatesh Reddy",
    rajesh_sharma: "Rajesh Sharma",
    // Graph Evidence/Node type labels
    cctv_4521: "CCTV #4521",
    phone_records: "Phone Records",
    fingerprint: "Fingerprint",
    suspect: "Suspect",
    vehicle: "Vehicle",
    phone: "Phone",
    // Graph Edges
    accomplice: "Accomplice",
    fence: "Fence",
    operational_head: "Operational Head",
    training: "Training",
    logistics: "Logistics",
    cyber_ops: "Cyber Ops",
    parts_dealer: "Parts Dealer",
    identified: "Identified",
    cell_tower: "Cell tower",
    partial_print: "Partial print",
    registered: "Registered",
    used_in_crime: "Used in crime",
    primary: "Primary",
    burner: "Burner",
    shared: "Shared",

    // Chat History Titles
    fir_analysis_title: "FIR #4521 Analysis",
    suspect_network_title: "Suspect Network — Ravi Kumar",
    mo_pattern_title: "MO Pattern Research",
    cross_district_title: "Cross-district case linking",
    theft_pattern_title: "Theft pattern Bengaluru North",
    whisper_investigation_title: "Whisper alert investigation",
    evidence_report_title: "Evidence report generation",

    // --- MAP & GEOGRAPHIC TRANSLATIONS ---
    geo_intelligence: "Geo Intelligence",
    risk_level: "Risk Level",
    click_district_desc: "Click a district on the map to view details",
    crime_density: "Crime Density",
    recent_hotspots: "Recent Hotspots",
    active_routes: "Active Routes",
    suspect_movement: "Suspect Movement",
    case_connection: "Case Connection",
    districts: "Districts",
    last_updated: "Last Updated",

    // --- INVESTIGATION TRANSLATIONS ---
    search_investigations_placeholder: "Search investigations...",
    add_evidence: "Add Evidence",
    add_note_placeholder: "Add an investigation note...",
    add_note: "Add Note",
    just_now: "Just now",
    no_related_cases_found: "No related cases found",
    match: "match",
    add_event: "Add Event",
    bookmarks: "Bookmarks",
    bookmarked: "Bookmarked",
    add_bookmark: "Add Bookmark",
    reports: "Reports",
    export_pdf: "Export PDF",
    print: "Print",
    quick_actions: "Quick Actions",
    investigation_stats: "Investigation Stats",
    notes: "Notes",
    events: "Events",
    progress: "Progress",
    select_investigation: "Select an Investigation",
    choose_case_desc: "Choose a case from the list to start working",
    ai_analysis: "AI Analysis",
    recommended_actions: "Recommended Actions",
    pattern_analysis: "Pattern Analysis",
    jul: "Jul",
    si_karthik: "Karthik",
    inspector_deepak: "Inspector Deepak",
    cyber_cell: "Cyber Cell",
    ai_pattern_text_desc: "Based on historical data, cases with similar MO patterns have a 73% resolution rate when cross-district coordination is initiated within 48 hours.",
    high: "High",
    medium: "Medium",
    low: "Low",
    timeline: "Timeline",
    reasoning: "Reasoning",
    related: "Related Cases",
    search_reports_placeholder: "Search by report ID, title, case...",
    date: "Date",
    all_period: "All period",
    type: "Type",
    all_types: "All types",
    all_statuses: "All statuses",
    export_csv: "Export CSV",
    report_id: "Report ID",
    title: "Title",
    case: "Case",
    officer: "Officer",
    pages: "Pages",
    actions: "Actions",
    report_statistics: "Report Statistics",
    current_week: "Current Week",
    clear_all: "Clear all",
    saved_searches: "Saved Searches",
    save_current_search: "Save current search",
    no_saved_searches: "No saved searches",
    results: "results",
    run_search: "Run search",
    delete: "Delete",
    search_cases_placeholder: "Search cases, suspects, FIRs, evidence...",
    save_search: "Save search",
    voice_search: "Voice search",
    search: "Search",
    recent_searches: "Recent searches",
    search_history: "Search History",
    no_search_history: "No search history",
    no_results_found: "No results found",
    try_adjusting_search: "Try adjusting your search or filters",
    results_found: "results found",
    case_id: "Case ID",
    crime_type: "Crime Type",
    district: "District",
    open: "Open",
    all: "All",
    fir: "FIR",
    bengaluru: "Bengaluru",
    dashboard: "Dashboard",
    crime_analytics: "Crime Analytics",
    everything_analytical: "Everything analytical",
    resolution_rate: "Resolution Rate",
    copilot: "AI Copilot",
    knowledge_graph: "Knowledge Graph",
    crime_trend: "Crime Trend",
    daily: "Daily",
    weekly: "Weekly",
    monthly: "Monthly",
    annually: "Annually",
    cases_filed: "Cases Filed",
    investigation_rate: "Investigation Rate",
    active_firs: "Active FIRs",
    officers_on_duty: "Officers on Duty",
    vs_last_year: "vs last Year",
    vs_last_month: "vs last Month",
    vs_last_week: "vs last Week",
    vs_last_quarter: "vs last Quarter",
    analytics: "Analytics",
    crime_search: "Search Cases",
    search_everything: "Search everything",
    criminal_intelligence: "Criminal Intelligence",
    everything_about_suspects: "Everything about suspects",
    search_suspects_placeholder: "Search suspects by name, ID, alias...",
    high_risk: "High Risk",
    repeat: "Repeat Offenders",
    at_large: "At Large",
    under_trial: "Under Trial",
    yrs: "yrs",
    no_suspects_found: "No suspects found matching your criteria",
    arrested: "Arrested",
    under_investigation: "Under Investigation",
    released: "Released",
    bengaluru_rural: "Bengaluru Rural",
    mangalaru: "Mangaluru",
    hubballi: "Hubballi",
    kumar_swamy: "Kumar Swamy",
    suresh_patel: "Suresh Patel",
  },
  ta: {
    settings: "அமைப்புகள்", personal_preferences: "தனிப்பட்ட விருப்பங்கள்", saving: "சேமிக்கப்படுகிறது...", saved: "சேமிக்கப்பட்டது!", save_changes: "மாற்றங்களைச் சேமி", profile: "சுயவிவரம்", edit_profile: "சுயவிவரத்தைத் திருத்து", opening: "திறக்கப்படுகிறது...", language: "மொழி", primary_language: "முதன்மை மொழி", secondary_language: "இரண்டாம் நிலை மொழி", ui_language: "UI மொழி (பயன்பாடு)", theme: "தீம்", notifications: "அறிவிப்புகள்", voice_settings: "குரல் அமைப்புகள்", voice_assistant: "குரல் உதவியாளர்", speed: "வேகம்", auto_transcribe: "தானியங்கு படியெடுத்தல்", offline_sync: "ஆஃப்லைன் ஒத்திசைவு", enable_offline: "ஆஃப்லைனை இயக்கு", sync_frequency: "ஒத்திசைவு அதிர்வெண்", storage_used: "பயன்படுத்தப்பட்ட சேமிப்பு", clear_cache: "தற்காலிக சேமிப்பை அழி", cleared: "அழிக்கப்பட்டது!", device_management: "சாதன மேலாண்மை", this_device: "இந்த சாதனம்", active: "செயலில்", last_sync: "கடைசி ஒத்திசைவு", minutes_ago: "நிமிடங்களுக்கு முன்", sync_now: "இப்போது ஒத்திசை", synced: "ஒத்திசைக்கப்பட்டது!", other_devices: "பிற சாதனங்கள்", tablet: "டேப்லெட்", desktop: "டெஸ்க்டாப்", manage_devices: "சாதனங்களை நிர்வகி", light: "ஒளி", dark: "இருண்ட", system: "கணினி", push: "தள்ளு", email: "மின்னஞ்சல்", sound: "ஒலி", whisper: "விஸ்பர்",
    accept: "ஒப்புக்கொள்",
    dismiss: "நிராகரி",
    view: "பார்",
    alert: "எச்சரிக்கை",
    priority: "முன்னுரிமை",
    status: "நிலை",
    alerts: "அவசரங்கள்",
    alert_feed: "அவசரப் புலம்",
    all_alerts: "அனைத்து எச்சரிக்கைகள்",
    new_alerts: "புதிய எச்சரிக்கைகள்",
    pending: "நிலுவையில் உள்ளது",
    resolved: "தீர்க்கப்பட்டது",
    total_alerts: "மொத்த எச்சரிக்கைகள்",
    alerts_by_type: "வகை வாரியாக எச்சரிக்கைகள்",
    recent_activity: "சமீபத்திய நடவடிக்கை",
    crime_heatmap: "குற்ற வெப்ப வரைபடம்",
    whisper_alert: "விஸ்பர் எச்சரிக்கை",
    fir_match: "எஃப்.ஐ.ஆர் பொருத்தம்",
    cross_district: "மாவட்டங்களுக்கு இடையேயான",
    evidence_link: "ஆதார இணைப்பு",
    ai_notification: "செயற்கை நுண்ணறிவு அறிவிப்பு",
    intelligence_alerts: "உளவுத்துறை எச்சரிக்கைகள்",
    monitor_intel: "செயலில் உள்ள உளவுத்துறையை கண்காணித்து பதிலளிக்கவும்",
    performance_summary: "எச்சரிக்கை செயல்திறன் சுருக்கம்",
    pending_review: "மதிப்பாய்வு நிலுவையில் உள்ளது",
    alert_trend: "எச்சரிக்கை போக்கு",
    alert_distribution: "எச்சரிக்கை விநியோகம்",
    total: "மொத்தம்",
    recent_alerts: "சமீபத்திய எச்சரிக்கைகள்",
    more_details: "கூடுதல் விவரங்கள்",
    // Analytics & Charts Translation
    crime_breakdown: "குற்ற வகை முறிவு",
    cases_label: "வழக்குகள்",
    cases_by_crime_type: "குற்ற வகை வாரியாக வழக்குகள்",
    todays_cases: "இன்றைய வழக்குகள்",
    live: "நேரலை",
    total_cases: "மொத்த வழக்குகள்",
    theft: "களவு",
    fraud: "மோசடி",
    cybercrime: "சைபர் குற்றம்",
    assault: "தாக்குதல்",
    other: "இதர",
    top_districts: "முன்னணி மாவட்டங்கள்",
    by_case_count: "வழக்குகளின் எண்ணிக்கை அடிப்படையில்",
    case_resolution: "வழக்கு தீர்வு",
    by_time_period: "கால அளவின் அடிப்படையில்",
    total_resolved: "மொத்தம் தீர்க்கப்பட்டவை",
    avg_resolution: "சராசரி தீர்வு",
    case_trend: "வழக்கு போக்கு",
    time_interval: "கால இடைவெளி:",
    weekly: "வாராந்திர",
    monthly: "மாதாந்திர",
    yearly: "வருடாந்திர",
    vs_30_days: "கடந்த 30 நாட்களில்",
    cases_by_district: "மாவட்ட வாரியாக வழக்குகள்",
    investigation_calendar: "விசாரணை நாட்காட்டி",
    hearings: "விசாரணைகள்",
    shifts: "பணிகள்",
    cases_by_status: "நிலை வாரியாக வழக்குகள்",
    active: "செயலில் உள்ளது",
    under_investigation: "விசாரணையில் உள்ளது",
    closed: "முடிக்கப்பட்டது",
    // Calendar Events
    court_hearing: "நீதிமன்ற விசாரணை — FIR #4489",
    bail_review: "ஜாமீன் ஆய்வு — வழக்கு #4512",
    shift_handover: "பணி ஒப்படைப்பு — காலை",
    night_patrol: "இரவு ரோந்து விளக்கக்காட்சி",
    // Districts
    bengaluru_urban: "பெங்களூரு நகர்ப்புறம்",
    bengaluru_rural: "பெங்களூரு ஊரக",
    mysuru: "மைசூரு",
    mangalaru: "மங்களூரு",
    hubballi: "ஹூப்ளி",
    // Days/Periods
    days_label: "நாட்கள்",
    "0-30 days": "0-30 நாட்கள்",
    "31-60 days": "31-60 நாட்கள்",
    "61-90 days": "61-90 நாட்கள்",
    "91-180 days": "91-180 நாட்கள்",
    "180+ days": "180+ நாட்கள்",
    Sun: "ஞாயிறு",
    Mon: "திங்கள்",
    Tue: "செவ்வாய்",
    Wed: "புதன்",
    Thu: "வியாழன்",
    Fri: "வெள்ளி",
    Sat: "சனி",

    // --- NEW COPILOT TRANSLATIONS ---
    analyzing: "ஆராய்கிறது...",
    ai_copilot: "AI copilot",
    hi_there: "வணக்கம் 👋",
    ask_copilot: "வழக்குகள், சந்தேக நபர்கள் அல்லது விசாரணைகள் பற்றி என்னிடம் எது வேண்டுமானாலும் கேளுங்கள்.",
    chat_history: "உரையாடல் வரலாறு",
    new_chat: "புதிய உரையாடல்",
    saved: "சேமிக்கப்பட்டது",
    today: "இன்று",
    yesterday: "நேற்று",
    ask_anything_placeholder: "என்னிடம் எதையும் கேளுங்கள்...",
    all_sources: "அனைத்து ஆதாரங்கள்",
    fir_database: "எஃப்.ஐ.ஆர் தரவுத்தளம்",
    suspects: "சந்தேக நபர்கள்",
    evidence: "ஆதாரம்",
    stations: "நிலையங்கள்",
    context: "சூழல்",
    referenced_sources: "குறிப்பிடப்பட்ட ஆதாரங்கள்",
    actions: "செயல்கள்",
    related_cases: "தொடர்புடைய வழக்குகள்",
    generate_report: "அறிக்கையை உருவாக்கு",
    export_conversation: "உரையாடலை ஏற்றுமதி செய்",
    save_to_case: "வழக்கில் சேமி",
    share_with_team: "குழுவுடன் பகிர்",
    robbery_indiranagar: "கொள்ளை — இந்திராநகர்",
    theft_koramangala: "களவு — கோரமங்களா",
    cyber_fraud_ecity: "சைபர் மோசடி — எலக்ட்ரானிக் சிட்டி",
    copilot_assistant_desc: "உங்கள் AI விசாரணை உதவியாளர் — கர்நாடகா காவல் நெறிமுறைகள், குற்றவியல் தரவுத்தளங்கள் மற்றும் சட்ட கட்டமைப்புகள் ஆகியவற்றில் பயிற்சி பெற்றவர்.",
    quick_tasks: "விரைவான பணிகள்",
    suggested_prompt: "பரிந்துரைக்கப்பட்ட கேள்வி",
    task_analyze_connections: "சந்தேக நபரின் இணைப்புகளை பகுப்பாய்வு செய்",
    task_generate_report: "விசாரணை அறிக்கையை உருவாக்கு",
    task_search_cross_district: "மாவட்டங்களுக்கு இடையேயான வழக்குகளைத் தேடு",
    suggested_prompt_text: "இந்த மாதம் பெங்களூரு மாவட்டம் முழுவதும் களவு வழக்குகளில் பொதுவான MO முறைகள் யாவை?",
    theft_malleshwaram: "களவு — மல்லேஸ்வரம், பெங்களூரு",
    suspect_linked_3_cases: "3 திறந்த வழக்குகளுடன் தொடர்புடையது",
    cctv_footage_main_road: "சிசிடிவி காட்சிகள் — முக்கிய சாலை",
    captured_at_215_am: "அதிகாலை 2:15 மணிக்கு எடுக்கப்பட்டது",
    malleshwaram_bengaluru: "மல்லேஸ்வரம், பெங்களூரு",
    crime_hotspot_zone: "குற்றங்கள் அதிகம் நடக்கும் பகுதி",

    // --- NEW GRAPH TRANSLATIONS ---
    all_connections: "அனைத்து இணைப்புகள்",
    criminal_network: "குற்றவியல் நெட்வொர்க்",
    gang_network: "கும்பல் நெட்வொர்க்",
    evidence_links: "ஆதார இணைப்புகள்",
    select_node: "ஒரு முனையைத் தேர்ந்தெடுக்கவும்",
    click_node_desc: "விவரங்களைக் காண வரைபடத்தில் உள்ள ஏதேனும் முனையை சொடுக்கவும்",
    risk: "அபாயம்",
    cases: "வழக்குகள்",
    connections: "இணைப்புகள்",
    view_full_profile: "முழு சுயவிவரத்தைக் காட்டு",
    add_to_investigation: "விசாரணையில் சேர்",
    // Graph Suspects
    ravi_kumar: "ரவி குமார்",
    deepak_reddy: "தீபக் ரெட்டி",
    mohammed_ali: "முகமது அலி",
    imran_khan: "இம்ரான் கான்",
    venkatesh_reddy: "வெங்கடேஷ் ரெட்டி",
    rajesh_sharma: "ராஜேஷ் சர்மா",
    // Graph Evidence/Node type labels
    cctv_4521: "சிசிடிவி #4521",
    phone_records: "தொலைபேசி பதிவுகள்",
    fingerprint: "கைரேகை",
    suspect: "சந்தேக நபர்",
    vehicle: "வாகனம்",
    phone: "தொலைபேசி",
    // Graph Edges
    accomplice: "கூட்டாளி",
    fence: "பெறுபவர் (வேலி)",
    operational_head: "செயல்பாட்டுத் தலைவர்",
    training: "பயிற்சி",
    logistics: "தளவாடங்கள்",
    cyber_ops: "சைபர் செயல்பாடுகள்",
    parts_dealer: "உதிரிபாகங்கள் வியாபாரி",
    identified: "அடையாளம் காணப்பட்டது",
    cell_tower: "செல் கோபுரம்",
    partial_print: "பகுதி கைரேகை",
    registered: "பதிவு செய்யப்பட்டது",
    used_in_crime: "குற்றத்தில் பயன்படுத்தப்பட்டது",
    primary: "முதன்மை",
    burner: "பர்னர்",
    shared: "பகிரப்பட்டது",

    // Chat History Titles
    fir_analysis_title: "எஃப்.ஐ.ஆர் #4521 பகுப்பாய்வு",
    suspect_network_title: "சந்தேக நபர் நெட்வொர்க் — ரவி குமார்",
    mo_pattern_title: "குற்றச் செயல் பாணி ஆராய்ச்சி",
    cross_district_title: "மாவட்டங்களுக்கு இடையேயான இணைப்பு",
    theft_pattern_title: "பெங்களூரு வடக்கு களவு பாணி",
    whisper_investigation_title: "விஸ்பர் எச்சரிக்கை விசாரணை",
    evidence_report_title: "ஆதார அறிக்கை தயாரித்தல்",

    // --- MAP & GEOGRAPHIC TRANSLATIONS ---
    geo_intelligence: "புவிசார் நுண்ணறிவு",
    risk_level: "அபாய நிலை",
    click_district_desc: "விவரங்களைக் காண வரைபடத்தில் உள்ள ஏதேனும் மாவட்டத்தை சொடுக்கவும்",
    crime_density: "குற்ற அடர்த்தி",
    recent_hotspots: "சமீபத்திய ஹாட்ஸ்பாட்கள்",
    active_routes: "செயலில் உள்ள வழிகள்",
    suspect_movement: "சந்தேக நபர் நடமாட்டம்",
    case_connection: "வழக்கு இணைப்பு",
    districts: "மாவட்டங்கள்",
    last_updated: "கடைசியாக புதுப்பிக்கப்பட்டது",

    // --- INVESTIGATION TRANSLATIONS ---
    search_investigations_placeholder: "விசாரணைகளைத் தேடு...",
    add_evidence: "ஆதாரத்தைச் சேர்",
    add_note_placeholder: "விசாரணைக் குறிப்பைச் சேர்க்கவும்...",
    add_note: "குறிப்பைச் சேர்",
    just_now: "இப்போது தான்",
    no_related_cases_found: "தொடர்புடைய வழக்குகள் எதுவும் இல்லை",
    match: "பொருத்தம்",
    add_event: "நிகழ்வைச் சேர்",
    bookmarks: "புக்மார்க்குகள்",
    bookmarked: "புக்மார்க் செய்யப்பட்டது",
    add_bookmark: "புக்மார்க்கைச் சேர்",
    reports: "அறிக்கைகள்",
    export_pdf: "PDF ஏற்றுமதி",
    print: "அச்சிடுக",
    quick_actions: "விரைவான செயல்கள்",
    investigation_stats: "விசாரணை புள்ளிவிவரங்கள்",
    notes: "குறிப்புகள்",
    events: "நிகழ்வுகள்",
    progress: "முன்னேற்றம்",
    select_investigation: "ஒரு விசாரணையைத் தேர்ந்தெடுக்கவும்",
    choose_case_desc: "வேலையைத் தொடங்க பட்டியலில் இருந்து ஒரு வழக்கைத் தேர்வுசெய்யவும்",
    ai_analysis: "செயற்கை நுண்ணறிவு பகுப்பாய்வு",
    recommended_actions: "பரிந்துரைக்கப்பட்ட செயல்கள்",
    pattern_analysis: "பாணி பகுப்பாய்வு",
    jul: "ஜூலை",
    si_karthik: "கார்த்திக்",
    inspector_deepak: "ஆய்வாளர் தீபக்",
    cyber_cell: "சைபர் பிரிவு",
    ai_pattern_text_desc: "வரலாற்றுத் தரவுகளின் அடிப்படையில், 48 மணி நேரத்திற்குள் மாவட்டங்களுக்கு இடையேயான ஒருங்கிணைப்பு தொடங்கப்பட்டால், ஒத்த MO வடிவங்களைக் கொண்ட வழக்குகள் 73% தீர்வு விகிதத்தைக் கொண்டுள்ளன.",
    high: "உயர்",
    medium: "நடுத்தர",
    low: "குறைந்த",
    timeline: "காலவரிசை",
    reasoning: "காரணங்கள்",
    related: "தொடர்புடைய வழக்குகள்",
    dashboard: "முகப்பு",
    crime_analytics: "குற்ற பகுப்பாய்வு",
    everything_analytical: "எல்லாம் பகுப்பாய்வு",
    resolution_rate: "தீர்வு விகிதம்",
    copilot: "கோ-பைலட்",
    knowledge_graph: "அறிவு வரைபடம்",
    crime_trend: "குற்றப் போக்கு",
    daily: "தினசரி",
    weekly: "வாராந்திர",
    monthly: "மாதாந்திர",
    annually: "வருடாந்திர",
    cases_filed: "பதிவான வழக்குகள்",
    investigation_rate: "விசாரணை விகிதம்",
    active_firs: "செயலில் உள்ள FIRகள்",
    officers_on_duty: "பணியில் உள்ள அதிகாரிகள்",
    vs_last_year: "கடந்த ஆண்டை விட",
    vs_last_month: "கடந்த மாதத்தை விட",
    vs_last_week: "கடந்த வாரத்தை விட",
    vs_last_quarter: "கடந்த காலாண்டை விட",
    analytics: "பகுப்பாய்வு",
    clear_all: "அனைத்தையும் அழி",
    saved_searches: "சேமிக்கப்பட்ட தேடல்கள்",
    save_current_search: "தற்போதைய தேடலைச் சேமி",
    no_saved_searches: "சேமிக்கப்பட்ட தேடல்கள் இல்லை",
    results: "முடிவுகள்",
    run_search: "தேடலைத் தொடங்கு",
    delete: "அழி",
    search_cases_placeholder: "வழக்குகள், சந்தேக நபர்கள், FIRகள், ஆதாரங்களைத் தேடு...",
    save_search: "தேடலைச் சேமி",
    voice_search: "குரல் தேடல்",
    search: "தேடு",
    recent_searches: "சமீபத்திய தேடல்கள்",
    search_history: "தேடல் வரலாறு",
    no_search_history: "தேடல் வரலாறு இல்லை",
    no_results_found: "முடிவுகள் எதுவும் கிடைக்கவில்லை",
    try_adjusting_search: "உங்கள் தேடல் அல்லது வடிப்பான்களை மாற்றி முயற்சிக்கவும்",
    results_found: "முடிவுகள் கிடைத்தன",
    case_id: "வழக்கு ஐடி",
    crime_type: "குற்ற வகை",
    district: "மாவட்டம்",
    open: "திறந்துள்ளது",
    all: "அனைத்தும்",
    fir: "FIR",
    bengaluru: "பெங்களூரு",
    crime_search: "வழக்குகளைத் தேடு",
    search_everything: "அனைத்தையும் தேடு",
    title: "தலைப்பு",
    date: "தேதி",
    status: "நிலை",
    actions: "செயல்கள்",
    criminal_intelligence: "குற்றவியல் நுண்ணறிவு",
    everything_about_suspects: "சந்தேக நபர்கள் பற்றிய அனைத்தும்",
    search_suspects_placeholder: "பெயர், ஐடி, மாற்றுப் பெயரால் சந்தேக நபர்களைத் தேடு...",
    high_risk: "அதிக அபாயம்",
    repeat: "தொடர் குற்றவாளிகள்",
    at_large: "தலைமறைவு",
    under_trial: "விசாரணையில்",
    yrs: "வயது",
    no_suspects_found: "உங்கள் அளவுகோல்களுடன் பொருந்தக்கூடிய சந்தேக நபர்கள் யாரும் கிடைக்கவில்லை",
    arrested: "கைது",
    under_investigation: "விசாரணையில்",
    released: "விடுவிக்கப்பட்டார்",
    bengaluru_urban: "பெங்களூரு நகர்ப்புறம்",
    bengaluru_rural: "பெங்களூரு ஊரகம்",
    mysuru: "மைசூரு",
    hubballi: "ஹூப்பள்ளி",
    mangalaru: "மங்களூரு",
    kumar_swamy: "குமார் சுவாமி",
    suresh_patel: "சுரேஷ் படேல்",
  },
  kn: {
    settings: "ಅமைப்புகள்", personal_preferences: "ವೈಯಕ್ತಿಕ ಆದ್ಯತೆಗಳು", saving: "ಉಳಿಸಲಾಗುತ್ತಿದೆ...", saved: "ಉಳಿಸಲಾಗಿದೆ!", save_changes: "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ", profile: "ಪ್ರೊಫೈಲ್", edit_profile: "ಪ್ರೊಫೈಲ್ ಎಡಿಟ್ ಮಾಡಿ", opening: "ತೆರೆಯಲಾಗುತ್ತಿದೆ...", language: "ಭಾಷೆ", primary_language: "ಪ್ರಾಥಮಿಕ ಭಾಷೆ", secondary_language: "ದ್ವಿತೀಯ ಭಾಷೆ", ui_language: "UI ಭಾಷೆ (ಅಪ್ಲಿಕೇಶನ್)", theme: "ಥೀಮ್", notifications: "ಅಧಿಸೂಚನೆಗಳು", voice_settings: "ಧ್ವನಿ ಸೆಟ್ಟಿಂಗ್‌ಗಳು", voice_assistant: "ಧ್ವನಿ ಸಹಾಯಕ", speed: "ವೇಗ", auto_transcribe: "ಸ್ವಯಂ ನಕಲು", offline_sync: "ಆಫ್‌ಲೈನ್ ಸಿಂಕ್", enable_offline: "ಆಫ್‌ಲೈನ್ ಸಕ್ರಿಯಗೊಳಿಸಿ", sync_frequency: "ಸಿಂಕ್ ಆವರ್ತನ", storage_used: "ಬಳಕೆಯಾದ ಶೇಖರಣೆ", clear_cache: "ಕ್ಯಾಶ್ ತೆರವುಗೊಳಿಸಿ", cleared: "ತೆರವುಗೊಳಿಸಲಾಗಿದೆ!", device_management: "ಸಾಧನ ನಿರ್ವಹಣೆ", this_device: "ಈ ಸಾಧನ", active: "ಸಕ್ರಿಯ", last_sync: "ಕೊನೆಯ ಸಿಂಕ್", minutes_ago: "ನಿಮಿಷಗಳ ಹಿಂದೆ", sync_now: "ಈಗ ಸಿಂಕ್ ಮಾಡಿ", synced: "ಸಿಂಕ್ ಮಾಡಲಾಗಿದೆ!", other_devices: "ಇತರ ಸಾಧನಗಳು", tablet: "ಟ್ಯಾಬ್ಲೆಟ್", desktop: "ಡೆಸ್ಕ್‌ಟಾಪ್", manage_devices: "ಸಾಧನಗಳನ್ನು ನಿರ್ವಹಿಸಿ", light: "ಬೆಳಕು", dark: "ಕತ್ತಲೆ", system: "ವ್ಯವಸ್ಥೆ", push: "ಪುಶ್", email: "ಇಮೇಲ್", sound: "ಧ್ವನಿ", whisper: "ವಿಸ್ಪರ್",
    accept: "ಸ್ವೀಕರಿಸಿ",
    dismiss: "ಮುಂದುವರಿಕೆ",
    view: "ವೀಕ್ಷಿಸು",
    alert: "ಎಚ್ಚರಿಕೆ",
    priority: "ಪ್ರಾಮುಖ್ಯತೆಯ",
    status: "ಸ್ಥಿತಿ",
    alerts: "ಎಚ್ಚರಿಕೆಗಳು",
    alert_feed: "ಎಚ್ಚರಿಕಾ ಫೀಡ್",
    all_alerts: "ಎಲ್ಲಾ ಎಚ್ಚರಿಕೆಗಳು",
    new_alerts: "ಹೊಸ ಎಚ್ಚರಿಕೆಗಳು",
    pending: "ಬಾಕಿ ಉಳಿದಿರುವ",
    resolved: "ಪರಿಹರಿಸಲಾಗಿದೆ",
    total_alerts: "ಒಟ್ಟು ಎಚ್ಚರಿಕೆಗಳು",
    alerts_by_type: "ಮಾದರಿ ಪ್ರಕಾರ ಎಚ್ಚರಿಕೆಗಳು",
    recent_activity: "ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ",
    crime_heatmap: "ಅಪರಾಧ ಶಾಖನಕ್ಷೆ",
    whisper_alert: "ವಿಸ್ಪರ್ ಎಚ್ಚರಿಕೆ",
    fir_match: "ಎಫ್‌ಐಆರ್ ಹೋಲಿಕೆ",
    cross_district: "ಅಂತರ-ಜಿಲ್ಲಾ",
    evidence_link: "ಸಾಕ್ಷ್ಯ ಲಿಂಕ್",
    ai_notification: "AI ಅಧಿಸೂಚನೆ",
    intelligence_alerts: "ಗುಪ್ತಚರ ಎಚ್ಚರಿಕೆಗಳು",
    monitor_intel: "ಸಕ್ರಿಯ ಗುಪ್ತಚರವನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ ಮತ್ತು ಪ್ರತಿಕ್ರಿಯಿಸಿ",
    performance_summary: "ಎಚ್ಚರಿಕೆ ಕಾರ್ಯಕ್ಷಮತೆಯ ಸಾರಾಂಶ",
    pending_review: "ಪರಿಶೀಲನೆ ಬಾಕಿ ಇದೆ",
    alert_trend: "ಎಚ್ಚರಿಕೆ ಪ್ರವೃತ್ತಿ",
    alert_distribution: "ಎಚ್ಚರಿಕೆ ವಿತರಣೆ",
    total: "ಒಟ್ಟು",
    recent_alerts: "ಇತ್ತೀಚಿನ ಎಚ್ಚರಿಕೆಗಳು",
    more_details: "ಹೆಚ್ಚಿನ ವಿವರಗಳು",
    // Analytics & Charts Translation
    crime_breakdown: "ಅಪರಾಧ ಪ್ರಕಾರದ ವಿಭಜನೆ",
    cases_label: "ಪ್ರಕರಣಗಳು",
    cases_by_crime_type: "ಅಪರಾಧ ಪ್ರಕಾರದ ಪ್ರಕರಣಗಳು",
    todays_cases: "ಇಂದಿನ ಪ್ರಕರಣಗಳು",
    live: "ಲೈವ್",
    total_cases: "ಒಟ್ಟು ಪ್ರಕರಣಗಳು",
    theft: "ಕಳ್ಳತನ",
    fraud: "ವಂಚನೆ",
    cybercrime: "ಸೈಬರ್ ಅಪರಾಧ",
    assault: "ದಾಳಿ",
    other: "ಇತರೆ",
    top_districts: "ಉನ್ನತ ಜಿಲ್ಲೆಗಳು",
    by_case_count: "ಪ್ರಕರಣಗಳ ಸಂಖ್ಯೆಯ ಆಧಾರದ ಮೇಲೆ",
    case_resolution: "ಪ್ರಕರಣದ ಪರಿಹಾರ",
    by_time_period: "ಸಮಯದ ಅವಧಿಯ ಆಧಾರದ ಮೇಲೆ",
    total_resolved: "ಒಟ್ಟು ಪರಿಹರಿಸಲಾಗಿದೆ",
    avg_resolution: "ಸರಾಸರಿ ಪರಿಹಾರ ಸಮಯ",
    case_trend: "ಪ್ರಕರಣದ ಪ್ರವೃತ್ತಿ",
    time_interval: "ಸಮಯದ ಮಧ್ಯಂತರ:",
    weekly: "ವಾರದ",
    monthly: "ತಿಂಗಳ",
    yearly: "ವರ್ಷದ",
    vs_30_days: "ಕಳೆದ 30 ದಿನಗಳ ವಿರುದ್ಧ",
    cases_by_district: "ಜಿಲ್ಲಾವಾರು ಪ್ರಕರಣಗಳು",
    investigation_calendar: "ತನಿಖಾ ಕ್ಯಾಲೆಂಡರ್",
    hearings: "ವಿಚಾರಣೆಗಳು",
    shifts: "ಶಿಫ್ಟ್‌ಗಳು",
    cases_by_status: "ಸ್ಥಿತಿವಾರು ಪ್ರಕರಣಗಳು",
    active: "ಸಕ್ರಿಯ",
    under_investigation: "ತನಿಖೆಯಲ್ಲಿದೆ",
    closed: "ಮುಚ್ಚಲಾಗಿದೆ",
    // Calendar Events
    court_hearing: "ನ್ಯಾಯಾಲಯದ ವಿಚಾರಣೆ — FIR #4489",
    bail_review: "ಜಾಮೀನು ಪರಿಶೀಲನೆ — ಪ್ರಕರಣ #4512",
    shift_handover: "ಶಿಫ್ಟ್ ಹಸ್ತಾಂತರ — ಬೆಳಿಗ್ಗೆ",
    night_patrol: "ರಾತ್ರಿ ಗಸ್ತು ಮಾಹಿತಿ",
    // Districts
    bengaluru_urban: "ಬೆಂಗಳೂರು ನಗರ",
    bengaluru_rural: "ಬೆಂಗಳೂರು ಗ್ರಾಮಾಂತರ",
    mysuru: "ಮೈಸೂರು",
    mangalaru: "ಮಂಗಳೂರು",
    hubballi: "ಹುಬ್ಬಳ್ಳಿ",
    // Days/Periods
    days_label: "ದಿನಗಳು",
    "0-30 days": "0-30 ದಿನಗಳು",
    "31-60 days": "31-60 ದಿನಗಳು",
    "61-90 days": "61-90 ದಿನಗಳು",
    "91-180 days": "91-180 ದಿನಗಳು",
    "180+ days": "180+ ದಿನಗಳು",
    Sun: "ಭಾನು",
    Mon: "ಸೋಮ",
    Tue: "ಮಗಳು",
    Wed: "ಬುಧ",
    Thu: "ಗುರು",
    Fri: "ಶುಕ್ರ",
    Sat: "ಶನಿ",

    // --- NEW COPILOT TRANSLATIONS ---
    analyzing: "ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
    ai_copilot: "AI ಕೊಪೈಲಟ್",
    hi_there: "ನಮಸ್ಕಾರ 👋",
    ask_copilot: "ಪ್ರಕರಣಗಳು, ಶಂಕಿತರು ಅಥವಾ ತನಿಖೆಗಳ ಬಗ್ಗೆ ನನ್ನನ್ನು ಏನಾದರೂ ಕೇಳಿ.",
    chat_history: "ಚಾಟ್ ಇತಿಹಾಸ",
    new_chat: "ಹೊಸ ಚಾಟ್",
    saved: "ಉಳಿಸಲಾಗಿದೆ",
    today: "ಇಂದು",
    yesterday: "ನಿನ್ನೆ",
    ask_anything_placeholder: "ನನ್ನನ್ನು ಏನಾದರೂ ಕೇಳಿ...",
    all_sources: "ಎಲ್ಲಾ ಮೂಲಗಳು",
    fir_database: "ಎಫ್‌ಐಆರ್ ಡೇಟಾಬೇಸ್",
    suspects: "ಶಂಕಿತರು",
    evidence: "ಸಾಕ್ಷ್ಯಗಳು",
    stations: "ಠಾಣೆಗಳು",
    context: "ಸಂದರ್ಭ",
    referenced_sources: "ಉಲ್ಲೇಖಿತ ಮೂಲಗಳು",
    actions: "ಕ್ರಮಗಳು",
    related_cases: "ಸಂಬಂಧಿತ ಪ್ರಕರಣಗಳು",
    generate_report: "ವರದಿ ರಚಿಸಿ",
    export_conversation: "ಚಾಟ್ ರಫ್ತು ಮಾಡಿ",
    save_to_case: "ಪ್ರಕರಣಕ್ಕೆ ಉಳಿಸಿ",
    share_with_team: "ತಂಡದೊಂದಿಗೆ ಹಂಚಿಕೊಳ್ಳಿ",
    robbery_indiranagar: "ದರೋಡೆ — ಇಂದಿರಾನಗರ",
    theft_koramangala: "ಕಳ್ಳತನ — ಕೋರಮಂಗಲ",
    cyber_fraud_ecity: "ಸೈಬರ್ ವಂಚನೆ — ಎಲೆಕ್ಟ್ರಾನಿಕ್ ಸಿಟಿ",
    copilot_assistant_desc: "ನಿಮ್ಮ AI ತನಿಖಾ ಸಹಾಯಕಿ — ಕರ್ನಾಟಕ ಪೊಲೀಸ್ ಪ್ರೋಟೋಕಾಲ್ಗಳು, ಅಪರಾಧ ಡೇಟಾಬೇಸ್ಗಳು ಮತ್ತು ಕಾನೂನು ಚೌಕಟ್ಟುಗಳ ಕುರಿತು ತರಬೇತಿ ಪಡೆದಿದೆ.",
    quick_tasks: "ತ್ವರಿತ ಕಾರ್ಯಗಳು",
    suggested_prompt: "ಸೂಚಿಸಲಾದ ಪ್ರಾಂಪ್ಟ್",
    task_analyze_connections: "ಶಂಕಿತರ ಸಂಪರ್ಕಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಿ",
    task_generate_report: "ತನಿಖಾ ವರದಿ ರಚಿಸಿ",
    task_search_cross_district: "ಅಂತರ-ಜಿಲ್ಲಾ ಪ್ರಕರಣಗಳನ್ನು ಹುಡುಕಿ",
    suggested_prompt_text: "ಈ ತಿಂಗಳು ಬೆಂಗಳೂರು ಜಿಲ್ಲೆಯಾದ್ಯಂತ ಕಳ್ಳತನ ಪ್ರಕರಣಗಳಲ್ಲಿನ ಸಾಮಾನ್ಯ MO ಮಾದರಿಗಳು ಯಾವುವು?",
    theft_malleshwaram: "ಕಳ್ಳತನ — ಮಲ್ಲೇಶ್ವರಂ, ಬೆಂಗಳೂರು",
    suspect_linked_3_cases: "3 ಬಾಕಿ ಪ್ರಕರಣಗಳಿಗೆ ಸಂಬಂಧಿಸಿದೆ",
    cctv_footage_main_road: "CCTV ದೃಶ್ಯಾವಳಿ — ಮುಖ್ಯ ರಸ್ತೆ",
    captured_at_215_am: "ಮುಂಜಾನೆ 2:15 ಕ್ಕೆ ಸೆರೆಹಿಡಿಯಲಾಗಿದೆ",
    malleshwaram_bengaluru: "ಮಲ್ಲೇಶ್ವರಂ, ಬೆಂಗಳೂರು",
    crime_hotspot_zone: "ಅಪರಾಧ ಸೂಕ್ಷ್ಮ ವಲಯ",

    // --- NEW GRAPH TRANSLATIONS ---
    all_connections: "ಎಲ್ಲಾ ಸಂಪರ್ಕಗಳು",
    criminal_network: "ಅಪರಾಧ ಜಾಲ",
    gang_network: "ಗ್ಯಾಂಗ್ ಜಾಲ",
    evidence_links: "ಸಾಕ್ಷ್ಯ ಲಿಂಕ್‌ಗಳು",
    select_node: "ನೋಡ್ ಆಯ್ಕೆಮಾಡಿ",
    click_node_desc: "ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಲು ಗ್ರಾಫ್‌ನಲ್ಲಿನ ಯಾವುದೇ ನೋಡ್ ಅನ್ನು ಕ್ಲಿಕ್ ಮಾಡಿ",
    risk: "ಅಪಾಯ",
    cases: "ಪ್ರಕರಣಗಳು",
    connections: "ಸಂಪರ್ಕಗಳು",
    view_full_profile: "ಪೂರ್ಣ ಪ್ರೊಫೈಲ್ ವೀಕ್ಷಿಸಿ",
    add_to_investigation: "ತನಿಖೆಗೆ ಸೇರಿಸಿ",
    // Graph Suspects
    ravi_kumar: "ರವಿ ಕುಮಾರ್",
    deepak_reddy: "ದೀಪಕ್ ರೆಡ್ಡಿ",
    mohammed_ali: "ಮೊಹಮ್ಮದ್ ಅಲಿ",
    imran_khan: "ಇಮ್ರಾನ್ ಖಾನ್",
    venkatesh_reddy: "ವೆಂಕಟೇಶ್ ರೆಡ್ಡಿ",
    rajesh_sharma: "ರಾಜೇಶ್ ಶರ್ಮಾ",
    // Graph Evidence/Node type labels
    cctv_4521: "ಸಿಸಿಟಿವಿ #4521",
    phone_records: "ದೂರವಾಣಿ ದಾಖಲೆಗಳು",
    fingerprint: "ಬೆರಳಚ್ಚು",
    suspect: "ಶಂಕಿತ",
    vehicle: "ವಾಹನ",
    phone: "ದೂರವಾಣಿ",
    // Graph Edges
    accomplice: "ಸಹಚರ",
    fence: "ಫೆನ್ಸ್",
    operational_head: "ಕಾರ್ಯಾಚರಣೆ ಮುಖ್ಯಸ್ಥ",
    training: "ತರಬೇತಿ",
    logistics: "ಸಾಗಣೆ ಮತ್ತು ವ್ಯವಸ್ಥೆ",
    cyber_ops: "ಸೈಬರ್ ಕಾರ್ಯಾಚರಣೆಗಳು",
    parts_dealer: "ಭಾಗಗಳ ವ್ಯಾಪಾರಿ",
    identified: "ಗುರುತಿಸಲಾಗಿದೆ",
    cell_tower: "ಸೆಲ್ ಟವರ್",
    partial_print: "ಅರೆ ಬೆರಳಚ್ಚು",
    registered: "ನೋಂದಾಯಿಸಲಾಗಿದೆ",
    used_in_crime: "ಅಪರಾಧದಲ್ಲಿ ಬಳಸಲಾಗಿದೆ",
    primary: "ಪ್ರಾಥಮಿಕ",
    burner: "ಬರ್ನರ್",
    shared: "ಹಂಚಿಕೊಳ್ಳಲಾಗಿದೆ",

    // Chat History Titles
    fir_analysis_title: "ಎಫ್‌ಐಆರ್ #4521 ವಿಶ್ಲೇಷಣೆ",
    suspect_network_title: "ಶಂಕಿತರ ಜಾಲ — ರವಿ ಕುಮಾರ್",
    mo_pattern_title: "ಎಂ.ಓ ವಿಧಾನ ಸಂಶೋಧನೆ",
    cross_district_title: "ಅಂತರ-ಜಿಲ್ಲಾ ಪ್ರಕರಣ ಸಂಯೋಜನೆ",
    theft_pattern_title: "ಬೆಂಗಳೂರು ಉತ್ತರ ಕಳ್ಳತನ ಮಾದರಿ",
    whisper_investigation_title: "ವಿಸ್ಪರ್ ಎಚ್ಚರಿಕೆ ತನಿಖೆ",
    evidence_report_title: "ಸಾಕ್ಷ್ಯಾಧಾರ ವರದಿ ಸಿದ್ಧತೆ",

    // --- MAP & GEOGRAPHIC TRANSLATIONS ---
    geo_intelligence: "ಭೌಗೋಳಿಕ ಬುದ್ಧಿಮತ್ತೆ",
    risk_level: "ಅಪಾಯದ ಮಟ್ಟ",
    click_district_desc: "ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಲು ನಕ್ಷೆಯಲ್ಲಿ ಜಿಲ್ಲೆಯನ್ನು ಕ್ಲಿಕ್ ಮಾಡಿ",
    crime_density: "ಅಪರಾಧ ಸಾಂದ್ರತೆ",
    recent_hotspots: "ಇತ್ತೀಚಿನ ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳು",
    active_routes: "ಸಕ್ರಿಯ ಮಾರ್ಗಗಳು",
    suspect_movement: "ಶಂಕಿತರ ಚಲನವಲನ",
    case_connection: "ಪ್ರಕರಣದ ಸಂಪರ್ಕ",
    districts: "ಜಿಲ್ಲೆಗಳು",
    last_updated: "ಕೊನೆಯದಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ",

    // --- INVESTIGATION TRANSLATIONS ---
    search_investigations_placeholder: "ತನಿಖೆಗಳನ್ನು ಹುಡುಕಿ...",
    add_evidence: "ಸಾಕ್ಷ್ಯ ಸೇರಿಸಿ",
    add_note_placeholder: "ತನಿಖಾ ಟಿಪ್ಪಣಿ ಸೇರಿಸಿ...",
    add_note: "ಟಿಪ್ಪಣಿ ಸೇರಿಸಿ",
    just_now: "ಈಗ ತಾನೇ",
    no_related_cases_found: "ಯಾವುದೇ ಸಂಬಂಧಿತ ಪ್ರಕರಣಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
    match: "ಹೊಂದಾಣಿಕೆ",
    add_event: "ಘಟನೆ ಸೇರಿಸಿ",
    bookmarks: "ಬುಕ್‌ಮಾರ್ಕ್‌ಗಳು",
    bookmarked: "ಬುಕ್‌ಮಾರ್ಕ್ ಮಾಡಲಾಗಿದೆ",
    add_bookmark: "ಬುಕ್‌ಮಾರ್ಕ್ ಸೇರಿಸಿ",
    reports: "ವರದಿಗಳು",
    export_pdf: "PDF ರಫ್ತು ಮಾಡಿ",
    print: "ಪ್ರಿಂಟ್ ಮಾಡಿ",
    quick_actions: "ತ್ವರಿತ ಕ್ರಿಯೆಗಳು",
    investigation_stats: "ತನಿಖಾ ಅಂಕಿಅಂಶಗಳು",
    notes: "ಟಿಪ್ಪಣಿಗಳು",
    events: "ಘಟನೆಗಳು",
    progress: "ಪ್ರಗತಿ",
    select_investigation: "ತನಿಖೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    choose_case_desc: "ಕೆಲಸ ಪ್ರಾರಂಭಿಸಲು ಪಟ್ಟಿಯಿಂದ ಪ್ರಕರಣವನ್ನು ಆರಿಸಿ",
    ai_analysis: "AI ವಿಶ್ಲೇಷಣೆ",
    recommended_actions: "ಶಿಫಾರಸು ಮಾಡಿದ ಕ್ರಮಗಳು",
    pattern_analysis: "ಮಾದರಿ ವಿಶ್ಲೇಷಣೆ",
    jul: "ಜುಲೈ",
    si_karthik: "ಕಾರ್ತಿಕ್",
    inspector_deepak: "ಇನ್ಸ್ಪೆಕ್ಟರ್ ದೀಪಕ್",
    cyber_cell: "ಸೈಬರ್ ಸೆಲ್",
    ai_pattern_text_desc: "ಐತಿಹಾಸಿಕ ದತ್ತಾಂಶದ ಆಧಾರದ ಮೇಲೆ, 48 ಗಂಟೆಗಳ ಒಳಗೆ ಅಂತರ-ಜಿಲ್ಲಾ ಸಮನ್ವಯವನ್ನು ಪ್ರಾರಂಭಿಸಿದಾಗ ಇದೇ ರೀತಿಯ MO ಮಾದರಿಯ ಪ್ರಕರಣಗಳು 73% ಪರಿಹಾರ ದರವನ್ನು ಹೊಂದಿರುತ್ತವೆ.",
    high: "ಹೆಚ್ಚು",
    medium: "ಮಧ್ಯಮ",
    low: "ಕಡಿಮೆ",
    timeline: "ಸಮಯರೇಖೆ",
    reasoning: "ತಾರ್ಕಿಕ ವಿವರಣೆ",
    related: "ಸಂಬಂಧಿತ ಪ್ರಕರಣಗಳು",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    crime_analytics: "ಅಪರಾಧ ವಿಶ್ಲೇಷಣೆ",
    everything_analytical: "ಎಲ್ಲವೂ ವಿಶ್ಲೇಷಣಾತ್ಮಕ",
    resolution_rate: "ಪರಿಹಾರ ದರ",
    copilot: "ಕೊಪೈಲಟ್",
    knowledge_graph: "ಜ್ಞಾನ ನಕ್ಷೆ",
    crime_trend: "ಅಪರಾಧದ ಒಲವು",
    daily: "ದೈನಂದಿನ",
    weekly: "ವಾರದ",
    monthly: "ತಿಂಗಳ",
    annually: "ವಾರ್ಷಿಕ",
    cases_filed: "ದಾಖಲಾದ ಪ್ರಕರಣಗಳು",
    investigation_rate: "ತನಿಖಾ ದರ",
    active_firs: "ಸಕ್ರಿಯ FIR ಗಳು",
    officers_on_duty: "ಕರ್ತವ್ಯದಲ್ಲಿರುವ ಅಧಿಕಾರಿಗಳು",
    vs_last_year: "ಕಳೆದ ವರ್ಷದ ವಿರುದ್ಧ",
    vs_last_month: "ಕಳೆದ ತಿಂಗಳ ವಿರುದ್ಧ",
    vs_last_week: "ಕಳೆದ ವಾರದ ವಿರುದ್ಧ",
    vs_last_quarter: "ಕಳೆದ ತ್ರೈಮಾಸಿಕ ವಿರುದ್ಧ",
    analytics: "ವಿಶ್ಲೇಷಣೆ",
    clear_all: "ಎಲ್ಲವನ್ನೂ ತೆರವುಗೊಳಿಸಿ",
    saved_searches: "ಉಳಿಸಿದ ಹುಡುಕಾಟಗಳು",
    save_current_search: "ಪ್ರಸ್ತುತ ಹುಡುಕಾಟವನ್ನು ಉಳಿಸಿ",
    no_saved_searches: "ಉಳಿಸಿದ ಹುಡುಕಾಟಗಳಿಲ್ಲ",
    results: "ಫಲಿತಾಂಶಗಳು",
    run_search: "ಹುಡುಕಾಟವನ್ನು ಪ್ರಾರಂಭಿಸಿ",
    delete: "ಅಳಿಸಿ",
    search_cases_placeholder: "ಪ್ರಕರಣಗಳು, ಶಂಕಿತರು, ಎಫ್ಐಆರ್‌ಗಳು, ಸಾಕ್ಷ್ಯಗಳನ್ನು ಹುಡುಕಿ...",
    save_search: "ಹುಡುಕಾಟವನ್ನು ಉಳಿಸಿ",
    voice_search: "ಧ್ವನಿ ಹುಡುಕಾಟ",
    search: "ಹುಡುಕಿ",
    recent_searches: "ಇತ್ತೀಚಿನ ಹುಡುಕಾಟಗಳು",
    search_history: "ಹುಡುಕಾಟ ಇತಿಹಾಸ",
    no_search_history: "ಯಾವುದೇ ಹುಡುಕಾಟ ಇತಿಹಾಸವಿಲ್ಲ",
    no_results_found: "ಯಾವುದೇ ಫಲಿತಾಂಶಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
    try_adjusting_search: "ನಿಮ್ಮ ಹುಡುಕಾಟ ಅಥವಾ ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಸರಿಹೊಂದಿಸಲು ಪ್ರಯತ್ನಿಸಿ",
    results_found: "ಫಲಿತಾಂಶಗಳು ಕಂಡುಬಂದಿವೆ",
    case_id: "ಪ್ರಕರಣ ಐಡಿ",
    crime_type: "ಅಪರಾಧ ಪ್ರಕಾರ",
    district: "ಜಿಲ್ಲೆ",
    open: "ತೆರೆದಿದೆ",
    all: "ಎಲ್ಲಾ",
    fir: "FIR",
    bengaluru: "ಬೆಂಗಳೂರು",
    crime_search: "ಪ್ರಕರಣಗಳನ್ನು ಹುಡುಕಿ",
    search_everything: "ಎಲ್ಲವನ್ನೂ ಹುಡುಕಿ",
    title: "ಶೀರ್ಷಿಕೆ",
    date: "ದಿನಾಂಕ",
    status: "ಸ್ಥಿತಿ",
    actions: "ಕ್ರಿಯೆಗಳು",
    criminal_intelligence: "ಅಪರಾಧ ಗುಪ್ತಚರ",
    everything_about_suspects: "ಶಂಕಿತರ ಬಗ್ಗೆ ಎಲ್ಲವೂ",
    search_suspects_placeholder: "ಹೆಸರು, ಐಡಿ, ಅಲಿಯಾಸ್ ಮೂಲಕ ಶಂಕಿತರನ್ನು ಹುಡುಕಿ...",
    high_risk: "ಹೆಚ್ಚಿನ ಅಪಾಯ",
    repeat: "ಪುನರಾವರ್ತಿತ ಅಪರಾಧಿಗಳು",
    at_large: "ತಲೆಮರೆಸಿಕೊಂಡಿದ್ದಾರೆ",
    under_trial: "ವಿಚಾರಣೆಯಲ್ಲಿದ್ದಾರೆ",
    yrs: "ವರ್ಷ",
    no_suspects_found: "ನಿಮ್ಮ ಮಾನದಂಡಗಳಿಗೆ ಹೊಂದುವ ಯಾವುದೇ ಶಂಕಿತರು ಕಂಡುಬಂದಿಲ್ಲ",
    arrested: "ಬಂಧಿಸಲಾಗಿದೆ",
    under_investigation: "ತನಿಖೆಯಲ್ಲಿದೆ",
    released: "ಬಿಡುಗಡೆಯಾಗಿದ್ದಾರೆ",
    bengaluru_urban: "ಬೆಂಗಳೂರು ನಗರ",
    bengaluru_rural: "ಬೆಂಗಳೂರು ಗ್ರಾಮಾಂತರ",
    mysuru: "ಮೈಸೂರು",
    hubballi: "ಹುಬ್ಬಳ್ಳಿ",
    mangalaru: "ಮಂಗಳೂರು",
    kumar_swamy: "ಕುಮಾರ್ ಸ್ವಾಮಿ",
    suresh_patel: "ಸುರೇಶ್ ಪಟೇಲ್",
  },
  te: {
    settings: "సెట్టింగులు", personal_preferences: "వ్యక్తిగత ప్రాధాన్యతలు", saving: "సేవ్ చేయబడుతోంది...", saved: "సేవ్ చేయబడింది!", save_changes: "మార్పులను సేవ్ చేయండి", profile: "ప్రొఫైల్", edit_profile: "ప్రొఫైల్‌ను సవరించండి", opening: "తెరవబడుతోంది...", language: "భాష", primary_language: "ప్రాథమిక భాష", secondary_language: "ద్వితీయ భాష", ui_language: "UI భాష (యాప్)", theme: "థీమ్", notifications: "నోటిఫికేషన్‌లు", voice_settings: "వాయిస్ సెట్టింగులు", voice_assistant: "వాయిస్ అసిస్టెంట్", speed: "వేగం", auto_transcribe: "ఆటో-ట్రాన్స్‌క్రైబ్", offline_sync: "ఆఫ్‌లైన్ సమకాలీకరణ", enable_offline: "ఆఫ్‌లైన్‌ను ప్రారంభించండి", sync_frequency: "సమకాలీకరణ ఫ్రీక్వెన్సీ", storage_used: "ఉపయోగించిన నిల్వ", clear_cache: "కాష్ క్లియర్ చేయండి", cleared: "క్లియర్ చేయబడింది!", device_management: "పరికర నిర్వహణ", this_device: "ఈ పరికరం", active: "క్రియాశీల", last_sync: "చివరి సమకాలీకరణ", minutes_ago: "నిమిషాల క్రితం", sync_now: "ఇప్పుడే సమకాలీకరించండి", synced: "సమకాలీకరించబడింది!", other_devices: "ఇతర పరికరాలు", tablet: "టాబ్లెట్", desktop: "డెస్క్‌టాప్", manage_devices: "పరికరాలను నిర్వహించండి", light: "కాంతి", dark: "చీకటి", system: "సిస్టమ్", push: "పుష్", email: "ఇమెయిల్", sound: "ధ్వని", whisper: "విస్పర్",
    accept: "అంగీకరించండి",
    dismiss: "నిరాకరించండి",
    view: "వీక్షించండి",
    alert: "అలర్ట్",
    priority: "ప్రాధాన్యత",
    status: "స్థితి",
    alerts: "అలర్ట్స్",
    alert_feed: "అలర్ట్ ఫీడ్",
    all_alerts: "అన్ని అలర్ట్స్",
    new_alerts: "కొత్త అలర్ట్స్",
    pending: "పెండింగ్",
    resolved: "పరిష్కరించబడింది",
    total_alerts: "మొత్తం అలర్ట్స్",
    alerts_by_type: "రకం ఆధారంగా అలర్ట్స్",
    recent_activity: "ఇటీవలి కార్యాచరణ",
    crime_heatmap: "క్రైమ్ హీట్‌మ్యాప్",
    whisper_alert: "విస్పర్ అలర్ట్",
    fir_match: "FIR సరిపోలిక",
    cross_district: "క్రాస్-డిస్ట్రిక్ట్",
    evidence_link: "ఆధారాల లింక్",
    ai_notification: "AI నోటిఫికేషన్",
    intelligence_alerts: "ఇంటెలిజెన్స్ అలర్ట్స్",
    monitor_intel: "క్రియాశీల ఇంటెలిజెన్స్‌ను పర్యవేక్షించండి మరియు స్పందించండి",
    performance_summary: "అలర్ట్ పనితీరు సారాంశం",
    pending_review: "సమీక్ష పెండింగ్",
    alert_trend: "అలర్ట్ ట్రెండ్",
    alert_distribution: "అలర్ట్ పంపిణీ",
    total: "మొత్తం",
    recent_alerts: "ఇటీవలి అలర్ట్స్",
    more_details: "మరిన్ని వివరాలు",
    // Analytics & Charts Translation
    crime_breakdown: "నేర రకం విభజన",
    cases_label: "కేసులు",
    cases_by_crime_type: "నేర రకం ఆధారంగా కేసులు",
    todays_cases: "నేటి కేసులు",
    live: "లైవ్",
    total_cases: "మొత్తం కేసులు",
    theft: "దొంగతనం",
    fraud: "మోసం",
    cybercrime: "సైబర్ నేరం",
    assault: "దాడి",
    other: "ఇతర",
    top_districts: "అగ్ర జిల్లాలు",
    by_case_count: "కేసుల సంఖ్య ఆధారంగా",
    case_resolution: "కేసు పరిష్కారం",
    by_time_period: "సమయ వ్యవధి ఆధారంగా",
    total_resolved: "మొత్తం పరిష్కరించబడింది",
    avg_resolution: "సగటు పరిష్కారం",
    case_trend: "కేసు ట్రెండ్",
    time_interval: "సమయ వ్యవధి:",
    weekly: "వారానికి ఒకసారి",
    monthly: "నెలవారీ",
    yearly: "వార్షిక",
    vs_30_days: "గత 30 రోజులతో పోలిస్తే",
    cases_by_district: "జిల్లా వారీగా కేసులు",
    investigation_calendar: "విచారణ క్యాలెండర్",
    hearings: "విచారణలు",
    shifts: "షిఫ్ట్‌లు",
    cases_by_status: "స్థితి ఆధారంగా కేసులు",
    active: "క్రియాశీల",
    under_investigation: "విచారణలో ఉంది",
    closed: "మూసివేయబడింది",
    // Calendar Events
    court_hearing: "కోర్టు విచారణ — FIR #4489",
    bail_review: "బెయిల్ సమీక్ష — కేసు #4512",
    shift_handover: "షిఫ్ట్ అప్పగింత — ఉదయం",
    night_patrol: "నైట్ పెట్రోల్ బ్రీఫింగ్",
    // Districts
    bengaluru_urban: "బెంగళూరు అర్బన్",
    bengaluru_rural: "బెంగళూరు రూరల్",
    mysuru: "మైసూర్",
    mangalaru: "మంగళూరు",
    hubballi: "హుబ్లీ",
    // Days/Periods
    days_label: "రోజులు",
    "0-30 days": "0-30 రోజులు",
    "31-60 days": "31-60 రోజులు",
    "61-90 days": "61-90 రోజులు",
    "91-180 days": "91-180 రోజులు",
    "180+ days": "180+ రోజులు",
    Sun: "ఆది",
    Mon: "సోమ",
    Tue: "మంగళ",
    Wed: "బుధ",
    Thu: "గురు",
    Fri: "శుక్ర",
    Sat: "శని",

    // --- NEW COPILOT TRANSLATIONS ---
    analyzing: "విశ్లేషిస్తోంది...",
    ai_copilot: "AI కోపైలట్",
    hi_there: "హలో 👋",
    ask_copilot: "కేసులు, అనుమానితులు లేదా విచారణల గురించి నన్ను ఏదైనా అడగండి.",
    chat_history: "చాట్ చరిత్ర",
    new_chat: "కొత్త చాట్",
    saved: "సేవ్ చేయబడింది",
    today: "నేడు",
    yesterday: "నిన్న",
    ask_anything_placeholder: "నన్ను ఏదైనా అడగండి...",
    all_sources: "అన్ని మూలాధారాలు",
    fir_database: "FIR డేటాబేస్",
    suspects: "అnuమానితులు",
    evidence: "ఆధారాలు",
    stations: "స్టేషన్లు",
    context: "సందర్భం",
    referenced_sources: "సూచించిన మూలాధారాలు",
    actions: "చర్యలు",
    related_cases: "సంబంధిత కేసులు",
    generate_report: "నివేదికను రూపొందించు",
    export_conversation: "సంభాషణను ఎగుమతి చేయి",
    save_to_case: "కేసుకు సేవ్ చేయి",
    share_with_team: "బృందంతో పంచుకోండి",
    robbery_indiranagar: "దోపిడీ — ఇందిరానగర్",
    theft_koramangala: "దొంగతనం — కోరమంగళ",
    cyber_fraud_ecity: "సైబర్ మోసం — ఎలక్ట్రానిక్ సిటీ",
    copilot_assistant_desc: "మీ AI విచారణ సహాయకుడు — కర్ణాటక పోలీసు ప్రోటోకాల్‌లు, నేర డేటాబేస్‌లు మరియు చట్టపరమైన ఫ్రేమ్‌వర్క్‌లపై శిక్షణ పొందారు.",
    quick_tasks: "శీఘ్ర పనులు",
    suggested_prompt: "సూచించిన ప్రాంప్ట్",
    task_analyze_connections: "అనుమానితుల కనెక్షన్లను విశ్లేషించు",
    task_generate_report: "విచారణ నివేదికను రూపొందించు",
    task_search_cross_district: "క్రాస్-డిస్ట్రిక్ట్ కేసులను శోధించు",
    suggested_prompt_text: "ఈ నెల బెంగళూరు జిల్లా వ్యాప్తంగా దొంగతనం కేసుల్లో సాధారణ MO నమూనాలు ఏమిటి?",
    theft_malleshwaram: "దొంగతనం — మల్లేశ్వరం, బెంగళూరు",
    suspect_linked_3_cases: "3 ఓపెన్ కేసులతో ముడిపడి ఉంది",
    cctv_footage_main_road: "CCTV ఫుటేజ్ — మెయిన్ రోడ్",
    captured_at_215_am: "ఉదయం 2:15 గంటలకు రికార్ड చేయబడింది",
    malleshwaram_bengaluru: "మల్లేశ్వరం, బెంగళూరు",
    crime_hotspot_zone: "క్రైమ్ హాట్‌స్పాట్ జోన్",

    // --- NEW GRAPH TRANSLATIONS ---
    all_connections: "అన్ని కనెక్షన్లు",
    criminal_network: "నేర నెట్‌వర్క్",
    gang_network: "గ్యాంగ్ నెట్‌వర్క్",
    evidence_links: "ఆధారాల లింకులు",
    select_node: "ఒక నోడ్ ఎంచుకోండి",
    click_node_desc: "వివరాలను వీక్షించడానికి గ్రాఫ్‌లోని ఏదైనా నోడ్‌పై క్లిక్ చేయండి",
    risk: "ప్రమాదం",
    cases: "కేసులు",
    connections: "కనెక్షన్లు",
    view_full_profile: "పూర్తి ప్రొఫైల్ వీక్షించండి",
    add_to_investigation: "విచారణకు జోడించండి",
    // Graph Suspects
    ravi_kumar: "రవి కుమార్",
    deepak_reddy: "దీపక్ రెడ్డి",
    mohammed_ali: "మహమ్మద్ అలీ",
    imran_khan: "ఇమ్రాన్ ఖాన్",
    venkatesh_reddy: "వెంకటేష్ రెడ్డి",
    rajesh_sharma: "రాజేష్ శర్మ",
    // Graph Evidence/Node type labels
    cctv_4521: "CCTV #4521",
    phone_records: "ఫోన్ రికార్డులు",
    fingerprint: "వేలిముద్ర",
    suspect: "అనుమానితుడు",
    vehicle: "వాహనం",
    phone: "ఫోన్",
    // Graph Edges
    accomplice: "సహచరుడు",
    fence: "ఫెన్స్",
    operational_head: "కార్యాచరణ అధిపతి",
    training: "శిక్షణ",
    logistics: "లాజిస్టిక్స్",
    cyber_ops: "సైబర్ ఆప్స్",
    parts_dealer: "విడిభాగాల డీలర్",
    identified: "గుర్తించబడింది",
    cell_tower: "సెల్ టవర్",
    partial_print: "పాక్షిక వేలిముద్ర",
    registered: "నమోదైంది",
    used_in_crime: "నేరంలో ఉపయోగించబడింది",
    primary: "ప్రాథమిక",
    burner: "బర్నర్",
    shared: "భాగస్వామ్యం చేయబడింది",

    // Chat History Titles
    fir_analysis_title: "FIR #4521 విశ్లేషణ",
    suspect_network_title: "అనుమానితుల నెట్‌వర్క్ — రవి కుమార్",
    mo_pattern_title: "MO పద్ధతి పరిశోధన",
    cross_district_title: "క్రాస్-డిస్ట్రిక్ట్ కేసు లింకింగ్",
    theft_pattern_title: "బెంగళూరు నార్త్ దొంగతనం నమూనా",
    whisper_investigation_title: "విస్పర్ అలర్ట్ విచారణ",
    evidence_report_title: "సాక్ష్యాల నివేదిక రూపకల్పన",

    // --- MAP & GEOGRAPHIC TRANSLATIONS ---
    geo_intelligence: "జియో ఇంటెలిజెన్స్",
    risk_level: "ప్రమాద స్థాయి",
    click_district_desc: "వివరాలను చూడటానికి మ్యాప్‌లోని ఏదైనా జిల్లాపై క్లిక్ చేయండి",
    crime_density: "నేరాల సాంద్రత",
    recent_hotspots: "ఇటీవలి హాట్‌స్పాట్లు",
    active_routes: "క్రియాశీల మార్గాలు",
    suspect_movement: "అనుమానితుడి కదలిక",
    case_connection: "కేసు కనెక్షన్",
    districts: "జిల్లాలు",
    last_updated: "చివరిగా నవీకరించబడింది",

    // --- INVESTIGATION TRANSLATIONS ---
    search_investigations_placeholder: "విచారణలను శోధించండి...",
    add_evidence: "ఆధారాన్ని జోడించండి",
    add_note_placeholder: "విచారణ గమనికను జోడించండి...",
    add_note: "గమనికను జోడించు",
    just_now: "ఇప్పుడే",
    no_related_cases_found: "సంబంధిత కేసులు ఏవీ కనుగొనబడలేదు",
    match: "పోలిక",
    add_event: "ఈవెంట్ జోడించు",
    bookmarks: "బుక్‌మార్క్‌లు",
    bookmarked: "బుక్‌మార్క్ చేయబడింది",
    add_bookmark: "బుక్‌మార్క్ జోడించు",
    reports: "నివేదికలు",
    export_pdf: "PDF ఎగుమతి చేయి",
    print: "ప్రింట్",
    quick_actions: "శీఘ్ర చర్యలు",
    investigation_stats: "విచారణ గణాంకాలు",
    notes: "గమనికలు",
    events: "ఈవెంట్లు",
    progress: "పురోగతి",
    select_investigation: "ఒక విచారణను ఎంచుకోండి",
    choose_case_desc: "పనిని ప్రారంభించడానికి జాబితా నుండి ఒక కేసును ఎంచుకోండి",
    ai_analysis: "AI విశ్లేషణ",
    recommended_actions: "సిఫార్సు చేయబడిన చర్యలు",
    pattern_analysis: "నమూనా విశ్లేషణ",
    jul: "జూలై",
    si_karthik: "కార్తీక్",
    inspector_deepak: "ఇన్‌స్పెక్టర్ దీపక్",
    cyber_cell: "సైబర్ సెల్",
    ai_pattern_text_desc: "చారిత్రక డేటా ఆధారంగా, 48 గంటల్లో క్రాస్-డిస్ట్రిక్ట్ సమన్వయం ప్రారంభించబడినప్పుడు ఇలాంటి MO నమూనాలతో కూడిన కేసులు 73% పరిష్కార రేటును కలిగి ఉంటాయి.",
    high: "అధిక",
    medium: "మధ్యమ",
    low: "తక్కువ",
    timeline: "సమయక్రమం",
    reasoning: "విశ్లేషణ",
    related: "సంబంధిత కేసులు",
    dashboard: "డ్యాష్‌బోర్డ్",
    crime_analytics: "నేర విశ్లేషణ",
    everything_analytical: "అంతా విశ్లేషణాత్మకమైనది",
    resolution_rate: "పరిష్కార రేటు",
    copilot: "కోపైలట్",
    knowledge_graph: "నాలెడ్జ్ గ్రాఫ్",
    crime_trend: "క్రైమ్ ట్రెండ్",
    daily: "రోజువారీ",
    weekly: "వారానికోసారి",
    monthly: "నెలవారీ",
    annually: "వార్షికంగా",
    cases_filed: "నమోదైన కేసులు",
    investigation_rate: "విచారణ రేటు",
    active_firs: "క్రియాశీల FIRలు",
    officers_on_duty: "విధి నిర్వహణలో ఉన్న అధికారులు",
    vs_last_year: "గత ఏడాదితో పోలిస్తే",
    vs_last_month: "గత నెలతో పోలిస్తే",
    vs_last_week: "గత వారంతో పోలిస్తే",
    vs_last_quarter: "గత త్రైమాసికంతో పోలిస్తే",
    analytics: "అనలిటిక్స్",
    clear_all: "అన్నీ క్లియర్ చేయండి",
    saved_searches: "సేవ్ చేసిన శోధనలు",
    save_current_search: "ప్రస్తుత శోధనను సేవ్ చేయండి",
    no_saved_searches: "సేవ్ చేసిన శోధనలు లేవు",
    results: "ఫలితాలు",
    run_search: "శోధనను ప్రారంభించండి",
    delete: "తొలగించు",
    search_cases_placeholder: "కేసులు, అనుమానితులు, ఎఫ్ఐఆర్‌లు, ఆధారాల కోసం వెతకండి...",
    save_search: "శోధనను సేవ్ చేయండి",
    voice_search: "వాయిస్ సెర్చ్",
    search: "శోధన",
    recent_searches: "ఇటీవలి శోధనలు",
    search_history: "శోధన చరిత్ర",
    no_search_history: "శోధన చరిత్ర లేదు",
    no_results_found: "ఎటువంటి ఫలితాలు కనుగొనబడలేదు",
    try_adjusting_search: "మీ శోధన లేదా ఫిల్టర్‌లను సర్దుబాటు చేయడానికి ప్రయత్నించండి",
    results_found: "ఫలితాలు కనుగొనబడ్డాయి",
    case_id: "కేసు ఐడి",
    crime_type: "నేర రకం",
    district: "జిల్లా",
    open: "తెరిచి ఉంది",
    all: "అన్నీ",
    fir: "FIR",
    bengaluru: "బెంగళూరు",
    crime_search: "కేసులను శోధించండి",
    search_everything: "అంతటా వెతకండి",
    title: "శీర్షిక",
    date: "తేదీ",
    status: "స్థితి",
    actions: "చర్యలు",
    criminal_intelligence: "క్రిమినల్ ఇంటెలిజెన్స్",
    everything_about_suspects: "అనుమానితుల గురించి ప్రతిదీ",
    search_suspects_placeholder: "పేరు, ఐడి, మారుపేరు ద్వారా అనుమానితుల కోసం వెతకండి...",
    high_risk: "అధిక ప్రమాదం",
    repeat: "రిపీట్ అఫెండర్లు",
    at_large: "పరారీలో",
    under_trial: "విచారణలో",
    yrs: "సంవత్సరాలు",
    no_suspects_found: "మీ ప్రమాణాలకు సరిపోలే అనుమానితులు ఎవరూ కనుగొనబడలేదు",
    arrested: "అరెస్ట్",
    under_investigation: "దర్యాప్తులో",
    released: "విడుదల",
    bengaluru_urban: "బెంగళూరు అర్బన్",
    bengaluru_rural: "బెంగళూరు రూరల్",
    mysuru: "మైసూరు",
    hubballi: "హుబ్బళ్లి",
    mangalaru: "మంగళూరు",
    kumar_swamy: "కుమార్ స్వామి",
    suresh_patel: "సురేష్ పటేల్",
  },
  hi: {
    settings: "सेटिंग्स", personal_preferences: "व्यक्तिगत प्राथमिकताएँ", saving: "सहेजा जा रहा है...", saved: "सहेज लिया गया!", save_changes: "परिवर्तन सहेजें", profile: "प्रोफ़ाइल", edit_profile: "प्रोफ़ाइल संपादित करें", opening: "खुल रहा है...", language: "भाषा", primary_language: "प्राथमिक भाषा", secondary_language: "द्वितीयक भाषा", ui_language: "UI भाषा (ऐप)", theme: "थीम", notifications: "सूचनाएं", voice_settings: "वॉयस सेटिंग्स", voice_assistant: "वॉयस असिस्टेंट", speed: "गति", auto_transcribe: "ऑटो-ट्रांसक्राइब", offline_sync: "ऑफ़लाइन सिंक", enable_offline: "ऑफ़लाइन सक्षम करें", sync_frequency: "सिंक आवृत्ति", storage_used: "उपयोग किया गया स्टोरेज", clear_cache: "कैश साफ़ करें", cleared: "साफ़ किया गया!", device_management: "डिवाइस प्रबंधन", this_device: "यह डिवाइस", active: "सक्रिय", last_sync: "अंतिम सिंक", minutes_ago: "मिनट पहले", sync_now: "अभी सिंक करें", synced: "सिंक किया गया!", other_devices: "अन्य उपकरण", tablet: "टैबलेट", desktop: "डेस्कटॉप", manage_devices: "उपकरण प्रबंधित करें", light: "रोशनी", dark: "अंधेरा", system: "सिस्टम", push: "पुश", email: "ईमेल", sound: "ध्वनि", whisper: "विस्पर",
    accept: "स्वीकार करें",
    dismiss: "अस्वीकार",
    view: "देखें",
    alert: "अलर्ट",
    priority: "प्राथमिकता",
    status: "स्थिति",
    alerts: "अलर्ट्स",
    alert_feed: "अलर्ट फ़ीड",
    all_alerts: "सभी अलर्ट्स",
    new_alerts: "नए अलर्ट्स",
    pending: "लंबित",
    resolved: "हल किया गया",
    total_alerts: "कुल अलर्ट्स",
    alerts_by_type: "प्रकार के आधार पर अलर्ट्स",
    recent_activity: "हाल की गतिविधि",
    crime_heatmap: "अपराध हीटमैप",
    whisper_alert: "व्हिस्पर अलर्ट",
    fir_match: "एफआईआर मिलान",
    cross_district: "क्रॉस-डिस्ट्रिक्ट",
    evidence_link: "साक्ष्य लिंक",
    ai_notification: "एआई अधिसूचना",
    intelligence_alerts: "खुफिया अलर्ट",
    monitor_intel: "सक्रिय खुफिया जानकारी की निगरानी करें और प्रतिक्रिया दें",
    performance_summary: "अलर्ट प्रदर्शन सारांश",
    pending_review: "समीक्षा लंबित",
    alert_trend: "अलर्ट ट्रेंड",
    alert_distribution: "अलर्ट वितरण",
    total: "कुल",
    recent_alerts: "हाल के अलर्ट",
    more_details: "अधिक विवरण",
    // Analytics & Charts Translation
    crime_breakdown: "अपराध प्रकार का विवरण",
    cases_label: "मामले",
    cases_by_crime_type: "अपराध प्रकार के अनुसार मामले",
    todays_cases: "आज के मामले",
    live: "लाइव",
    total_cases: "कुल मामले",
    theft: "चोरी",
    fraud: "धोखाधड़ी",
    cybercrime: "साइबर अपराध",
    assault: "हमला",
    other: "अन्य",
    top_districts: "शीर्ष जिले",
    by_case_count: "मामलों की संख्या के अनुसार",
    case_resolution: "मामले का समाधान",
    by_time_period: "समय अवधि के अनुसार",
    total_resolved: "कुल हल किए गए",
    avg_resolution: "औसत समाधान",
    case_trend: "मामले का ट्रेंड",
    time_interval: "समय अंतराल:",
    weekly: "साप्ताहिक",
    monthly: "मासिक",
    yearly: "वार्षिक",
    vs_30_days: "पिछले 30 दिनों की तुलना में",
    cases_by_district: "जिले के अनुसार मामले",
    investigation_calendar: "जांच कैलेंडर",
    hearings: "सुनवाई",
    shifts: "पालियों",
    cases_by_status: "स्थिति के अनुसार मामले",
    active: "सक्रिय",
    under_investigation: "जांच के अधीन",
    closed: "बंद",
    // Calendar Events
    court_hearing: "कोर्ट सुनवाई — FIR #4489",
    bail_review: "जमानत समीक्षा — केस #4512",
    shift_handover: "शिफ्ट हैंडओवर — सुबह",
    night_patrol: "रात्रि गश्त ब्रीफिंग",
    // Districts
    bengaluru_urban: "बेंगलुरु शहरी",
    bengaluru_rural: "बेंगलुरु ग्रामीण",
    mysuru: "मैसूरु",
    mangalaru: "मंगलुरु",
    hubballi: "हुबली",
    // Days/Periods
    days_label: "दिन",
    "0-30 days": "0-30 दिन",
    "31-60 days": "31-60 दिन",
    "61-90 days": "61-90 दिन",
    "91-180 days": "91-180 दिन",
    "180+ days": "180+ दिन",
    Sun: "रवि",
    Mon: "सोम",
    Tue: "मंगल",
    Wed: "बुध",
    Thu: "गुरु",
    Fri: "शुक्र",
    Sat: "शनि",

    // --- NEW COPILOT TRANSLATIONS ---
    analyzing: "विश्लेषण किया जा रहा है...",
    ai_copilot: "एआई कोपायलट",
    hi_there: "नमस्ते 👋",
    ask_copilot: "मुझसे मामलों, संदिग्धों या जांच के बारे में कुछ भी पूछें।",
    chat_history: "चैट इतिहास",
    new_chat: "नया चैट",
    saved: "सहेजे गए",
    today: "आज",
    yesterday: "कल",
    ask_anything_placeholder: "मुझसे कुछ भी पूछें...",
    all_sources: "सभी स्रोत",
    fir_database: "एफआईआर डेटाबेस",
    suspects: "संदिग्ध",
    evidence: "साक्ष्य",
    stations: "थाने",
    context: "संदर्भ",
    referenced_sources: "संदर्भित स्रोत",
    actions: "कार्रवाई",
    related_cases: "संबंधित मामले",
    generate_report: "रिपोर्ट जनरेट करें",
    export_conversation: "बातचीत निर्यात करें",
    save_to_case: "केस में सहेजें",
    share_with_team: "टीम के साथ साझा करें",
    robbery_indiranagar: "डकैती — इंदिरा नगर",
    theft_koramangala: "चोरी — कोरमंगला",
    cyber_fraud_ecity: "साइबर धोखाधड़ी — इलेक्ट्रॉनिक सिटी",
    copilot_assistant_desc: "आपका एआई जांच सहायक — कर्नाटक पुलिस प्रोटोकॉल, आपराधिक डेटाबेस और कानूनी ढांचे पर प्रशिक्षित।",
    quick_tasks: "त्वरित कार्य",
    suggested_prompt: "सुझाया गया संकेत",
    task_analyze_connections: "संदिग्ध कनेक्शन का विश्लेषण करें",
    task_generate_report: "जांच रिपोर्ट जनरेट करें",
    task_search_cross_district: "क्रॉस-डिस्ट्रिक्ट मामलों की खोज करें",
    suggested_prompt_text: "इस महीने की शुरुआत में बेंगलुरु जिले में चोरी के मामलों में सामान्य एमओ पैटर्न क्या हैं?",
    theft_malleshwaram: "चोरी — मल्लेश्वरम, बेंगलुरु",
    suspect_linked_3_cases: "3 लंबित मामलों से जुड़ा हुआ है",
    cctv_footage_main_road: "सीसीटीवी फुटेज — मुख्य सड़क",
    captured_at_215_am: "सुबह 2:15 बजे कैप्चर किया गया",
    malleshwaram_bengaluru: "मल्लेश्वरम, बेंगलुरु",
    crime_hotspot_zone: "अपराध हॉटस्पॉट क्षेत्र",

    // --- NEW GRAPH TRANSLATIONS ---
    all_connections: "सभी कनेक्शन",
    criminal_network: "अपराधिक नेटवर्क",
    gang_network: "गैंग नेटवर्क",
    evidence_links: "साक्ष्य लिंक",
    select_node: "एक नोड चुनें",
    click_node_desc: "विवरण देखने के लिए ग्राफ़ में किसी भी नोड पर क्लिक करें",
    risk: "जोखिम",
    cases: "मामले",
    connections: "कनेक्शन",
    view_full_profile: "पूरा प्रोफाइल देखें",
    add_to_investigation: "जांच में जोड़ें",
    // Graph Suspects
    ravi_kumar: "रवि कुमार",
    deepak_reddy: "दीपक रेड्डी",
    mohammed_ali: "मोहम्मद अली",
    imran_khan: "इमरान खान",
    venkatesh_reddy: "वेंकटेश रेड्डी",
    rajesh_sharma: "राजेश शर्मा",
    // Graph Evidence/Node type labels
    cctv_4521: "सीसीटीवी #4521",
    phone_records: "फ़ोन रिकॉर्ड",
    fingerprint: "उंगली की छाप",
    suspect: "संदिग्ध",
    vehicle: "वाहन",
    phone: "फ़ोन",
    // Graph Edges
    accomplice: "सहयोगी",
    fence: "सौदागर (फेंस)",
    operational_head: "परिचालन प्रमुख",
    training: "प्रशिक्षण",
    logistics: "रसद (लॉजिस्टिक्स)",
    cyber_ops: "साइबर ऑप्स",
    parts_dealer: "पुर्जा विक्रेता",
    identified: "पहचाना गया",
    cell_tower: "सेल टॉवर",
    partial_print: "आंशिक छाप",
    registered: "पंजीकृत",
    used_in_crime: "अपराध में प्रयुक्त",
    primary: "प्राथमिक",
    burner: "बर्नर",
    shared: "साझा",

    // Chat History Titles
    fir_analysis_title: "एफआईआर #4521 विश्लेषण",
    suspect_network_title: "संदिग्ध नेटवर्क — रवि कुमार",
    mo_pattern_title: "कार्यप्रणाली (MO) अनुसंधान",
    cross_district_title: "क्रॉस-डिस्ट्रिक्ट केस लिंकिंग",
    theft_pattern_title: "बेंगलुरु उत्तर चोरी पैटर्न",
    whisper_investigation_title: "व्हिस्पर अलर्ट जांच",
    evidence_report_title: "साक्ष्य रिपोर्ट तैयार करना",

    // --- MAP & GEOGRAPHIC TRANSLATIONS ---
    geo_intelligence: "भू-स्थानिक खुफिया जानकारी",
    risk_level: "जोखिम का स्तर",
    click_district_desc: "विवरण देखने के लिए मानचित्र पर किसी जिले पर क्लिक करें",
    crime_density: "अपराध घनत्व",
    recent_hotspots: "हाल के हॉटस्पॉट",
    active_routes: "सक्रिय मार्ग",
    suspect_movement: "संदिग्ध की गतिविधि",
    case_connection: "केस कनेक्शन",
    districts: "जिले",
    last_updated: "अंतिम बार अपडेट किया गया",

    // --- INVESTIGATION TRANSLATIONS ---
    search_investigations_placeholder: "जांच खोजें...",
    add_evidence: "साक्ष्य जोड़ें",
    add_note_placeholder: "जांच नोट जोड़ें...",
    add_note: "नोट जोड़ें",
    just_now: "अभी-अभी",
    no_related_cases_found: "कोई संबंधित मामला नहीं मिला",
    match: "मिलान",
    add_event: "घटना जोड़ें",
    bookmarks: "बुकमार्क",
    bookmarked: "बुकमार्क किया गया",
    add_bookmark: "बुकमार्क जोड़ें",
    reports: "रिपोर्ट",
    export_pdf: "PDF निर्यात करें",
    print: "प्रिंट करें",
    quick_actions: "त्वरित कार्रवाई",
    investigation_stats: "जांच आँकड़े",
    notes: "टिप्पणियां",
    events: "घटनाएं",
    progress: "प्रगति",
    select_investigation: "एक जांच चुनें",
    choose_case_desc: "काम शुरू करने के लिए सूची से एक केस चुनें",
    ai_analysis: "एआई विश्लेषण",
    recommended_actions: "अनुशंसित कार्रवाई",
    pattern_analysis: "पैटर्न विश्लेषण",
    jul: "जुलाई",
    si_karthik: "कार्तिक",
    inspector_deepak: "इंस्पेक्टर दीपक",
    cyber_cell: "साइबर सेल",
    ai_pattern_text_desc: "ऐतिहासिक आंकड़ों के आधार पर, समान एमओ पैटर्न वाले मामलों में 73% समाधान दर होती है जब 48 घंटों के भीतर क्रॉस-डिस्ट्रिक्ट समन्वय शुरू किया जाता है।",
    high: "उच्च",
    medium: "मध्यम",
    low: "कम",
    timeline: "समयरेखा",
    reasoning: "तर्क",
    related: "संबंधित मामले",
    dashboard: "डैशबोर्ड",
    crime_analytics: "अपराध विश्लेषण",
    everything_analytical: "सब कुछ विश्लेषणात्मक",
    resolution_rate: "समाधान दर",
    copilot: "कोपायलट",
    knowledge_graph: "नॉलेज ग्राफ",
    crime_trend: "अपराध प्रवृत्ति",
    daily: "दैनिक",
    weekly: "साप्ताहिक",
    monthly: "मासिक",
    annually: "वार्षिक",
    cases_filed: "दर्ज किए गए मामले",
    investigation_rate: "जांच दर",
    active_firs: "सक्रिय एफआईआर",
    officers_on_duty: "ड्यूटी पर अधिकारी",
    vs_last_year: "पिछले वर्ष की तुलना में",
    vs_last_month: "पिछले महीने की तुलना में",
    vs_last_week: "पिछले सप्ताह की तुलना में",
    vs_last_quarter: "पिछली तिमाही की तुलना में",
    analytics: "विश्लेषण",
    clear_all: "सभी साफ़ करें",
    saved_searches: "सहेजी गई खोजें",
    save_current_search: "वर्तमान खोज सहेजें",
    no_saved_searches: "कोई सहेजी गई खोज नहीं",
    results: "परिणाम",
    run_search: "खोजें",
    delete: "हटाएं",
    search_cases_placeholder: "मामले, संदिग्ध, एफआईआर, साक्ष्य खोजें...",
    save_search: "खोज सहेजें",
    voice_search: "वॉयस सर्च",
    search: "खोज",
    recent_searches: "हाल की खोजें",
    search_history: "खोज इतिहास",
    no_search_history: "कोई खोज इतिहास नहीं",
    no_results_found: "कोई परिणाम नहीं मिला",
    try_adjusting_search: "अपनी खोज या फ़िल्टर को समायोजित करने का प्रयास करें",
    results_found: "परिणाम मिले",
    case_id: "केस आईडी",
    crime_type: "अपराध का प्रकार",
    district: "जिला",
    open: "खुला",
    all: "सभी",
    fir: "एफआईआर",
    bengaluru: "बेंगलुरु",
    crime_search: "मामले खोजें",
    search_everything: "सब कुछ खोजें",
    title: "शीर्षक",
    date: "दिनांक",
    status: "स्थिति",
    actions: "कार्रवाई",
    criminal_intelligence: "आपराधिक खुफिया",
    everything_about_suspects: "संदिग्धों के बारे में सब कुछ",
    search_suspects_placeholder: "नाम, आईडी, उपनाम से संदिग्धों को खोजें...",
    high_risk: "उच्च जोखिम",
    repeat: "आदतन अपराधी",
    at_large: "फरार",
    under_trial: "विचाराधीन",
    yrs: "वर्ष",
    no_suspects_found: "आपके मानदंडों से मेल खाने वाले कोई संदिग्ध नहीं मिले",
    arrested: "गिरफ्तार",
    under_investigation: "जांच के अधीन",
    released: "रिहा",
    bengaluru_urban: "बेंगलुरु शहरी",
    bengaluru_rural: "बेंगलुरु ग्रामीण",
    mysuru: "मैसूरु",
    hubballi: "हुबली",
    mangalaru: "मंगलुरु",
    kumar_swamy: "कुमार स्वामी",
    suresh_patel: "सुरेश पटेल",
  },
};

// --- MOCK DATA TRANSLATION SYSTEM ---

const rawTranslations = {
  // Case Titles & Types
  "Theft at Malleshwaram residence": {
    ta: "மல்லேஸ்வரம் குடியிருப்பில் திருட்டு",
    kn: "ಮಲ್ಲೇಶ್ವರಂ ನಿವಾಸದಲ್ಲಿ ಕಳ್ಳತನ",
    te: "మల్లేశ్వరం నివాసంలో దొంగతనం",
    hi: "मल्लेश्वरम आवास पर चोरी",
  },
  "Cyber fraud — Electronic City": {
    ta: "சைபர் மோசடி — எலக்ட்ரானிக் சிட்டி",
    kn: "ಸೈಬರ್ ವಂಚನೆ — ಎಲೆಕ್ಟ್ರಾನಿಕ್ ಸಿಟಿ",
    te: "సైబర్ మోసం — ఎలక్ట్రానిక్ సిటీ",
    hi: "साइबर धोखाधड़ी — इलेक्ट्रॉनिक सिटी",
  },
  "Missing person — Koramangala": {
    ta: "காணாமல் போன நபர் — கோரமங்களா",
    kn: "ಕಾಣೆಯಾದ ವ್ಯಕ್ತಿ — ಕೋರಮಂಗಲ",
    te: "తప్పిపోయిన వ్యక్తి — కోరమంగళ",
    hi: "लापता व्यक्ति — कोरमंगला",
  },
  "Robbery — Indiranagar": {
    ta: "கொள்ளை — இந்திராநகர்",
    kn: "ದರೋಡೆ — ಇಂದಿರಾನಗರ",
    te: "దోపిడీ — ఇందిరానగర్",
    hi: "डकैती — इंदिरा नगर",
  },
  "Missing juvenile — Hebbal": {
    ta: "காணாமல் போன சிறுவன் — ಹೆಬ್ಬಾಳ",
    kn: "ಕಾಣೆಯಾದ ಅಪ್ರಾಪ್ತ ವಯಸ್ಕ — ಹೆಬ್ಬಾಳ",
    te: "తప్పిపోయిన మైనర్ — హెబ్బాల్",
    hi: "लापता किशोर — हेब्बाल",
  },
  "Theft — Rajajinagar": {
    ta: "திருட்டு — ராஜாஜிநகர்",
    kn: "ಕಳ್ಳತನ — ರಾಜಾಜಿನಗರ",
    te: "దొಂಗతనం — రాజాజీనగర్",
    hi: "चोरी — राजाजीनगर",
  },
  "Theft — Malleshwaram 5th Block": {
    ta: "திருட்டு — மல்லேஸ்வரம் 5வது பிளாக்",
    kn: "ಕಳ್ಳತನ — ಮಲ್ಲೇಶ್ವರಂ 5 ನೇ ಬ್ಲಾಕ್",
    te: "దొంగతనం — మల్లేశ్వరం 5వ బ్లాక్",
    hi: "चोरी — मल्लेश्वरम 5वां ब्लॉक",
  },
  "Cybercrime — phishing attack": {
    ta: "சைபர் குற்றம் — ஃபிஷிங் தாக்குதல்",
    kn: "ಸೈಬರ್ ಅಪರಾಧ — ಫಿಶಿಂಗ್ ದಾಳಿ",
    te: "సైబర్ క్రైమ్ — ఫిషింగ్ దాడి",
    hi: "साइबर अपराध — फ़िशिंग हमला",
  },
  "Fraud — online payment scam": {
    ta: "மோசடி — ஆன்லைன் கட்டண மோசடி",
    kn: "ವಂಚನೆ — ಆನ್‌ಲೈನ್ ಪಾವತಿ ಹಗರಣ",
    te: "మోసం — ఆన్‌లైన్ చెల్లింపు కుంభకోణం",
    hi: "धोखाधड़ी — ऑनलाइन भुगतान घोटाला",
  },
  "Theft at Malleshwaram": {
    ta: "மல்லேஸ்வரத்தில் திருட்டு",
    kn: "ಮಲ್ಲೇಶ್ವರಂನಲ್ಲಿ ಕಳ್ಳತನ",
    te: "మల్లేశ్వరంలో దొంగతనం",
    hi: "मल्लेश्वरम में चोरी",
  },

  // Connection text
  "MO Match": { ta: "MO பொருத்தம்", kn: "ಎಂ.ಓ ಹೊಂದಾಣಿಕೆ", te: "MO పోలిక", hi: "एमओ मिलान" },
  "Location": { ta: "இடம்", kn: "ಸ್ಥಳ", te: "ప్రదేశం", hi: "स्थान" },
  "Suspect Link": { ta: "சந்தேக நபர் இணைப்பு", kn: "ಶಂಕಿತರ ಸಂಪರ್ಕ", te: "అనుమానితుడి లింక్", hi: "संदिग्ध लिंक" },
  "Pattern Match": { ta: "பாணி பொருத்தம்", kn: "ವಿನ್ಯಾಸದ ಹೊಂದಾಣಿಕೆ", te: "నమూనా పోలిక", hi: "पैटर्न मिलान" },
  "Technique": { ta: "தொழில்நுட்பம்", kn: "ತಂತ್ರ", te: "సాంకేతికత", hi: "तकनीक" },

  // Notes
  "Initial scene investigation complete. No fingerprints found on primary entry point.": {
    ta: "ஆரம்பக் கட்ட விசாரணை முடிந்தது. முதன்மை நுழைவுப் பகுதியில் கைரேகைகள் எதுவும் கிடைக்கவில்லை.",
    kn: "ಪ್ರಾಥಮಿಕ ದೃಶ್ಯ ತನಿಖೆ ಪೂರ್ಣಗೊಂಡಿದೆ. ಮುಖ್ಯ ಪ್ರವೇಶ ದ್ವಾರದಲ್ಲಿ ಯಾವುದೇ ಬೆರಳಚ್ಚುಗಳು ಕಂಡುಬಂದಿಲ್ಲ.",
    te: "ప్రాథమిక ఘటనా స్థల విచారణ పూర్తయింది. ప్రధాన ప్రవేశ ద్వారం వద్ద వేలిముద్రలు లభించలేదు.",
    hi: "प्रारंभिक दृश्य जांच पूरी हुई। प्राथमिक प्रवेश बिंदु पर कोई उंगलियों के निशान नहीं मिले।"
  },
  "CCTV footage from neighbor shows suspect at 2:15 AM wearing dark jacket.": {
    ta: "அண்டை வீட்டுக்காரரின் சிசிடிவி காட்சிகள் அதிகாலை 2:15 மணிக்கு சந்தேக நபர் இருண்ட ஜாக்கெட் அணிந்திருந்ததைக் காட்டுகிறது.",
    kn: "ನೆರೆಹೊರೆಯವರ ಸಿಸಿಟಿವಿ ದೃಶ್ಯಾವಳಿಯು ಮುಂಜಾನೆ 2:15 ಕ್ಕೆ ಶಂಕಿತ ವ್ಯಕ್ತಿ ಕಪ್ಪು ಜಾಕೆಟ್ ಧರಿಸಿರುವುದನ್ನು ತೋರಿಸುತ್ತದೆ.",
    te: "పొరుగువారి సిసిటివి ఫుటేజ్ తెల్లవారుజామున 2:15 గంటలకు అనుమానితుడు డార్క్ జాకెట్ ధరించినట్లు చూపుతోంది.",
    hi: "पड़ोसी के सीसीटीवी फुटेज में संदिग्ध सुबह 2:15 बजे गहरे रंग की जैकेट पहने नजर आ रहा है।"
  },
  "Suspect identified as Ravi Kumar, known repeat offender. Previous cases: FIR #4201, FIR #4356.": {
    ta: "சந்தேக நபர் ரவி குமார் என அடையாளம் காணப்பட்டுள்ளார். முந்தைய வழக்குகள்: எஃப்ஐஆர் #4201, எஃப்ஐஆர் #4356.",
    kn: "ಶಂಕಿತನನ್ನು ರವಿ ಕುಮಾರ್ ಎಂದು ಗುರುತಿಸಲಾಗಿದೆ, ಇವರು ಹಳೆಯ ಅಪರಾಧಿ. ಹಿಂದಿನ ಪ್ರಕರಣಗಳು: FIR #4201, FIR #4356.",
    te: "అనుమానితుడు రవికుమార్‌గా గుర్తించబడ్డాడు, ఇతడు పాత నేరస్థుడు. మునుపటి కేసులు: FIR #4201, FIR #4356.",
    hi: "संदिग्ध की पहचान रवि कुमार के रूप में हुई है, जो आदतन अपराधी है। पिछले मामले: प्राथमिकी #4201, प्राथमिकी #4356।"
  },
  "Multiple victims reported unauthorized transactions after phishing emails.": {
    ta: "ஃபிஷிங் மின்னஞ்சல்களுக்குப் பிறகு அங்கீகரிக்கப்படாத பரிவர்த்தனைகள் நடந்ததாகப் பல பாதிக்கப்பட்டவர்கள் தெரிவித்தனர்.",
    kn: "ಫಿಶಿಂಗ್ ಇಮೇಲ್‌ಗಳ ನಂತರ ಅನೇಕ ಬಲಿಪಶುಗಳು ಅನಧಿಕೃತ ವಹಿವಾಟುಗಳನ್ನು ವರದಿ ಮಾಡಿದ್ದಾರೆ.",
    te: "ఫిషింగ్ ఇమెయిల్‌ల తర్వాత అనధికారిక లావాదేవీలు జరిగినట్లు పలువురు బాధితులు నివేదించారు.",
    hi: "फ़िशिंग ईमेल के बाद कई पीड़ितों ने अनधिकृत लेनदेन की सूचना दी।"
  },
  "Phishing email template matches known threat actor group \"CyberShadow\".": {
    ta: "ஃபிஷிங் மின்னஞ்சல் வார்ப்புரு அறியப்பட்ட அச்சுறுத்தல் குழுவான \"சைபர்ஷேடோ\" உடன் பொருந்துகிறது.",
    kn: "ಫಿಶಿಂಗ್ ಇಮೇಲ್ ಟೆಂಪ್ಲೇಟ್ ತಿಳಿದಿರುವ ಬೆದರಿಕೆ ಗುಂಪು \"CyberShadow\" ಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ.",
    te: "ఫిషింగ్ ఇమెయిల్ టెంప్లేట్ తెలిసిన సైబర్ ముఠా \"CyberShadow\"తో సరిపోలింది.",
    hi: "फ़िशिंग ईमेल टेम्प्लेट ज्ञात थ्रेट एक्टर ग्रुप \"साइबरशैडो\" से मेल खाता है।"
  },
  "22-year-old engineering student missing since July 12. Last seen leaving college.": {
    ta: "22 வயது பொறியியல் மாணவர் ஜூலை 12 முதல் காணவில்லை. கடைசியாக கல்லூரியிலிருந்து வெளியேறும் போது பார்க்கப்பட்டார்.",
    kn: "22 ವರ್ಷದ ಎಂಜಿನಿಯರಿಂಗ್ ವಿದ್ಯಾರ್ಥಿ ಜುಲೈ 12 ರಿಂದ ಕಾಣೆಯಾಗಿದ್ದಾರೆ. ಕೊನೆಯದಾಗಿ ಕಾಲೇಜು ಬಿಟ್ಟು ಹೋಗುವಾಗ ಕಂಡುಬಂದಿದ್ದಾರೆ.",
    te: "22 ఏళ్ల ఇంజనీరింగ్ విద్యార్థి జూలై 12 నుంచి కనిపించడం లేదు. చివరిసారిగా కాలేజీ నుంచి వెళ్తూ కనిపించాడు.",
    hi: "22 वर्षीय इंजीनियरिंग छात्र 12 जुलाई से लापता है। आखिरी बार कॉलेज से निकलते हुए देखा गया था।"
  },
  "Phone switched off since 4:45 PM on Jul 12. Last ping near MG Road.": {
    ta: "ஜூலை 12 மாலை 4:45 மணி முதல் தொலைபேசி அணைக்கப்பட்டுள்ளது. கடைசியாக எம்ஜி சாலை அருகில் சிக்னல் காட்டியது.",
    kn: "ಜುಲೈ 12 ರ ಸಂಜೆ 4:45 ರಿಂದ ಫೋನ್ ಸ್ವಿಚ್ ಆಫ್ ಆಗಿದೆ. ಕೊನೆಯ ಲೊಕೇಶನ್ ಎಂಜಿ ರಸ್ತೆ ಬಳಿ ಇತ್ತು.",
    te: "జూలై 12 సాయంత్రం 4:45 గంటల నుంచి ఫోన్ స్విచ్ ఆఫ్ చేయబడింది. చివరి లొకేషన్ ఎంజీ రోడ్ సమీపంలో ఉంది.",
    hi: "12 जुलाई को शाम 4:45 बजे से फोन बंद है। आखिरी बार एमजी रोड के पास पिंग हुआ था।"
  },
  "Two suspects on motorcycle threatened restaurant staff.": {
    ta: "மோட்டார் சைக்கிளில் வந்த இரு சந்தேக நபர்கள் உணவக ஊழியர்களை மிரட்டினர்.",
    kn: "ಮೋಟಾರ್ ಸೈಕಲ್‌ನಲ್ಲಿ ಬಂದ ಇಬ್ಬರು ಶಂಕಿತರು ರೆಸ್ಟೋರೆಂಟ್ ಸಿಬ್ಬಂದಿಗೆ ಬೆದರಿಕೆ ಹಾಕಿದ್ದಾರೆ.",
    te: "మోటార్ సైకిల్‌పై వచ్చిన ఇద్దరు అనుమానితులు రెస్టారెంట్ సిబ్బందిని బెదిరించారు.",
    hi: "मोटरसाइकिल पर सवार दो संदिग्धों ने रेस्तरां कर्मचारियों को धमकाया।"
  },
  "16-year-old student missing. Left a note mentioning personal issues.": {
    ta: "16 வயது மாணவன் காணவில்லை. தனிப்பட்ட பிரச்சனைகளைக் குறிப்பிட்டு கடிதம் ஒன்றை எழுதியுள்ளார்.",
    kn: "16 ವರ್ಷದ ವಿದ್ಯಾರ್ಥಿ ಕಾಣೆಯಾಗಿದ್ದಾರೆ. ವೈಯಕ್ತಿಕ ಸಮಸ್ಯೆಗಳನ್ನು ಉಲ್ಲೇಖಿಸಿ ಟಿಪ್ಪಣಿ ಬರೆದಿದ್ದಾರೆ.",
    te: "16 ఏళ్ల విద్యార్థి కనిపించడం లేదు. వ్యక్తిగత సమస్యలను ప్రస్తావిస్తూ ఒక లేఖ రాశాడు.",
    hi: "16 वर्षीय छात्र लापता। व्यक्तिगत समस्याओं का उल्लेख करते हुए एक नोट छोड़ा।"
  },

  // Evidence descriptions
  "Neighbor camera footage showing suspect at 2:15 AM": {
    ta: "அதிகாலை 2:15 மணிக்கு சந்தேக நபரை காட்டும் அண்டை வீட்டு கேமரா காட்சிகள்",
    kn: "ಮುಂಜಾನೆ 2:15 ಕ್ಕೆ ಶಂಕಿತನನ್ನು ತೋರಿಸುವ ನೆರೆಹೊರೆಯವರ ಕ್ಯಾಮೆರಾ ದೃಶ್ಯಾವಳಿ",
    te: "తెల్లవారుజామున 2:15 గంటలకు అనుమానితుడిని చూపిస్తున్న పొరుగువారి కెమెరా ఫుటేజ్",
    hi: "पड़ोसी के कैमरे का फुटेज जिसमें संदिग्ध सुबह 2:15 बजे दिख रहा है"
  },
  "Cell tower data showing suspect near scene": {
    ta: "குற்றம் நடந்த இடத்தின் அருகே சந்தேக நபர் இருந்ததை காட்டும் செல் கோபுர தரவு",
    kn: "ಘಟನಾ ಸ್ಥಳದ ಬಳಿ ಶಂಕಿತನಿದ್ದ ಸೆಲ್ ಟವರ್ ಮಾಹಿತಿ",
    te: "ఘటనా స్థలానికి సమీపంలో అనుమానితుడు ఉన్నట్లు చూపిస్తున్న సెల్ టవర్ డేటా",
    hi: "सेल टॉवर डेटा संदिग्ध को घटना स्थल के पास दिखा रहा है"
  },
  "Partial print on rear door handle": {
    ta: "பின்புற கதவு கைப்பிடியில் பகுதி கைரேகை",
    kn: "ಹಿಂಭಾಗದ ಬಾಗಿಲಿನ ಹ್ಯಾಂಡಲ್‌ನಲ್ಲಿ ಅರೆ ಬೆರಳಚ್ಚು",
    te: "వెనుక తలుపు హ్యాండిల్‌పై పాక్షిక వేలిముద్ర",
    hi: "पीछे के दरवाजे के हैंडल पर आंशिक छाप"
  },
  "Neighbor heard dog barking at 2:30 AM": {
    ta: "அதிகாலை 2:30 மணிக்கு நாய் குரைக்கும் சத்தம் கேட்டதாக அண்டை வீட்டார் தெரிவித்தனர்",
    kn: "ಮುಂಜಾನೆ 2:30 ಕ್ಕೆ ನಾಯಿ ಬೊಗಳುವುದನ್ನು ನೆರೆಹೊರೆಯವರು ಕೇಳಿದ್ದಾರೆ",
    te: "తెల్లవారుజామున 2:30 గంటలకు కుక్క మొరగడం పొరుగువారు విన్నారు",
    hi: "पड़ोसी ने सुबह 2:30 बजे कुत्ते के भौंकने की आवाज सुनी"
  },
  "Phishing email headers and content": {
    ta: "ஃபிஷிங் மின்னஞ்சல் தலைப்புகள் மற்றும் உள்ளடக்கம்",
    kn: "ಫಿಶಿಂಗ್ ಇಮೇಲ್ ಹೆಡರ್‌ಗಳು ಮತ್ತು ವಿಷಯ",
    te: "ఫిషింగ్ ఇమెయిల్ హెడర్‌లు మరియు కంటెంట్",
    hi: "फ़िशिंग ईमेल हेडर और सामग्री"
  },
  "Transaction records from 4 victim accounts": {
    ta: "பாதிக்கப்பட்ட 4 கணக்குகளின் பரிவர்த்தனை பதிவுகள்",
    kn: "ಬಲಿಪಶುಗಳ 4 ಬ್ಯಾಂಕ್ ಖಾತೆಗಳ ವಹಿವಾಟು ದಾಖಲೆಗಳು",
    te: "4 బాధితుల ఖాతాల నుండి లావాదేవీల రికార్డులు",
    hi: "4 पीड़ित खातों के लेनदेन रिकॉर्ड"
  },
  "VPN endpoint traced to Singapore": {
    ta: "VPN இறுதிப்புள்ளி சிங்கப்பூரில் கண்டறியப்பட்டது",
    kn: "VPN ಸ್ಥಳ ಸಿಂಗಾಪುರಕ್ಕೆ ಪತ್ತೆಯಾಗಿದೆ",
    te: "VPN ముగింపు స్థానం సింగపూర్‌కు ట్రేస్ చేయబడింది",
    hi: "वीपीएन एंडपॉइंट का पता सिंगापुर में चला"
  },
  "Campus exit footage at 4:32 PM": {
    ta: "மாலை 4:32 மணிக்கு வளாகத்திலிருந்து வெளியேறும் காட்சிகள்",
    kn: "ಸಂಜೆ 4:32 ಕ್ಕೆ ಕ್ಯಾಂಪಸ್ ನಿರ್ಗಮನ ದೃಶ್ಯಾವಳಿ",
    te: "సాయంత్రం 4:32 గంటలకు క్యాంపస్ నిష్క్రమణ ఫుటేజ్",
    hi: "शाम 4:32 बजे परिसर से बाहर निकलने का फुटेज"
  },
  "Last cell tower ping at 4:45 PM, MG Road area": {
    ta: "மாலை 4:45 மணிக்கு கடைசி செல் கோபுர சிக்னல், எம்ஜி சாலை பகுதி",
    kn: "ಸಂಜೆ 4:45 ಕ್ಕೆ ಕೊನೆಯ ಸೆಲ್ ಟವರ್ ಸಿಗ್ನಲ್, ಎಂಜಿ ರಸ್ತೆ ಪ್ರದೇಶ",
    te: "సాయంత్రం 4:45 గంటలకు చివరి సెల్ టవర్ పింగ్, ఎంజీ రోడ్ ప్రాంతం",
    hi: "शाम 4:45 बजे आखिरी सेल टॉवर पिंग, एमजी रोड क्षेत्र"
  },
  "Restaurant entrance footage": {
    ta: "உணவக நுழைவாயில் காட்சிகள்",
    kn: "ರೆಸ್ಟೋರೆಂಟ್ ಪ್ರವೇಶ ದ್ವಾರದ ದೃಶ್ಯಾವಳಿ",
    te: "రెస్టారెంట్ ప్రవేశ ద్వారం ఫుటేజ్",
    hi: "रेस्तरां प्रवेश द्वार का फुटेज"
  },
  "Partial plate number: KA-01-AB-****": {
    ta: "பகுதி எண் பலகை: KA-01-AB-****",
    kn: "ಅರೆ ನೋಂದಣಿ ಸಂಖ್ಯೆ: KA-01-AB-****",
    te: "పాక్షిక ప్లేట్ సంఖ్య: KA-01-AB-****",
    hi: "आंशिक प्लेट नंबर: KA-01-AB-****"
  },
  "Handwritten note found at home": {
    ta: "வீட்டில் கண்டெடுக்கப்பட்ட கையால் எழுதப்பட்ட குறிப்பு",
    kn: "ಮನೆಯಲ್ಲಿ ಪತ್ತೆಯಾದ ಕೈಬರಹದ ಟಿಪ್ಪಣಿ",
    te: "ఇంట్లో దొరికిన చేతిరాత లేఖ",
    hi: "घर पर मिला हस्तलिखित नोट"
  },
  "Social media activity analysis": {
    ta: "சமூக ஊடக செயல்பாட்டு பகுப்பாய்வு",
    kn: "ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮ ಚಟುವಟಿಕೆ ವಿಶ್ಲೇಷಣೆ",
    te: "సోషల్ మీడియా కార్యాచరణ విశ్ಲೇషణ",
    hi: "सोशल मीडिया गतिविधि विश्लेषण"
  },

  // Timeline events
  "FIR registered by victim": { ta: "பாதிக்கப்பட்டவரால் எஃப்ஐஆர் பதிவு செய்யப்பட்டது", kn: "ಬಲಿಪಶುವಿನಿಂದ ಎಫ್‌ಐಆರ್ ನೋಂದಣಿ", te: "బాధితుడు నమోదు చేసిన FIR", hi: "पीड़ित द्वारा प्राथमिकी दर्ज कराई गई" },
  "Scene investigation completed": { ta: "சம்பவ இட விசாரணை முடிந்தது", kn: "ಸ್ಥಳ ಪರಿಶೀಲನೆ ಪೂರ್ಣಗೊಂಡಿದೆ", te: "ఘటనా స్థల విచారణ పూర్తయింది", hi: "घटनास्थल की जांच पूरी हुई" },
  "CCTV footage collected from 3 neighbors": { ta: "3 அண்டை வீட்டாரிடமிருந்து சிசிடிவி காட்சிகள் சேகரிக்கப்பட்டன", kn: "3 ನೆರೆಹೊರೆಯವರಿಂದ ಸಿಸಿಟಿವಿ ದೃಶ್ಯಾವಳಿ ಸಂಗ್ರಹ", te: "3 పొరుగువారి నుండి సిసిటివి ఫుటేజ్ సేకరించబడింది", hi: "3 पड़ोसियों से सीसीटीवी फुटेज एकत्र किए गए" },
  "Suspect identified from footage — Ravi Kumar": { ta: "காட்சிகள் மூலம் சந்தேக நபர் ரவி குமார் என அடையாளம் காணப்பட்டார்", kn: "ದೃಶ್ಯಾವಳಿಗಳಿಂದ ಶಂಕಿತನ ಗುರುತು — ರವಿ ಕುಮಾರ್", te: "ఫుటేజ్ నుండి అనుమానితుడు రవికుమార్‌గా గుర్తింపు", hi: "फुटेज से संदिग्ध की पहचान हुई — रवि कुमार" },
  "Cell tower data analysis initiated": { ta: "செல் கோபுர தரவு பகுப்பாய்வு தொடங்கப்பட்டது", kn: "ಸೆಲ್ ಟವರ್ ಡೇಟಾ ವಿಶ್ಲೇಷಣೆ ಪ್ರಾರಂಭ", te: "సెల్ టవర్ డేటా విశ్ಲೇషణ ప్రారంభించబడింది", hi: "सेल टॉवर डेटा विश्लेषण शुरू किया गया" },
  "First complaint received": { ta: "முதல் புகார் பெறப்பட்டது", kn: "ಮೊದಲ ದೂರು ಸ್ವೀಕರಿಸಲಾಗಿದೆ", te: "మొదటి ఫిర్యాదు అందింది", hi: "पहली शिकायत प्राप्त हुई" },
  "3 more victims came forward": { ta: "பாதிக்கப்பட்ட மேலும் 3 பேர் புகார் அளித்தனர்", kn: "ಮತ್ತೆ 3 ಬಲಿಪಶುಗಳು ದೂರು ನೀಡಿದ್ದಾರೆ", te: "మరో 3 బాధితులు ముందుకు వచ్చారు", hi: "3 और पीड़ित सामने आए" },
  "Phishing email analysis initiated": { ta: "ஃபிஷிங் மின்னஞ்சல் பகுப்பாய்வு தொடங்கப்பட்டது", kn: "ಫಿಶಿಂಗ್ ಇಮೇಲ್ ವಿಶ್ಲೇಷಣೆ ಪ್ರಾರಂಭ", te: "ఫిషింగ్ ఇమెయిల్ విశ్లేషణ ప్రారంభించబడింది", hi: "फ़िशिंग ईमेल विश्लेषण शुरू किया गया" },
  "Bank transaction freeze requested": { ta: "வங்கி பரிவர்த்தனையை முடக்கக் கோரப்பட்டது", kn: "ಬ್ಯಾಂಕ್ ವಹಿವಾಟು ತಡೆಗೆ ವಿನಂತಿ", te: "బ్యాంక్ లావాదేవీల నిలిపివేత అభ్యర్థించబడింది", hi: "बैंक लेनदेन फ्रीज करने का अनुरोध किया गया" },
  "Missing person report filed": { ta: "காணாமல் போன நபர் புகார் பதிவு செய்யப்பட்டது", kn: "ಕಾಣೆಯಾದ ವ್ಯಕ್ತಿಯ ದೂರು ದಾಖಲು", te: "తప్పిపోయిన వ్యక్తి ఫిర్యాదు నమోదు చేయబడింది", hi: "लापता व्यक्ति की रिपोर्ट दर्ज की गई" },
  "Campus CCTV reviewed": { ta: "வளாக சிசிடிவி ஆய்வு செய்யப்பட்டது", kn: "ಕ್ಯಾಂಪಸ್ ಸಿಸಿಟಿವಿ ಪರಿಶೀಲನೆ", te: "క్యాంపస్ సిసిటివి సమీక్షించబడింది", hi: "परिसर के सीसीटीवी की समीक्षा की गई" },
  "Phone location analysis": { ta: "தொலைபேசி இருப்பிட பகுப்பாய்வு", kn: "ದೂರವಾಣಿ ಸ್ಥಳದ ವಿಶ್ಲೇಷಣೆ", te: "ఫోన్ లొకేషన్ విశ్ಲೇషణ", hi: "फोन स्थान विश्लेषण" },
  "Robbery at 10:30 PM": { ta: "இரவு 10:30 மணிக்கு கொள்ளை", kn: "ರಾತ್ರಿ 10:30 ಕ್ಕೆ ದರೋಡೆ", te: "రాత్రి 10:30 గంటలకు దోపిడీ", hi: "रात 10:30 बजे डकैती" },
  "CCTV footage collected": { ta: "சிசிடிவி காட்சிகள் சேகரிக்கப்பட்டன", kn: "ಸಿಸಿಟಿವಿ ದೃಶ್ಯಾವಳಿ ಸಂಗ್ರಹಿಸಲಾಗಿದೆ", te: "CCTV ఫుటేజ్ సేకరించబడింది", hi: "सीसीटीवी फुटेज एकत्र किए गए" },
  "Vehicle number partially identified": { ta: "வாகன எண் பகுதியாக அடையாளம் காணப்பட்டது", kn: "ವಾಹನದ ಸಂಖ್ಯೆ ಭಾಗಶಃ ಪತ್ತೆಯಾಗಿದೆ", te: "వాహన సంఖ్య పాక్షికంగా గుర్తించబడింది", hi: "वाहन नंबर आंशिक रूप से पहचाना गया" },
  "Missing report filed": { ta: "காணாமல் போன புகார் பதிவு செய்யப்பட்டது", kn: "ಕಾಣೆಯಾದ ದೂರು ದಾಖಲು", te: "మిస్సింగ్ కేసు నమోదు చేయబడింది", hi: "लापता रिपोर्ट दर्ज की गई" },
  "Social media accounts reviewed": { ta: "சமூக ஊடக கணக்குகள் ஆய்வு செய்யப்பட்டன", kn: "ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮ ಖಾತೆಗಳ ಪರಿಶೀಲನೆ", te: "సోషల్ మీడియా ఖాతాలు సమీక్షించబడ్డాయి", hi: "सोशल मीडिया खातों की समीक्षा की गई" },

  // Reasoning steps
  "Entry method: Rear door forced open with pry tool": {
    ta: "நுழைவு முறை: பின்புற கதவு நெம்புகோல் கொண்டு உடைக்கப்பட்டுள்ளது",
    kn: "ಪ್ರವೇಶ ವಿಧಾನ: ಹಿಂಭಾಗದ ಬಾಗಿಲನ್ನು ರಂಧ್ರ ಕೊರೆಯುವ ಉಪಕರಣದಿಂದ ಬಲವಂತವಾಗಿ ತೆರೆಯಲಾಗಿದೆ",
    te: "ప్రవేశ విధానం: వెనుక తలుపును ఏదైనా సాధనంతో బలవంతంగా తెరిచారు",
    hi: "प्रवेश विधि: पीछे का दरवाजा पेचकस या औजार से जबरन खोला गया"
  },
  "Timing: 2:00-4:00 AM consistent with suspect MO": {
    ta: "நேரம்: அதிகாலை 2:00-4:00 மணி சந்தேக நபரின் வழக்கமான பாணியுடன் ஒத்துப்போகிறது",
    kn: "ಸಮಯ: ಮುಂಜಾನೆ 2:00-4:00 ಶಂಕಿತನ ಅಪರಾಧ ವಿಧಾನಕ್ಕೆ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ",
    te: "సమయం: తెల్లవారుజామున 2:00-4:00 గంటలు అనుమానితుడి MO తో సరిపోలింది",
    hi: "समय: सुबह 2:00-4:00 बजे संदिग्ध के काम करने के तरीके (MO) के अनुरूप है"
  },
  "CCTV confirms suspect presence at scene": {
    ta: "சம்பவ இடத்தில் சந்தேக நபர் இருந்ததை சிசிடிவி உறுதிப்படுத்துகிறது",
    kn: "ಘಟನಾ ಸ್ಥಳದಲ್ಲಿ ಶಂಕಿತನ ಉಪಸ್ಥಿತಿಯನ್ನು ಸಿಸಿಟಿವಿ ಖಚಿತಪಡಿಸುತ್ತದೆ",
    te: "ఘటనా స్థలంలో అనుమానితుడు ఉన్నట్లు సిసిటివి ధృవీకరించింది",
    hi: "सीसीटीवी घटनास्थल पर संदिग्ध की उपस्थिति की पुष्टि करता है"
  },
  "Phone records place suspect in area during timeframe": {
    ta: "தொலைபேசி பதிவுகள் சந்தேக நபர் அந்த நேரத்தில் குறிப்பிட்ட பகுதியில் இருந்ததைக் காட்டுகின்றன",
    kn: "ದೂರವಾಣಿ ದಾಖಲೆಗಳು ಆ ಸಮಯದಲ್ಲಿ ಶಂಕಿತನು ಅದೇ ಪ್ರದೇಶದಲ್ಲಿದ್ದನೆಂದು ಸೂಚಿಸುತ್ತವೆ",
    te: "ఫోన్ రికార్డులు ఆ సమయంలో అనుమానితుడు ఆ ప్రాంతంలో ఉన్నట్లు చూపుతున్నాయి",
    hi: "फोन रिकॉर्ड संदिग्ध को उस समय सीमा के दौरान क्षेत्र में दिखाते हैं"
  },
  "Prior cases show identical entry method and timing": {
    ta: "முந்தைய வழக்குகள் இதேபோன்ற நுழைவு முறை மற்றும் நேரத்தைக் காட்டுகின்றன",
    kn: "ಹಿಂದಿನ ಪ್ರಕರಣಗಳು ಪ್ರವೇಶದ ವಿಧಾನ ಮತ್ತು ಸಮಯದ ಹೋಲಿಕೆಯನ್ನು ತೋರಿಸುತ್ತವೆ",
    te: "మునుపటి కేసులు అదే ప్రవేశ విధానాన్ని మరియు సమయాన్ని చూపిస్తున్నాయి",
    hi: "पिछले मामले समान प्रवेश विधि और समय दिखाते हैं"
  },
  "Phishing email originated from spoofed corporate domain": {
    ta: "ஃபிஷிங் மின்னஞ்சல் போலியான நிறுவன டொமைனிலிருந்து வந்துள்ளது",
    kn: "ಫಿಶಿಂಗ್ ಇಮೇಲ್ ನಕಲಿ ಕಾರ್ಪೊರೇಟ್ ಡೊಮೇನ್‌ನಿಂದ ಬಂದಿದೆ",
    te: "ఫిషింగ్ ఇమెయిల్ నకిలీ కార్పొరేట్ డొమైన్ నుండి వచ్చింది",
    hi: "फ़िशिंग ईमेल नकली कॉर्पोरेट डोमेन से उत्पन्न हुआ है"
  },
  "VPN endpoint in Singapore, but linguistic analysis suggests local operator": {
    ta: "VPN இறுதிப்புள்ளி சிங்கப்பூரில் உள்ளது, ஆனால் மொழி பகுப்பாய்வு உள்ளூர் ஆபரேட்டரைக் குறிக்கிறது",
    kn: "VPN ಸಿಂಗಾಪುರದ್ದಾಗಿದ್ದರೂ, ಭಾಷಾ ವಿಶ್ಲೇಷಣೆಯು ಸ್ಥಳೀಯ ಆಪರೇಟರ್ ಇರಬಹುದು ಎಂದು ಸೂಚಿಸುತ್ತದೆ",
    te: "VPN ఎండ్‌పాయింట్ సింగపూర్‌లో ఉన్నప్పటికీ, భాషా విశ్లేషణ స్థానిక ఆపరేటర్‌ను సూచిస్తుంది",
    hi: "वीपीएन एंडपॉइंट सिंगापुर में है, लेकिन भाषाई विश्लेषण स्थानीय ऑपरेटर का सुझाव देता है"
  },
  "Similar campaigns targeting tech companies in Bengaluru": {
    ta: "பெங்களூரில் உள்ள தொழில்நுட்ப நிறுவனங்களை இலக்காகக் கொண்ட இதேபோன்ற மோசடி பிரச்சாரங்கள்",
    kn: "ಬೆಂಗಳೂರಿನ ಟೆಕ್ ಕಂಪನಿಗಳನ್ನು ಗುರಿಯಾಗಿಸಿಕೊಂಡು ನಡೆದ ಇದೇ ರೀತಿಯ ವಂಚನೆಗಳು",
    te: "బెంగళూరులోని టెక్ కంపెనీలను లక్ష్యంగా చేసుకుని ఇలాంటి ప్రచారాలు జరుగుతున్నాయి",
    hi: "बेंगलुरु में तकनीकी कंपनियों को निशाना बनाने वाले समान अभियान"
  },
  "Last seen at college campus at 4:32 PM": {
    ta: "கடைசியாக மாலை 4:32 மணிக்கு கல்லூரி வளாகத்தில் பார்க்கப்பட்டார்",
    kn: "ಕೊನೆಯದಾಗಿ ಸಂಜೆ 4:32 ಕ್ಕೆ ಕಾಲೇಜು ಆವರಣದಲ್ಲಿ ಕಂಡುಬಂದಿದ್ದಾರೆ",
    te: "చివరిసారిగా సాయంత్రం 4:32 గంటలకు కాలేజీ క్యాంపస్‌లో కనిపించారు",
    hi: "आखिरी बार शाम 4:32 बजे कॉलेज परिसर में देखा गया"
  },
  "Phone ping at MG Road at 4:45 PM — 30 min transit": {
    ta: "மாலை 4:45 மணிக்கு எம்ஜி சாலையில் தொலைபேசி சிக்னல் — 30 நிமிட பயணம்",
    kn: "ಸಂಜೆ 4:45 ಕ್ಕೆ ಎಂಜಿ ರಸ್ತೆಯಲ್ಲಿ ಫೋನ್ ಸಿಗ್ನಲ್ — 30 ನಿಮಿಷಗಳ ಚಲನೆ",
    te: "సాయంత్రం 4:45 గంటలకు ఎంజీ రోడ్‌లో ఫోన్ పింగ్ — 30 నిమిషాల ప్రయాణం",
    hi: "शाम 4:45 बजे एमजी रोड पर फोन पिंग — 30 मिनट का पारगमन"
  },
  "No financial activity since disappearance": {
    ta: "காணாமல் போனதில் இருந்து எந்த நிதி நடவடிக்கையும் இல்லை",
    kn: "ಕಾಣೆಯಾದ ನಂತರ ಯಾವುದೇ ಹಣಕಾಸು ವಹಿವಾಟು ನಡೆದಿಲ್ಲ",
    te: "కనిపించకుండా పోయినప్పటి నుండి ఎటువంటి ఆర్థిక లావాదేవీలు లేవు",
    hi: "लापता होने के बाद से कोई वित्तीय गतिविधि नहीं हुई"
  },
  "Motorcycle-based robbery, helmet use suggests planning": {
    ta: "மோட்டார் சைக்கிள் அடிப்படையிலான கொள்ளை, ஹெல்மெட் பயன்பாடு திட்டமிடலைக் குறிக்கிறது",
    kn: "ಮೋಟಾರ್ ಸೈಕಲ್ ದರೋಡೆ, ಹೆಲ್ಮೆಟ್ ಧರಿಸಿರುವುದು ಪೂರ್ವ ಯೋಜಿತ ಕೃತ್ಯವೆಂದು ಸೂಚಿಸುತ್ತದೆ",
    te: "మోటార్ సైకిల్ ఆధారిత దోపిడీ, హెల్మెట్ ఉపయోగించడం ప్రణాళికను సూచిస్తుంది",
    hi: "मोटरसाइकिल आधारित डकैती, हेलमेट का उपयोग योजना बनाने का सुझाव देता है"
  },
  "Partial plate KA-01-AB narrows search": {
    ta: "பகுதி எண் பலகை KA-01-AB தேடலை எளிதாக்குகிறது",
    kn: "ಭಾಗಶಃ ನೋಂದಣಿ ಸಂಖ್ಯೆ KA-01-AB ಹುಡುಕಾಟವನ್ನು ಸುಲಭಗೊಳಿಸುತ್ತದೆ",
    te: "పాక్షిక ప్లేట్ KA-01-AB శోధనను సులభతరం చేస్తుంది",
    hi: "आंशिक प्लेट KA-01-AB खोज को संकीर्ण करती है"
  },
  "Note suggests voluntary departure, not abduction": {
    ta: "குறிப்பு கடத்தலைக் குறிக்கவில்லை, அவராகவே சென்றதைக் குறிக்கிறது",
    kn: "ಟಿಪ್ಪಣಿಯು ಸ್ವಯಂಪ್ರೇರಿತ ನಿರ್ಗಮನವನ್ನು ಸೂಚಿಸುತ್ತದೆ, ಅಪಹರಣವಲ್ಲ",
    te: "లేఖ స్వచ్ఛందంగా వెళ్లినట్లు సూచిస్తుంది, కిడ్నాప్ కాదు",
    hi: "नोट स्वैच्छिक प्रस्थान का सुझाव देता है, अपहरण का नहीं"
  },
  "Social media shows recent distress signals": {
    ta: "சமூக ஊடகங்கள் சமீபத்திய மன உளைச்சல் சிக்னல்களைக் காட்டுகின்றன",
    kn: "ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮವು ಇತ್ತೀಚಿನ ಮಾನಸಿಕ ಯಾತನೆಯ ಸಂಕೇತಗಳನ್ನು ತೋರಿಸುತ್ತದೆ",
    te: "సోషల్ మీడియా ఇటీవలి బాధాకరమైన సంకేతాలను చూపుతోంది",
    hi: "सोशल मीडिया हाल के संकट के संकेत दिखाता है"
  },

  // AI Insights
  "MO fingerprint matches 3 unsolved cases in Bengaluru North across the last 6 months. The entry method (rear door, same tool marks) and timing (2-4 AM) are consistent. Recommend cross-district alert for similar pattern.": {
    ta: "கடந்த 6 மாதங்களில் பெங்களூரு வடக்கில் தீர்க்கப்படாத 3 வழக்குகளுடன் MO ஒத்துப்போகிறது. நுழைவு முறை மற்றும் நேரம் சீராக உள்ளது. ஒத்த பாணிக்கு மாவட்டங்களுக்கு இடையேயான எச்சரிக்கையை பரிந்துரைக்கவும்.",
    kn: "ಕಳೆದ 6 ತಿಂಗಳುಗಳಲ್ಲಿ ಬೆಂಗಳೂರು ಉತ್ತರದಲ್ಲಿನ 3 ಬಗೆಹರಿಯದ ಪ್ರಕರಣಗಳಿಗೆ ಎಂ.ಓ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ. ಪ್ರವೇಶದ ವಿಧಾನ ಮತ್ತು ಸಮಯವು ಒಂದೇ ಆಗಿರುತ್ತದೆ. ಅಂತರ್-ಜಿಲ್ಲಾ ಎಚ್ಚರಿಕೆ ನೀಡಲು ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ.",
    te: "గత 6 నెలల్లో బెంగళూరు నార్త్‌లో పరిష్కారం కాని 3 కేసులతో MO సరిపోలింది. ప్రవేశ విధానం మరియు సమయం స్థిరంగా ఉన్నాయి. ఇలాంటి నమూనా కోసం క్రాస్-డిస్ట్రిక్ట్ అలర్ట్‌ను సిఫార్సు చేయండి.",
    hi: "एमओ फिंगरप्रिंट पिछले 6 महीनों में बेंगलुरु उत्तर में 3 अनसुलझे मामलों से मेल खाता है। प्रवेश विधि और समय सुसंगत हैं। समान पैटर्न के लिए क्रॉस-डिस्ट्रिक्ट अलर्ट की सिफारिश करें।"
  },
  "Pattern matches recent phishing campaigns targeting tech companies in Bengaluru. Email template similar to known threat actor group. Recommend coordinated investigation with cybercrime cell.": {
    ta: "பெங்களூரில் உள்ள தொழில்நுட்ப நிறுவனங்களை இலக்காகக் கொண்ட சமீபத்திய ஃபிஷிங் பிரச்சாரங்களுடன் பாணி பொருந்துகிறது. சைபர் கிரைம் பிரிவுடன் ஒருங்கிணைந்த விசாரணைக்கு பரிந்துரைக்கவும்.",
    kn: "ಬೆಂಗಳೂರಿನ ಟೆಕ್ ಕಂಪನಿಗಳನ್ನು ಗುರಿಯಾಗಿಸಿಕೊಂಡ ಇತ್ತೀಚಿನ ಫಿಶಿಂಗ್ ವಂಚನೆಗಳಿಗೆ ಇದು ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ. ಸೈಬರ್ ಕ್ರೈಮ್ ವಿಭಾಗದೊಂದಿಗೆ ಜಂಟಿ ತನಿಖೆಗೆ ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ.",
    te: "బెంగళూరులోని టెక్ కంపెनीలను లక్ష్యంగా చేసుకున్న ఇటీవలి ఫిషింగ్ ప్రచారాలతో ఈ నమూనా సరిపోలింది. సైబర్ క్రైమ్ విభాగంతో సమన్వయ విచారణను సిఫార్సు చేయండి.",
    hi: "पैटर्न बेंगलुरु में तकनीकी कंपनियों को निशाना बनाने वाले हालिया फ़िशिंग अभियानों से मेल खाता है। साइबर अपराध सेल के साथ समन्वित जांच की सिफारिश करें।"
  },
  "Phone activity ceased abruptly. No prior history of similar incidents. Recommend checking nearby hospitals and shelters.": {
    ta: "தொலைபேசி செயல்பாடு திடீரென நின்றது. இது போன்ற சம்பவங்கள் முன்பு நடந்ததில்லை. அருகிலுள்ள மருத்துவமனைகள் மற்றும் தங்குமிடங்களைச் சரிபார்க்க பரிந்துரைக்கவும்.",
    kn: "ಫೋನ್ ಚಟುವಟಿಕೆಯು ಇದ್ದಕ್ಕಿದ್ದಂತೆ ಸ್ಥಗಿತಗೊಂಡಿದೆ. ಈ ಹಿಂದೆ ಇಂತಹ ಯಾವುದೇ ಘಟನೆ ನಡೆದಿಲ್ಲ. ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗಳು ಮತ್ತು ಆಶ್ರಯ ತಾಣಗಳನ್ನು ಪರಿಶೀಲಿಸಲು ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ.",
    te: "ఫోన్ యాక్టివిటీ అకస్మాత్తుగా నిలిచిపోయింది. ఇలాంటి సంఘటనలు గతంలో జరగలేదు. సమీపంలోని ఆసుపత్రులు మరియు ఆశ్రయాలను తనిఖీ చేయాలని సిఫార్సు చేయండి.",
    hi: "फोन गतिविधि अचानक बंद हो गई। ऐसी घटनाओं का कोई पूर्व इतिहास नहीं है। नजदीकी अस्पतालों और आश्रयों की जाँच करने की सिफारिश करें।"
  },
  "MO matches robbery series in Bengaluru Urban. Same motorcycle-based approach.": {
    ta: "பெங்களூரு நகர்ப்புறத்தில் நடந்த தொடர் கொள்ளைகளுடன் MO ஒத்துப்போகிறது. அதே மோட்டார் சைக்கிள் அடிப்படையிலான அணுகுமுறை.",
    kn: "ಬೆಂಗಳೂರು ನಗರದಲ್ಲಿ ನಡೆದ ಸರಣಿ ದರೋಡೆಗಳಿಗೆ ಎಂ.ಓ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ. ಅದೇ ಮೋಟಾರ್ ಸೈಕಲ್ ಆಧಾರಿತ ವಿಧಾನ.",
    te: "బెంగళూరు అర్బన్‌లో జరిగిన దోపిడీల సిరీస్‌తో MO సరిపోలింది. అదే మోటార్ సైకిల్ ఆధారిత విధానం.",
    hi: "एमओ बेंगलुरु शहरी क्षेत्र में डकैती श्रृंखला से मेल खाता है। वही मोटरसाइकिल आधारित तरीका।"
  },
  "Juvenile may be at risk. Social media analysis shows recent distress signals.": {
    ta: "சிறுவன் ஆபத்தில் இருக்கலாம். சமூக ஊடக பகுப்பாய்வு சமீபத்திய மன உளைச்சல் சிக்னல்களைக் காட்டுகிறது.",
    kn: "ಅಪ್ರಾಪ್ತ ವಯಸ್ಕ ಅಪಾಯದಲ್ಲಿರಬಹುದು. ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮ ವಿಶ್ಲೇಷಣೆಯು ಇತ್ತೀಚಿನ ತೊಂದರೆಯ ಸಂಕೇತಗಳನ್ನು ತೋರಿಸುತ್ತದೆ.",
    te: "మైనర్ ప్రమాదంలో ఉండవచ్చు. సోషల్ మీడియా విశ్లేషణ ఇటీవలి బాధాకరమైన సంకేతాలను చూపుతోంది.",
    hi: "किशोर जोखिम में हो सकता है। सोशल मीडिया विश्लेषण हाल के संकट के संकेत दिखाता है।"
  },

  // Suggestions
  "Cross-reference suspect phone records with cell tower data from other unsolved cases": {
    ta: "சந்தேக நபரின் தொலைபேசி பதிவுகளை தீர்க்கப்படாத பிற வழக்குகளின் செல் கோபுர தரவுகளுடன் குறுக்கு குறிப்பு செய்யவும்",
    kn: "ಬಗೆಹರಿಯದ ಇತರ ಪ್ರಕರಣಗಳ ಸೆಲ್ ಟವರ್ ಮಾಹಿತಿಯೊಂದಿಗೆ ಶಂಕಿತನ ಫೋನ್ ದಾಖಲೆಗಳನ್ನು ಹೋಲಿಸಿ ನೋಡಿ",
    te: "పరిష్కారం కాని ఇతర కేసుల సెల్ టవర్ డేటాతో అనుమానిత ఫోన్ రికార్డులను సరిపోల్చండి",
    hi: "अन्य अनसुलझे मामलों के सेल टॉवर डेटा के साथ संदिग्ध फोन रिकॉर्ड का क्रॉस-रेफरेंस करें"
  },
  "Check if suspect has been seen in Indiranagar area recently": {
    ta: "சந்தேக நபர் சமீபத்தில் இந்திராநகர் பகுதியில் நடமாடினாரா என்று பார்க்கவும்",
    kn: "ಶಂಕಿತನು ಇತ್ತೀಚೆಗೆ ಇಂದಿರಾನಗರ ಪ್ರದೇಶದಲ್ಲಿ ಕಂಡುಬಂದಿದ್ದನೇ ಎಂದು ಪರಿಶೀಲಿಸಿ",
    te: "ఇటీవల ఇందిరానగర్ ప్రాంతంలో అనుమానితుడు కనిపించాడో లేదో తనిఖీ చేయండి",
    hi: "जांचें कि क्या संदिग्ध को हाल ही में इंदिरा नगर क्षेत्र में देखा गया है"
  },
  "Request CCTV footage from main road cameras between 1-5 AM": {
    ta: "அதிகாலை 1-5 மணி வரை முக்கிய சாலை கேமராக்களிலிருந்து சிசிடிவி காட்சிகளைக் கோரவும்",
    kn: "ಮುಂಜಾನೆ 1-5 ರ ನಡುವಿನ ಮುಖ್ಯ ರಸ್ತೆ ಕ್ಯಾಮೆರಾಗಳ ಸಿಸಿಟಿವಿ ದೃಶ್ಯಾವಳಿಗಳನ್ನು ಕೋರಿ",
    te: "తెల్లవారుజామున 1-5 గంటల మధ్య మెయిన్ రోడ్ కెమెరాల నుండి సిసిటివి ఫుటేజ్ కోసం అభ్యర్థించండి",
    hi: "सुबह 1-5 बजे के बीच मुख्य सड़क के कैमरों से सीसीटीवी फुटेज का अनुरोध करें"
  },
  "Coordinate with Singapore authorities for VPN provider logs": {
    ta: "VPN வழங்குநர் பதிவுகளுக்காக சிங்கப்பூர் அதிகாரிகளுடன் ஒருங்கிணைக்கவும்",
    kn: "VPN ಪೂರೈಕೆದಾರರ ದಾಖಲೆಗಳಿಗಾಗಿ ಸಿಂಗಾಪುರ ಅಧಿಕಾರಿಗಳೊಂದಿಗೆ ಸಮನ್ವಯ ಸಾಧಿಸಿ",
    te: "VPN ప్రొవైడర్ లాగ్‌ల కోసం సింగపూర్ అధికారులతో సమన్వయం చేసుకోండి",
    hi: "वीपीएन प्रदाता लॉग के लिए सिंगापुर अधिकारियों के साथ समन्वय करें"
  },
  "Analyze email header routing for origin clues": {
    ta: "மின்னஞ்சல் தோற்றத்தை கண்டறிய மின்னஞ்சல் தலைப்பு ரூட்டிங்கை பகுப்பாய்வு செய்யவும்",
    kn: "ಮೂಲದ ಸುಳಿವುಗಳಿಗಾಗಿ ಇಮೇಲ್ ಹೆಡರ್ ರೂಟಿಂಗ್ ಅನ್ನು ವಿಶ್ಲೇಷಿಸಿ",
    te: "మూలాల ఆధారాల కోసం ఇమెయిల్ హెడర్ రూటింగ్‌ను విశ్ಲೇషించండి",
    hi: "मूल सुरागों के लिए ईमेल हेडर रूटिंग का विश्लेषण करें"
  },
  "Check if same infrastructure used in other recent phishing attacks": {
    ta: "சமீபத்திய பிற ஃபிஷிங் தாக்குதல்களிலும் இதே உள்கட்டமைப்பு பயன்படுத்தப்பட்டதா என்று பார்க்கவும்",
    kn: "ಇತ್ತೀಚಿನ ಇತರ ಫಿಶಿಂಗ್ ದಾಳಿಗಳಲ್ಲಿ ಅದೇ ಮೂಲಸೌಕರ್ಯವನ್ನು ಬಳಸಲಾಗಿದೆಯೇ ಎಂದು ಪರಿಶೀಲಿಸಿ",
    te: "ఇటీవలి ఇతర ఫిషింగ్ దాడులలో ఇదే మౌలిక సదుపాయాలను ఉపయోగించారో లేదो తనిఖీ చేయండి",
    hi: "जांचें कि क्या हाल के अन्य फ़िशिंग हमलों में इसी बुनियादी ढांचे का उपयोग किया गया था"
  },
  "Issue missing person alert to all Bengaluru stations": {
    ta: "அனைத்து பெங்களூரு நிலையங்களுக்கும் காணாமல் போன நபர் எச்சரிக்கையை வெளியிடவும்",
    kn: "ಎಲ್ಲಾ ಬೆಂಗಳೂರು ಪೊಲೀಸ್ ಠಾಣೆಗಳಿಗೆ ಕಾಣೆಯಾದ ವ್ಯಕ್ತಿಯ ಬಗ್ಗೆ ಎಚ್ಚರಿಕೆ ಸಂದೇಶ ರವಾನಿಸಿ",
    te: "అన్ని బెంగళూరు స్టేషన్‌లకు తప్పిపోయిన వ్యక్తి అలర్ట్‌ను జారీ చేయండి",
    hi: "बेंगलुरु के सभी थानों को लापता व्यक्ति का अलर्ट जारी करें"
  },
  "Check hospital admission records for matching description": {
    ta: "பொருத்தமான அடையாளங்களுக்கு மருத்துவமனை சேர்க்கை பதிவுகளைச் சரிபார்க்கவும்",
    kn: "ಹೊಂದುವಂತಹ ವಿವರಗಳಿಗಾಗಿ ಆಸ್ಪತ್ರೆ ದಾಖಲಾತಿ ದಾಖಲೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ",
    te: "సరిపోయే గుర్తింపుల కోసం ఆసుపత్రి ప్రవేశ రికార్డులను తనిీ చేయండి",
    hi: "मिलान विवरण के लिए अस्पताल में भर्ती होने के रिकॉर्ड की जांच करें"
  },
  "Review social media activity for distress signals": {
    ta: "மன உளைச்சல் சிக்னல்களுக்காக சமூக ஊடக செயல்பாட்டை மதிப்பாய்வு செய்யவும்",
    kn: "ಮನಃಕ್ಲೇಶದ ಸುಳಿವುಗಳಿಗಾಗಿ ಸಾಮಾಜिक ಮಾಧ್ಯಮ ಚಟುವಟಿಕೆಯನ್ನು ಪರಿಶೀಲಿಸಿ",
    te: "బాధాకరమైన సంకేతాల కోసం సోషల్ మీడియా కార్యాచరణను సమీక్షించండి",
    hi: "संकट के संकेतों के लिए सोशल मीडिया गतिविधि की समीक्षा करें"
  },
  "Run partial plate through RTO database": {
    ta: "ஆர்டிஓ தரவுத்தளத்தின் மூலம் பகுதி எண் பலகையை சரிபார்க்கவும்",
    kn: "ಭಾಗಶಃ ಪತ್ತೆಯಾದ ಸಂಖ್ಯೆಯನ್ನು ಆರ್‌ಟಿಓ ಡೇಟಾಬೇಸ್‌ನಲ್ಲಿ ಪರಿಶೀಲಿಸಿ",
    te: "RTO డేటాబేస్ ద్వారా పాక్షిక ప్లేట్ నంబర్‌ను రన్ చేయండి",
    hi: "आरटीओ डेटाबेस के माध्यम से आंशिक प्लेट चलाएं"
  },
  "Check for similar motorcycle robberies in surrounding areas": {
    ta: "சுற்றியுள்ள பகுதிகளில் இதேபோன்ற மோட்டார் சைக்கிள் கொள்ளைகள் நடந்துள்ளதா என்று சரிபார்க்கவும்",
    kn: "ಸುತ್ತಮುತ್ತಲಿನ ಪ್ರದೇಶಗಳಲ್ಲಿ ಇದೇ ರೀತಿಯ ಮೋಟಾರ್ ಸೈಕಲ್ ದರೋಡೆಗಳು ನಡೆದಿವೆಯೇ ಎಂದು ಪರಿಶೀಲಿಸಿ",
    te: "పరిసర ప్రాంతాలలో ఇలాంటి మోటార్ సైకిల్ దోపిడీలు జరిగాయో లేదो తనిఖీ చేయండి",
    hi: "आसपास के क्षेत्रों में समान मोटरसाइकिल डकैतियों की जांच करें"
  },
  "Issue missing person alert to all stations": {
    ta: "அனைத்து நிலையங்களுக்கும் காணாமல் போன நபர் எச்சரிக்கையை வெளியிடவும்",
    kn: "ಎಲ್ಲಾ ಪೊಲೀಸ್ ಠಾಣೆಗಳಿಗೆ ಕಾಣೆಯಾದ ವ್ಯಕ್ತಿಯ ಬಗ್ಗೆ ಎಚ್ಚರಿಕೆ ಸಂದೇಶ ರವಾನಿಸಿ",
    te: "అన్ని స్టేషన్‌లకు తప్పిపోయిన వ్యక్తి అలర్ట్‌ను జారీ చేయండి",
    hi: "सभी थानों को लापता व्यक्ति का अलर्ट जारी करें"
  },
  "Check shelters and hospitals": {
    ta: "காப்பகங்கள் மற்றும் மருத்துவமனைகளைச் சரிபார்க்கவும்",
    kn: "ನಿರಾಶ್ರಿತ ತಾಣಗಳು ಮತ್ತು ಆಸ್ಪತ್ರೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ",
    te: "ఆశ్రయాలు మరియు ఆసుపత్రులను తనిఖీ చేయండి",
    hi: "आश्रयों और अस्पतालों की जांच करें"
  },
  "Contact school friends for information": {
    ta: "தகவலுக்கு பள்ளி நண்பர்களைத் தொடர்பு கொள்ளவும்",
    kn: "ಮಾಹಿತಿಗಾಗಿ ಶಾಲಾ ಸ್ನೇಹಿತರನ್ನು ಸಂಪರ್ಕಿಸಿ",
    te: "సమాచారం కోసం పాఠశాల స్నేహితులను సంప్రదించండి",
    hi: "जानकारी के लिए स्कूल के दोस्तों से संपर्क करें"
  },
};

/**
 * Translate a key based on the provided language code.
 * @param {string} key - The translation key.
 * @param {string} [lang='en'] - Language code (en, ta, kn, te, hi).
 * @returns {string} Translated string or the key if missing.
 */
export function t(key, lang = "en") {
  if (rawTranslations[key] && lang !== "en") {
    return rawTranslations[key][lang] || rawTranslations[key].en || key;
  }
  const langDict = translations[lang] || translations.en;
  return langDict[key] || translations.en[key] || key;
}

// Helper to translate alert type labels dynamically
export function translateAlertType(type, lang = "en") {
  const mapping = {
    whisper: "whisper_alert",
    "fir-match": "fir_match",
    "cross-district": "cross_district",
    evidence: "evidence_link",
    ai: "ai_notification",
  };
  const key = mapping[type];
  return key ? t(key, lang) : type;
}

// Helper to translate crime type labels dynamically
export function translateCrimeType(type, lang = "en") {
  const mapping = {
    theft: "theft",
    Theft: "theft",
    fraud: "fraud",
    Fraud: "fraud",
    cybercrime: "cybercrime",
    Cybercrime: "cybercrime",
    assault: "assault",
    Assault: "assault",
    other: "other",
    Other: "other",
  };
  const key = mapping[type];
  return key ? t(key, lang) : type;
}

// Helper to translate district names dynamically
export function translateDistrictName(name, lang = "en") {
  const mapping = {
    "Bengaluru Urban": "bengaluru_urban",
    "Bengaluru Rural": "bengaluru_rural",
    "Mysuru": "mysuru",
    "Mangaluru": "mangalaru",
    "Hubballi": "hubballi",
    "Hubballi-Dharwad": "hubballi",
    "Other": "other",
  };
  const key = mapping[name];
  return key ? t(key, lang) : name;
}

// Helper to translate calendar days
export function translateCalendarDay(day, lang = "en") {
  const mapping = {
    Sun: "Sun",
    Mon: "Mon",
    Tue: "Tue",
    Wed: "Wed",
    Thu: "Thu",
    Fri: "Fri",
    Sat: "Sat",
  };
  const key = mapping[day];
  return key ? t(key, lang) : day;
}

// Helper to translate calendar event titles dynamically
export function translateCalendarEvent(title, lang = "en") {
  const mapping = {
    "Court Hearing — FIR #4489": "court_hearing",
    "Bail Review — Case #4512": "bail_review",
    "Shift Handover — Morning": "shift_handover",
    "Night Patrol Briefing": "night_patrol",
  };
  const key = mapping[title];
  return key ? t(key, lang) : title;
}

// Helper to translate cases status dynamically
export function translateStatus(status, lang = "en") {
  const mapping = {
    "Active": "active",
    "active": "active",
    "Pending Review": "pending_review",
    "Under Investigation": "under_investigation",
    "Closed": "closed",
    "closed": "closed",
    "saved": "saved",
  };
  const key = mapping[status];
  return key ? t(key, lang) : status;
}

// Helper to translate Node Labels in Knowledge Graph
export function translateNodeLabel(label, lang = "en") {
  const mapping = {
    "Ravi Kumar": "ravi_kumar",
    "Deepak Reddy": "deepak_reddy",
    "Mohammed Ali": "mohammed_ali",
    "Imran Khan": "imran_khan",
    "Venkatesh Reddy": "venkatesh_reddy",
    "Rajesh Sharma": "rajesh_sharma",
    "CCTV #4521": "cctv_4521",
    "Phone Records": "phone_records",
    "Fingerprint": "fingerprint",
  };
  const key = mapping[label];
  return key ? t(key, lang) : label;
}

// Helper to translate Edge Labels in Knowledge Graph
export function translateEdgeLabel(label, lang = "en") {
  const trimmed = label ? label.trim() : "";
  const mapping = {
    "Operational Head": "operational_head",
    "Training": "training",
    "Logistics": "logistics",
    "Cyber Ops": "cyber_ops",
    "Parts Dealer": "parts_dealer",
    "Identified": "identified",
    "Cell tower": "cell_tower",
    "Partial print": "partial_print",
    "Registered": "registered",
    "Used in crime": "used_in_crime",
    "Primary": "primary",
    "burner": "burner",
    "Shared": "shared",
  };
  const key = mapping[trimmed];
  return key ? t(key, lang) : label;
}

// Helper to translate Chat History Item Titles
export function translateChatTitle(title, lang = "en") {
  const mapping = {
    "FIR #4521 Analysis": "fir_analysis_title",
    "Suspect Network — Ravi Kumar": "suspect_network_title",
    "MO Pattern Research": "mo_pattern_title",
    "Cross-district case linking": "cross_district_title",
    "Theft pattern Bengaluru North": "theft_pattern_title",
    "Whisper alert investigation": "whisper_investigation_title",
    "Evidence report generation": "evidence_report_title",
  };
  const key = mapping[title];
  return key ? t(key, lang) : title;
}

// Helper to translate risk tags (High, Medium, Low)
export function translateRisk(risk, lang = "en") {
  const mapping = {
    high: "High",
    High: "High",
    medium: "Medium",
    Medium: "Medium",
    low: "Low",
    Low: "Low",
  };
  // We can add them totranslations
  const translationsMap = {
    High: { en: "High", ta: "உயர்", kn: "ಹೆಚ್ಚು", te: "అధిక", hi: "उच्च" },
    Medium: { en: "Medium", ta: "நடுத்தர", kn: "ಮಧ್ಯಮ", te: "మధ్యమ", hi: "मध्यम" },
    Low: { en: "Low", ta: "குறைந்த", kn: "ಕಡಿಮೆ", te: "తక్కువ", hi: "कम" },
  };
  const key = mapping[risk];
  return (translationsMap[key] && translationsMap[key][lang]) || risk;
}

// Helper to translate hotspots names
export function translateHotspot(name, lang = "en") {
  const translationsMap = {
    "Malleshwaram": { en: "Malleshwaram", ta: "மல்லேஸ்வரம்", kn: "ಮಲ್ಲೇಶ್ವರಂ", te: "మల్లేశ్వరం", hi: "मल्लेश्वरम" },
    "Whitefield": { en: "Whitefield", ta: "ஒயிட்ஃபீல்ட்", kn: "ವೈಟ್‌ಫೀಲ್ಡ್", te: "వైట్‌ఫీల్డ్", hi: "व्हाइटफील्ड" },
    "Electronic City": { en: "Electronic City", ta: "எலக்ட்ரானிக் சிட்டி", kn: "ಎಲೆಕ್ಟ್ರಾನಿಕ್ ಸಿಟಿ", te: "ఎలక్ట్రానిక్ సిటీ", hi: "इलेक्ट्रॉनिक सिटी" },
    "Koramangala": { en: "Koramangala", ta: "கோரமங்களா", kn: "ಕೋರಮಂಗಲ", te: "కోరమంగళ", hi: "कोरमंगला" },
    "Indiranagar": { en: "Indiranagar", ta: "இந்திராநகர்", kn: "ಇಂದಿರಾನಗರ್", te: "ఇందిరానగర్", hi: "इंदिरा नगर" },
    "Mysuru City": { en: "Mysuru City", ta: "மைசூரு நகரம்", kn: "ಮೈಸೂರು ನಗರ", te: "మైసూర్ సిటీ", hi: "मैसूरु शहर" },
    "Hunsur": { en: "Hunsur", ta: "ஹன்சூர்", kn: "ಹುಣಸೂರು", te: "హున్సూర్", hi: "हुनसूर" },
    "Mangaluru City": { en: "Mangaluru City", ta: "மங்களூரு நகரம்", kn: "ಮಂಗಳೂರು ನಗರ", te: "మంగళూరు సిటీ", hi: "मंगलुरु शहर" },
    "Puttur": { en: "Puttur", ta: "புத்தூர்", kn: "ಪುತ್ತೂರು", te: "ಪುತ್ತೂರು", hi: "पुत्तूर" },
    "Hubballi City": { en: "Hubballi City", ta: "ஹூப்ளி நகரம்", kn: "ಹುಬ್ಬಳ್ಳಿ ನಗರ", te: "హుబ్లీ సిటీ", hi: "हुबली शहर" },
    "Dharwad": { en: "Dharwad", ta: "தார்வாட்", kn: "ಧಾರವಾಡ", te: "ధార్వాడ్", hi: "धारवाड़" },
    "Gulbarga City": { en: "Gulbarga City", ta: "குல்பர்கா நகரம்", kn: "ಗುಲ್ಬರ್ಗಾ ನಗರ", te: "గుల్బర్గా సిటీ", hi: "गुलबर्गा शहर" },
  };
  return (translationsMap[name] && translationsMap[name][lang]) || name;
}

// Fallback dynamic string translation helper
export function translateText(text, lang = "en") {
  if (!text) return "";
  const trimmed = text.trim();
  if (rawTranslations[trimmed] && rawTranslations[trimmed][lang]) {
    return rawTranslations[trimmed][lang];
  }
  return text;
}

// Export list of supported languages for UI selectors
export const supportedLanguages = ["en", "ta", "kn", "te", "hi"];
