// Simple translation utility for CrimeMatrix UI
// Languages: en (English), ta (Tamil), kn (Kannada), te (Telugu), hi (Hindi)

const translations = {
  en: {
    accept: "Accept",
    dismiss: "Dismiss",
    view: "View",
    alert: "Alert",
    priority: "Priority",
    status: "Status",
    alerts: "alerts",
    alert_feed: "Alert Feed",
    all_alerts: "All Alerts",
    new_alerts: "New Alerts",
    pending: "Pending",
    resolved: "Resolved",
    total_alerts: "Total Alerts",
    alerts_by_type: "Alerts by Type",
    recent_activity: "Recent Activity",
    crime_heatmap: "Crime Heatmap",
    whisper_alert: "Whisper Alert",
    fir_match: "FIR Match",
    cross_district: "Cross-District",
    evidence_link: "Evidence Link",
    ai_notification: "AI Notification",
    intelligence_alerts: "Intelligence Alerts",
    monitor_intel: "Monitor and respond to proactive intelligence",
    performance_summary: "Alert Performance Summary",
    pending_review: "Pending Review",
    alert_trend: "Alert Trend",
    alert_distribution: "Alert Distribution",
    total: "Total",
    recent_alerts: "Recent Alerts",
    more_details: "More details",
    // Analytics & Charts Translation
    crime_breakdown: "Crime Type Breakdown",
    cases_label: "cases",
    cases_by_crime_type: "Cases by Crime Type",
    todays_cases: "Today's Cases",
    live: "Live",
    total_cases: "Total Cases",
    theft: "Theft",
    fraud: "Fraud",
    cybercrime: "Cybercrime",
    assault: "Assault",
    other: "Other",
    top_districts: "Top Districts",
    by_case_count: "by case count",
    case_resolution: "Case Resolution",
    by_time_period: "by time period",
    total_resolved: "Total Resolved",
    avg_resolution: "Avg. Resolution",
    case_trend: "Case Trend",
    time_interval: "Time Interval:",
    weekly: "Weekly",
    monthly: "Monthly",
    yearly: "Yearly",
    vs_30_days: "vs 30 Days",
    cases_by_district: "Cases by District",
    investigation_calendar: "Investigation Calendar",
    hearings: "Hearings",
    shifts: "Shifts",
    cases_by_status: "Cases by Status",
    active: "Active",
    under_investigation: "Under Investigation",
    closed: "Closed",
    // Calendar Events
    court_hearing: "Court Hearing — FIR #4489",
    bail_review: "Bail Review — Case #4512",
    shift_handover: "Shift Handover — Morning",
    night_patrol: "Night Patrol Briefing",
    // Districts
    bengaluru_urban: "Bengaluru Urban",
    bengaluru_rural: "Bengaluru Rural",
    mysuru: "Mysuru",
    mangalaru: "Mangaluru",
    hubballi: "Hubballi",
    // Days/Periods
    days_label: "days",
    "0-30 days": "0-30 days",
    "31-60 days": "31-60 days",
    "61-90 days": "61-90 days",
    "91-180 days": "91-180 days",
    "180+ days": "180+ days",
    Sun: "Sun",
    Mon: "Mon",
    Tue: "Tue",
    Wed: "Wed",
    Thu: "Thu",
    Fri: "Fri",
    Sat: "Sat",

    // --- NEW COPILOT TRANSLATIONS ---
    analyzing: "Analyzing...",
    ai_copilot: "AI Copilot",
    hi_there: "Hi, there 👋",
    ask_copilot: "Ask me anything about cases, suspects, or investigations.",
    chat_history: "Chat History",
    new_chat: "New Chat",
    saved: "Saved",
    today: "Today",
    yesterday: "Yesterday",
    ask_anything_placeholder: "Ask me anything...",
    all_sources: "All Sources",
    fir_database: "FIR Database",
    suspects: "Suspects",
    evidence: "Evidence",
    stations: "Stations",
    context: "Context",
    referenced_sources: "Referenced Sources",
    actions: "Actions",
    related_cases: "Related Cases",
    generate_report: "Generate Report",
    export_conversation: "Export Conversation",
    save_to_case: "Save to Case",
    share_with_team: "Share with Team",
    robbery_indiranagar: "Robbery — Indiranagar",
    theft_koramangala: "Theft — Koramangala",
    cyber_fraud_ecity: "Cyber fraud — Electronic City",
    copilot_assistant_desc: "Your AI Investigation Assistant — trained on Karnataka police protocols, criminal databases, and legal frameworks.",
    quick_tasks: "Quick Tasks",
    suggested_prompt: "Suggested prompt",
    task_analyze_connections: "Analyze suspect connections",
    task_generate_report: "Generate investigation report",
    task_search_cross_district: "Search cross-district cases",
    suggested_prompt_text: "What are the common MO patterns in theft cases across Bengaluru district this month?",
    theft_malleshwaram: "Theft — Malleshwaram, Bengaluru",
    suspect_linked_3_cases: "Linked to 3 open cases",
    cctv_footage_main_road: "CCTV Footage — Main Road",
    captured_at_215_am: "Captured at 2:15 AM",
    malleshwaram_bengaluru: "Malleshwaram, Bengaluru",
    crime_hotspot_zone: "Crime hotspot zone",

    // --- NEW GRAPH TRANSLATIONS ---
    all_connections: "All Connections",
    criminal_network: "Criminal Network",
    gang_network: "Gang Network",
    evidence_links: "Evidence Links",
    select_node: "Select a Node",
    click_node_desc: "Click on any node in the graph to view details",
    risk: "Risk",
    cases: "Cases",
    connections: "Connections",
    view_full_profile: "View Full Profile",
    add_to_investigation: "Add to Investigation",
    // Graph Suspects
    ravi_kumar: "Ravi Kumar",
    deepak_reddy: "Deepak Reddy",
    mohammed_ali: "Mohammed Ali",
    imran_khan: "Imran Khan",
    venkatesh_reddy: "Venkatesh Reddy",
    rajesh_sharma: "Rajesh Sharma",
    // Graph Evidence/Node type labels
    cctv_4521: "CCTV #4521",
    phone_records: "Phone Records",
    fingerprint: "Fingerprint",
    suspect: "Suspect",
    vehicle: "Vehicle",
    phone: "Phone",
    // Graph Edges
    accomplice: "Accomplice",
    fence: "Fence",
    operational_head: "Operational Head",
    training: "Training",
    logistics: "Logistics",
    cyber_ops: "Cyber Ops",
    parts_dealer: "Parts Dealer",
    identified: "Identified",
    cell_tower: "Cell tower",
    partial_print: "Partial print",
    registered: "Registered",
    used_in_crime: "Used in crime",
    primary: "Primary",
    burner: "Burner",
    shared: "Shared",

    // Chat History Titles
    fir_analysis_title: "FIR #4521 Analysis",
    suspect_network_title: "Suspect Network — Ravi Kumar",
    mo_pattern_title: "MO Pattern Research",
    cross_district_title: "Cross-district case linking",
    theft_pattern_title: "Theft pattern Bengaluru North",
    whisper_investigation_title: "Whisper alert investigation",
    evidence_report_title: "Evidence report generation",
  },
  ta: {
    accept: "ஒப்புக்கொள்",
    dismiss: "நிராகரி",
    view: "பார்",
    alert: "எச்சரிக்கை",
    priority: "முன்னுரிமை",
    status: "நிலை",
    alerts: "அவசரங்கள்",
    alert_feed: "அவசரப் புலம்",
    all_alerts: "அனைத்து எச்சரிக்கைகள்",
    new_alerts: "புதிய எச்சரிக்கைகள்",
    pending: "நிலுவையில் உள்ளது",
    resolved: "தீர்க்கப்பட்டது",
    total_alerts: "மொத்த எச்சரிக்கைகள்",
    alerts_by_type: "வகை வாரியாக எச்சரிக்கைகள்",
    recent_activity: "சமீபத்திய நடவடிக்கை",
    crime_heatmap: "குற்ற வெப்ப வரைபடம்",
    whisper_alert: "விஸ்பர் எச்சரிக்கை",
    fir_match: "எஃப்.ஐ.ஆர் பொருத்தம்",
    cross_district: "மாவட்டங்களுக்கு இடையேயான",
    evidence_link: "ஆதார இணைப்பு",
    ai_notification: "செயற்கை நுண்ணறிவு அறிவிப்பு",
    intelligence_alerts: "உளவுத்துறை எச்சரிக்கைகள்",
    monitor_intel: "செயலில் உள்ள உளவுத்துறையை கண்காணித்து பதிலளிக்கவும்",
    performance_summary: "எச்சரிக்கை செயல்திறன் சுருக்கம்",
    pending_review: "மதிப்பாய்வு நிலுவையில் உள்ளது",
    alert_trend: "எச்சரிக்கை போக்கு",
    alert_distribution: "எச்சரிக்கை விநியோகம்",
    total: "மொத்தம்",
    recent_alerts: "சமீபத்திய எச்சரிக்கைகள்",
    more_details: "கூடுதல் விவரங்கள்",
    // Analytics & Charts Translation
    crime_breakdown: "குற்ற வகை முறிவு",
    cases_label: "வழக்குகள்",
    cases_by_crime_type: "குற்ற வகை வாரியாக வழக்குகள்",
    todays_cases: "இன்றைய வழக்குகள்",
    live: "நேரலை",
    total_cases: "மொத்த வழக்குகள்",
    theft: "களவு",
    fraud: "மோசடி",
    cybercrime: "சைபர் குற்றம்",
    assault: "தாக்குதல்",
    other: "இதர",
    top_districts: "முன்னணி மாவட்டங்கள்",
    by_case_count: "வழக்குகளின் எண்ணிக்கை அடிப்படையில்",
    case_resolution: "வழக்கு தீர்வு",
    by_time_period: "கால அளவின் அடிப்படையில்",
    total_resolved: "மொத்தம் தீர்க்கப்பட்டவை",
    avg_resolution: "சராசரி தீர்வு",
    case_trend: "வழக்கு போக்கு",
    time_interval: "கால இடைவெளி:",
    weekly: "வாராந்திர",
    monthly: "மாதாந்திர",
    yearly: "வருடாந்திர",
    vs_30_days: "கடந்த 30 நாட்களில்",
    cases_by_district: "மாவட்ட வாரியாக வழக்குகள்",
    investigation_calendar: "விசாரணை நாட்காட்டி",
    hearings: "விசாரணைகள்",
    shifts: "பணிகள்",
    cases_by_status: "நிலை வாரியாக வழக்குகள்",
    active: "செயலில் உள்ளது",
    under_investigation: "விசாரணையில் உள்ளது",
    closed: "முடிக்கப்பட்டது",
    // Calendar Events
    court_hearing: "நீதிமன்ற விசாரணை — FIR #4489",
    bail_review: "ஜாமீன் ஆய்வு — வழக்கு #4512",
    shift_handover: "பணி ஒப்படைப்பு — காலை",
    night_patrol: "இரவு ரோந்து விளக்கக்காட்சி",
    // Districts
    bengaluru_urban: "பெங்களூரு நகர்ப்புறம்",
    bengaluru_rural: "பெங்களூரு ஊரக",
    mysuru: "மைசூரு",
    mangalaru: "மங்களூரு",
    hubballi: "ஹூப்ளி",
    // Days/Periods
    days_label: "நாட்கள்",
    "0-30 days": "0-30 நாட்கள்",
    "31-60 days": "31-60 நாட்கள்",
    "61-90 days": "61-90 நாட்கள்",
    "91-180 days": "91-180 நாட்கள்",
    "180+ days": "180+ நாட்கள்",
    // Days
    Sun: "ஞாயிறு",
    Mon: "திங்கள்",
    Tue: "செவ்வாய்",
    Wed: "புதன்",
    Thu: "வியாழன்",
    Fri: "வெள்ளி",
    Sat: "சனி",

    // --- NEW COPILOT TRANSLATIONS ---
    analyzing: "ஆராய்கிறது...",
    ai_copilot: "AI copilot",
    hi_there: "வணக்கம் 👋",
    ask_copilot: "வழக்குகள், சந்தேக நபர்கள் அல்லது விசாரணைகள் பற்றி என்னிடம் எது வேண்டுமானாலும் கேளுங்கள்.",
    chat_history: "உரையாடல் வரலாறு",
    new_chat: "புதிய உரையாடல்",
    saved: "சேமிக்கப்பட்டது",
    today: "இன்று",
    yesterday: "நேற்று",
    ask_anything_placeholder: "என்னிடம் எதையும் கேளுங்கள்...",
    all_sources: "அனைத்து ஆதாரங்கள்",
    fir_database: "எஃப்.ஐ.ஆர் தரவுத்தளம்",
    suspects: "சந்தேக நபர்கள்",
    evidence: "ஆதாரம்",
    stations: "நிலையங்கள்",
    context: "சூழல்",
    referenced_sources: "குறிப்பிடப்பட்ட ஆதாரங்கள்",
    actions: "செயல்கள்",
    related_cases: "தொடர்புடைய வழக்குகள்",
    generate_report: "அறிக்கையை உருவாக்கு",
    export_conversation: "உரையாடலை ஏற்றுமதி செய்",
    save_to_case: "வழக்கில் சேமி",
    share_with_team: "குழுவுடன் பகிர்",
    robbery_indiranagar: "கொள்ளை — இந்திராநகர்",
    theft_koramangala: "களவு — கோரமங்களா",
    cyber_fraud_ecity: "சைபர் மோசடி — எலக்ட்ரானிக் சிட்டி",
    copilot_assistant_desc: "உங்கள் AI விசாரணை உதவியாளர் — கர்நாடகா காவல் நெறிமுறைகள், குற்றவியல் தரவுத்தளங்கள் மற்றும் சட்ட கட்டமைப்புகள் ஆகியவற்றில் பயிற்சி பெற்றவர்.",
    quick_tasks: "விரைவான பணிகள்",
    suggested_prompt: "பரிந்துரைக்கப்பட்ட கேள்வி",
    task_analyze_connections: "சந்தேக நபரின் இணைப்புகளை பகுப்பாய்வு செய்",
    task_generate_report: "விசாரணை அறிக்கையை உருவாக்கு",
    task_search_cross_district: "மாவட்டங்களுக்கு இடையேயான வழக்குகளைத் தேடு",
    suggested_prompt_text: "இந்த மாதம் பெங்களூரு மாவட்டம் முழுவதும் களவு வழக்குகளில் பொதுவான MO முறைகள் யாவை?",
    theft_malleshwaram: "களவு — மல்லேஸ்வரம், பெங்களூரு",
    suspect_linked_3_cases: "3 திறந்த வழக்குகளுடன் தொடர்புடையது",
    cctv_footage_main_road: "சிசிடிவி காட்சிகள் — முக்கிய சாலை",
    captured_at_215_am: "அதிகாலை 2:15 மணிக்கு எடுக்கப்பட்டது",
    malleshwaram_bengaluru: "மல்லேஸ்வரம், பெங்களூரு",
    crime_hotspot_zone: "குற்றங்கள் அதிகம் நடக்கும் பகுதி",

    // --- NEW GRAPH TRANSLATIONS ---
    all_connections: "அனைத்து இணைப்புகள்",
    criminal_network: "குற்றவியல் நெட்வொர்க்",
    gang_network: "கும்பல் நெட்வொர்க்",
    evidence_links: "ஆதார இணைப்புகள்",
    select_node: "ஒரு முனையைத் தேர்ந்தெடுக்கவும்",
    click_node_desc: "விவரங்களைக் காண வரைபடத்தில் உள்ள ஏதேனும் முனையை சொடுக்கவும்",
    risk: "அபாயம்",
    cases: "வழக்குகள்",
    connections: "இணைப்புகள்",
    view_full_profile: "முழு சுயவிவரத்தைக் காட்டு",
    add_to_investigation: "விசாரணையில் சேர்",
    // Graph Suspects
    ravi_kumar: "ரவி குமார்",
    deepak_reddy: "தீபக் ரெட்டி",
    mohammed_ali: "முகமது அலி",
    imran_khan: "இம்ரான் கான்",
    venkatesh_reddy: "வெங்கடேஷ் ரெட்டி",
    rajesh_sharma: "ராஜேஷ் சர்மா",
    // Graph Evidence/Node type labels
    cctv_4521: "சிசிடிவி #4521",
    phone_records: "தொலைபேசி பதிவுகள்",
    fingerprint: "கைரேகை",
    suspect: "சந்தேக நபர்",
    vehicle: "வாகனம்",
    phone: "தொலைபேசி",
    // Graph Edges
    accomplice: "கூட்டாளி",
    fence: "பெறுபவர் (வேலி)",
    operational_head: "செயல்பாட்டுத் தலைவர்",
    training: "பயிற்சி",
    logistics: "தளவாடங்கள்",
    cyber_ops: "சைபர் செயல்பாடுகள்",
    parts_dealer: "உதிரிபாகங்கள் வியாபாரி",
    identified: "அடையாளம் காணப்பட்டது",
    cell_tower: "செல் கோபுரம்",
    partial_print: "பகுதி கைரேகை",
    registered: "பதிவு செய்யப்பட்டது",
    used_in_crime: "குற்றத்தில் பயன்படுத்தப்பட்டது",
    primary: "முதன்மை",
    burner: "பர்னர்",
    shared: "பகிரப்பட்டது",

    // Chat History Titles
    fir_analysis_title: "எஃப்.ஐ.ஆர் #4521 பகுப்பாய்வு",
    suspect_network_title: "சந்தேக நபர் நெட்வொர்க் — ரவி குமார்",
    mo_pattern_title: "குற்றச் செயல் பாணி ஆராய்ச்சி",
    cross_district_title: "மாவட்டங்களுக்கு இடையேயான இணைப்பு",
    theft_pattern_title: "பெங்களூரு வடக்கு களவு பாணி",
    whisper_investigation_title: "விஸ்பர் எச்சரிக்கை விசாரணை",
    evidence_report_title: "ஆதார அறிக்கை தயாரித்தல்",
  },
  kn: {
    accept: "ಸ್ವೀಕರಿಸಿ",
    dismiss: "ಮುಂದುವರಿಕೆ",
    view: "ವೀಕ್ಷಿಸು",
    alert: "ಎಚ್ಚರಿಕೆ",
    priority: "ಪ್ರಾಮುಖ್ಯತೆಯ",
    status: "ಸ್ಥಿತಿ",
    alerts: "ಎಚ್ಚರಿಕೆಗಳು",
    alert_feed: "ಎಚ್ಚರಿಕಾ ಫೀಡ್",
    all_alerts: "ಎಲ್ಲಾ ಎಚ್ಚರಿಕೆಗಳು",
    new_alerts: "ಹೊಸ ಎಚ್ಚರಿಕೆಗಳು",
    pending: "ಬಾಕಿ ಉಳಿದಿರುವ",
    resolved: "ಪರಿಹರಿಸಲಾಗಿದೆ",
    total_alerts: "ಒಟ್ಟು ಎಚ್ಚರಿಕೆಗಳು",
    alerts_by_type: "ಮಾದರಿ ಪ್ರಕಾರ ಎಚ್ಚರಿಕೆಗಳು",
    recent_activity: "ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ",
    crime_heatmap: "ಅಪರಾಧ ಶಾಖನಕ್ಷೆ",
    whisper_alert: "ವಿಸ್ಪರ್ ಎಚ್ಚರಿಕೆ",
    fir_match: "ಎಫ್‌ಐಆರ್ ಹೋಲಿಕೆ",
    cross_district: "ಅಂತರ-ಜಿಲ್ಲಾ",
    evidence_link: "ಸಾಕ್ಷ್ಯ ಲಿಂಕ್",
    ai_notification: "AI ಅಧಿಸೂಚನೆ",
    intelligence_alerts: "ಗುಪ್ತಚರ ಎಚ್ಚರಿಕೆಗಳು",
    monitor_intel: "ಸಕ್ರಿಯ ಗುಪ್ತಚರವನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ ಮತ್ತು ಪ್ರತಿಕ್ರಿಯಿಸಿ",
    performance_summary: "ಎಚ್ಚರಿಕೆ ಕಾರ್ಯಕ್ಷಮತೆಯ ಸಾರಾಂಶ",
    pending_review: "ಪರಿಶೀಲನೆ ಬಾಕಿ ಇದೆ",
    alert_trend: "ಎಚ್ಚರಿಕೆ ಪ್ರವೃತ್ತಿ",
    alert_distribution: "ಎಚ್ಚರಿಕೆ ವಿತರಣೆ",
    total: "ಒಟ್ಟು",
    recent_alerts: "ಇತ್ತೀಚಿನ ಎಚ್ಚರಿಕೆಗಳು",
    more_details: "ಹೆಚ್ಚಿನ ವಿವರಗಳು",
    // Analytics & Charts Translation
    crime_breakdown: "ಅಪರಾಧ ಪ್ರಕಾರದ ವಿಭಜನೆ",
    cases_label: "ಪ್ರಕರಣಗಳು",
    cases_by_crime_type: "ಅಪರಾಧ ಪ್ರಕಾರದ ಪ್ರಕರಣಗಳು",
    todays_cases: "ಇಂದಿನ ಪ್ರಕರಣಗಳು",
    live: "ಲೈವ್",
    total_cases: "ಒಟ್ಟು ಪ್ರಕರಣಗಳು",
    theft: "ಕಳ್ಳತನ",
    fraud: "ವಂಚನೆ",
    cybercrime: "ಸೈಬರ್ ಅಪರಾಧ",
    assault: "ದಾಳಿ",
    other: "ಇತರೆ",
    top_districts: "ಉನ್ನತ ಜಿಲ್ಲೆಗಳು",
    by_case_count: "ಪ್ರಕರಣಗಳ ಸಂಖ್ಯೆಯ ಆಧಾರದ ಮೇಲೆ",
    case_resolution: "ಪ್ರಕರಣದ ಪರಿಹಾರ",
    by_time_period: "ಸಮಯದ ಅವಧಿಯ ಆಧಾರದ ಮೇಲೆ",
    total_resolved: "ಒಟ್ಟು ಪರಿಹರಿಸಲಾಗಿದೆ",
    avg_resolution: "ಸರಾಸರಿ ಪರಿಹಾರ ಸಮಯ",
    case_trend: "ಪ್ರಕರಣದ ಪ್ರವೃತ್ತಿ",
    time_interval: "ಸಮಯದ ಮಧ್ಯಂತರ:",
    weekly: "ವಾರದ",
    monthly: "ತಿಂಗಳ",
    yearly: "ವರ್ಷದ",
    vs_30_days: "ಕಳೆದ 30 ದಿನಗಳ ವಿರುದ್ಧ",
    cases_by_district: "ಜಿಲ್ಲಾವಾರು ಪ್ರಕರಣಗಳು",
    investigation_calendar: "ತನಿಖಾ ಕ್ಯಾಲೆಂಡರ್",
    hearings: "ವಿಚಾರಣೆಗಳು",
    shifts: "ಶಿಫ್ಟ್‌ಗಳು",
    cases_by_status: "ಸ್ಥಿತಿವಾರು ಪ್ರಕರಣಗಳು",
    active: "ಸಕ್ರಿಯ",
    under_investigation: "ತನಿಖೆಯಲ್ಲಿದೆ",
    closed: "ಮುಚ್ಚಲಾಗಿದೆ",
    // Calendar Events
    court_hearing: "ನ್ಯಾಯಾಲಯದ ವಿಚಾರಣೆ — FIR #4489",
    bail_review: "ಜಾಮೀನು ಪರಿಶೀಲನೆ — ಪ್ರಕರಣ #4512",
    shift_handover: "ಶಿಫ್ಟ್ ಹಸ್ತಾಂತರ — ಬೆಳಿಗ್ಗೆ",
    night_patrol: "ರಾತ್ರಿ ಗಸ್ತು ಮಾಹಿತಿ",
    // Districts
    bengaluru_urban: "ಬೆಂಗಳೂರು ನಗರ",
    bengaluru_rural: "ಬೆಂಗಳೂರು ಗ್ರಾಮಾಂತರ",
    mysuru: "ಮೈಸೂರು",
    mangalaru: "ಮಂಗಳೂರು",
    hubballi: "ಹುಬ್ಬಳ್ಳಿ",
    // Days/Periods
    days_label: "ದಿನಗಳು",
    "0-30 days": "0-30 ದಿನಗಳು",
    "31-60 days": "31-60 ದಿನಗಳು",
    "61-90 days": "61-90 ದಿನಗಳು",
    "91-180 days": "91-180 ದಿನಗಳು",
    "180+ days": "180+ ದಿನಗಳು",
    // Days
    Sun: "ಭಾನು",
    Mon: "ಸೋಮ",
    Tue: "ಮಂಗಳ",
    Wed: "ಬುಧ",
    Thu: "ಗುರು",
    Fri: "ಶುಕ್ರ",
    Sat: "ಶನಿ",

    // --- NEW COPILOT TRANSLATIONS ---
    analyzing: "ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
    ai_copilot: "AI ಕೊಪೈಲಟ್",
    hi_there: "ನಮಸ್ಕಾರ 👋",
    ask_copilot: "ಪ್ರಕರಣಗಳು, ಶಂಕಿತರು ಅಥವಾ ತನಿಖೆಗಳ ಬಗ್ಗೆ ನನ್ನನ್ನು ಏನಾದರೂ ಕೇಳಿ.",
    chat_history: "ಚಾಟ್ ಇತಿಹಾಸ",
    new_chat: "ಹೊಸ ಚಾಟ್",
    saved: "ಉಳಿಸಲಾಗಿದೆ",
    today: "ಇಂದು",
    yesterday: "ನಿನ್ನೆ",
    ask_anything_placeholder: "ನನ್ನನ್ನು ಏನಾದರೂ ಕೇಳಿ...",
    all_sources: "ಎಲ್ಲಾ ಮೂಲಗಳು",
    fir_database: "ಎಫ್‌ಐಆರ್ ಡೇಟಾಬೇಸ್",
    suspects: "ಶಂಕಿತರು",
    evidence: "ಸಾಕ್ಷ್ಯಗಳು",
    stations: "ಠಾಣೆಗಳು",
    context: "ಸಂದರ್ಭ",
    referenced_sources: "ಉಲ್ಲೇಖಿತ ಮೂಲಗಳು",
    actions: "ಕ್ರಮಗಳು",
    related_cases: "ಸಂಬಂಧಿತ ಪ್ರಕರಣಗಳು",
    generate_report: "ವರದಿ ರಚಿಸಿ",
    export_conversation: "ಚಾಟ್ ರಫ್ತು ಮಾಡಿ",
    save_to_case: "ಪ್ರಕರಣಕ್ಕೆ ಉಳಿಸಿ",
    share_with_team: "ತಂಡದೊಂದಿಗೆ ಹಂಚಿಕೊಳ್ಳಿ",
    robbery_indiranagar: "ದರೋಡೆ — ಇಂದಿರಾನಗರ",
    theft_koramangala: "ಕಳ್ಳತನ — ಕೋರಮಂಗಲ",
    cyber_fraud_ecity: "ಸೈಬರ್ ವಂಚನೆ — ಎಲೆಕ್ಟ್ರಾನಿಕ್ ಸಿಟಿ",
    copilot_assistant_desc: "ನಿಮ್ಮ AI ತನಿಖಾ ಸಹಾಯಕಿ — ಕರ್ನಾಟಕ ಪೊಲೀಸ್ ಪ್ರೋಟೋಕಾಲ್ಗಳು, ಅಪರಾಧ ಡೇಟಾಬೇಸ್ಗಳು ಮತ್ತು ಕಾನೂನು ಚೌಕಟ್ಟುಗಳ ಕುರಿತು ತರಬೇತಿ ಪಡೆದಿದೆ.",
    quick_tasks: "ತ್ವರಿತ ಕಾರ್ಯಗಳು",
    suggested_prompt: "ಸೂಚಿಸಲಾದ ಪ್ರಾಂಪ್ಟ್",
    task_analyze_connections: "ಶಂಕಿತರ ಸಂಪರ್ಕಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಿ",
    task_generate_report: "ತನಿಖಾ ವರದಿ ರಚಿಸಿ",
    task_search_cross_district: "ಅಂತರ-ಜಿಲ್ಲಾ ಪ್ರಕರಣಗಳನ್ನು ಹುಡುಕಿ",
    suggested_prompt_text: "ಈ ತಿಂಗಳು ಬೆಂಗಳೂರು ಜಿಲ್ಲೆಯಾದ್ಯಂತ ಕಳ್ಳತನ ಪ್ರಕರಣಗಳಲ್ಲಿನ ಸಾಮಾನ್ಯ MO ಮಾದರಿಗಳು ಯಾವುವು?",
    theft_malleshwaram: "ಕಳ್ಳತನ — ಮಲ್ಲೇಶ್ವರಂ, ಬೆಂಗಳೂರು",
    suspect_linked_3_cases: "3 ಬಾಕಿ ಪ್ರಕರಣಗಳಿಗೆ ಸಂಬಂಧಿಸಿದೆ",
    cctv_footage_main_road: "CCTV ದೃಶ್ಯಾವಳಿ — ಮುಖ್ಯ ರಸ್ತೆ",
    captured_at_215_am: "ಮುಂಜಾನೆ 2:15 ಕ್ಕೆ ಸೆರೆಹಿಡಿಯಲಾಗಿದೆ",
    malleshwaram_bengaluru: "ಮಲ್ಲೇಶ್ವರಂ, ಬೆಂಗಳೂರು",
    crime_hotspot_zone: "ಅಪರಾಧ ಸೂಕ್ಷ್ಮ ವಲಯ",

    // --- NEW GRAPH TRANSLATIONS ---
    all_connections: "ಎಲ್ಲಾ ಸಂಪರ್ಕಗಳು",
    criminal_network: "ಅಪರಾಧ ಜಾಲ",
    gang_network: "ಗ್ಯಾಂಗ್ ಜಾಲ",
    evidence_links: "ಸಾಕ್ಷ್ಯ ಲಿಂಕ್‌ಗಳು",
    select_node: "ನೋಡ್ ಆಯ್ಕೆಮಾಡಿ",
    click_node_desc: "ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಲು ಗ್ರಾಫ್‌ನಲ್ಲಿನ ಯಾವುದೇ ನೋಡ್ ಅನ್ನು ಕ್ಲಿಕ್ ಮಾಡಿ",
    risk: "ಅಪಾಯ",
    cases: "ಪ್ರಕರಣಗಳು",
    connections: "ಸಂಪರ್ಕಗಳು",
    view_full_profile: "ಪೂರ್ಣ ಪ್ರೊಫೈಲ್ ವೀಕ್ಷಿಸಿ",
    add_to_investigation: "ತನಿಖೆಗೆ ಸೇರಿಸಿ",
    // Graph Suspects
    ravi_kumar: "ರವಿ ಕುಮಾರ್",
    deepak_reddy: "ದೀಪಕ್ ರೆಡ್ಡಿ",
    mohammed_ali: "ಮೊಹಮ್ಮದ್ ಅಲಿ",
    imran_khan: "ಇಮ್ರಾನ್ ಖಾನ್",
    venkatesh_reddy: "ವೆಂಕಟೇಶ್ ರೆಡ್ಡಿ",
    rajesh_sharma: "ರಾಜೇಶ್ ಶರ್ಮಾ",
    // Graph Evidence/Node type labels
    cctv_4521: "ಸಿಸಿಟಿವಿ #4521",
    phone_records: "ದೂರವಾಣಿ ದಾಖಲೆಗಳು",
    fingerprint: "ಬೆರಳಚ್ಚು",
    suspect: "ಶಂಕಿತ",
    vehicle: "ವಾಹನ",
    phone: "ದೂರವಾಣಿ",
    // Graph Edges
    accomplice: "ಸಹಚರ",
    fence: "ಫೆನ್ಸ್",
    operational_head: "ಕಾರ್ಯಾಚರಣೆ ಮುಖ್ಯಸ್ಥ",
    training: "ತರಬೇತಿ",
    logistics: "ಸಾಗಣೆ ಮತ್ತು ವ್ಯವಸ್ಥೆ",
    cyber_ops: "ಸೈಬರ್ ಕಾರ್ಯಾಚರಣೆಗಳು",
    parts_dealer: "ಭಾಗಗಳ ವ್ಯಾಪಾರಿ",
    identified: "ಗುರುತಿಸಲಾಗಿದೆ",
    cell_tower: "ಸೆಲ್ ಟವರ್",
    partial_print: "ಅರೆ ಬೆರಳಚ್ಚು",
    registered: "ನೋಂದಾಯಿಸಲಾಗಿದೆ",
    used_in_crime: "ಅಪರಾಧದಲ್ಲಿ ಬಳಸಲಾಗಿದೆ",
    primary: "ಪ್ರಾಥಮಿಕ",
    burner: "ಬರ್ನರ್",
    shared: "ಹಂಚಿಕೊಳ್ಳಲಾಗಿದೆ",

    // Chat History Titles
    fir_analysis_title: "ಎಫ್‌ಐಆರ್ #4521 ವಿಶ್ಲೇಷಣೆ",
    suspect_network_title: "ಶಂಕಿತರ ಜಾಲ — ರವಿ ಕುಮಾರ್",
    mo_pattern_title: "ಎಂ.ಓ ವಿಧಾನ ಸಂಶೋಧನೆ",
    cross_district_title: "ಅಂತರ-ಜಿಲ್ಲಾ ಪ್ರಕರಣ ಸಂಯೋಜನೆ",
    theft_pattern_title: "ಬೆಂಗಳೂರು ಉತ್ತರ ಕಳ್ಳತನ ಮಾದರಿ",
    whisper_investigation_title: "ವಿಸ್ಪರ್ ಎಚ್ಚರಿಕೆ ತನಿಖೆ",
    evidence_report_title: "ಸಾಕ್ಷ್ಯಾಧಾರ ವರದಿ ಸಿದ್ಧತೆ",
  },
  te: {
    accept: "అంగీకరించండి",
    dismiss: "నిరాకరించండి",
    view: "వీక్షించండి",
    alert: "అలర్ట్",
    priority: "ప్రాధాన్యత",
    status: "స్థితి",
    alerts: "అలర్ట్స్",
    alert_feed: "అలర్ట్ ఫీడ్",
    all_alerts: "అన్ని అలర్ట్స్",
    new_alerts: "కొత్త అలర్ట్స్",
    pending: "పెండింగ్",
    resolved: "పరిష్కరించబడింది",
    total_alerts: "మొత్తం అలర్ట్స్",
    alerts_by_type: "రకం ఆధారంగా అలర్ట్స్",
    recent_activity: "ఇటీవలి కార్యాచరణ",
    crime_heatmap: "క్రైమ్ హీట్‌మ్యాప్",
    whisper_alert: "విస్పర్ అలర్ట్",
    fir_match: "FIR సరిపోలిక",
    cross_district: "క్రాస్-డిస్ట్రిక్ట్",
    evidence_link: "ఆధారాల లింక్",
    ai_notification: "AI నోటిఫికేషన్",
    intelligence_alerts: "ఇంటెలిజెన్స్ అలర్ట్స్",
    monitor_intel: "క్రియాశీల ఇంటెలిజెన్స్‌ను పర్యవేక్షించండి మరియు స్పందించండి",
    performance_summary: "అలర్ట్ పనితీరు సారాంశం",
    pending_review: "ಸಮೀಕ್ಷೆ ಪೆಂಡಿಂಗ್",
    alert_trend: "అలర్ట్ ట్రెండ్",
    alert_distribution: "అలర్ట్ పంపిణీ",
    total: "మొత్తం",
    recent_alerts: "ఇటీవలి అలర్ట్స్",
    more_details: "మరిన్ని వివరాలు",
    // Analytics & Charts Translation
    crime_breakdown: "నేర రకం విభజన",
    cases_label: "కేసులు",
    cases_by_crime_type: "నేర రకం ఆధారంగా కేసులు",
    todays_cases: "నేటి కేసులు",
    live: "లైవ్",
    total_cases: "మొత్తం కేసులు",
    theft: "దొంగతనం",
    fraud: "మోసం",
    cybercrime: "సైబర్ నేరం",
    assault: "దాడి",
    other: "ఇతర",
    top_districts: "అగ్ర జిల్లాలు",
    by_case_count: "కేసుల సంఖ్య ఆధారంగా",
    case_resolution: "కేసు పరిష్కారం",
    by_time_period: "సమయ వ్యవధి ఆధారంగా",
    total_resolved: "మొత్తం పరిష్కరించబడింది",
    avg_resolution: "సగటు పరిష్కారం",
    case_trend: "కేసు ట్రెండ్",
    time_interval: "సమయ వ్యవధి:",
    weekly: "వారానికి ఒకసారి",
    monthly: "నెలవారీ",
    yearly: "వార్షిక",
    vs_30_days: "గత 30 రోజులతో పోలిస్తే",
    cases_by_district: "జిల్లా వారీగా కేసులు",
    investigation_calendar: "విచారణ క్యాలెండర్",
    hearings: "విచారణలు",
    shifts: "షిఫ్ట్‌లు",
    cases_by_status: "స్థితి ఆధారంగా కేసులు",
    active: "క్రియాశీల",
    under_investigation: "విచారణలో ఉంది",
    closed: "మూసివేయబడింది",
    // Calendar Events
    court_hearing: "కోర్టు విచారణ — FIR #4489",
    bail_review: "బెయిల్ సమీక్ష — కేసు #4512",
    shift_handover: "షిఫ్ట్ అప్పగింత — ఉదయం",
    night_patrol: "నైట్ పెట్రోల్ బ్రీఫింగ్",
    // Districts
    bengaluru_urban: "బెంగళూరు అర్బన్",
    bengaluru_rural: "బెంగళూరు రూరల్",
    mysuru: "మైసూర్",
    mangalaru: "మంగళూరు",
    hubballi: "హుబ్లీ",
    // Days/Periods
    days_label: "రోజులు",
    "0-30 days": "0-30 రోజులు",
    "31-60 days": "31-60 రోజులు",
    "61-90 days": "61-90 రోజులు",
    "91-180 days": "91-180 రోజులు",
    "180+ days": "180+ రోజులు",
    // Days
    Sun: "ఆది",
    Mon: "సోమ",
    Tue: "మంగళ",
    Wed: "बुధ",
    Thu: "గురు",
    Fri: "శుక్ర",
    Sat: "శని",

    // --- NEW COPILOT TRANSLATIONS ---
    analyzing: "విశ్లేషిస్తోంది...",
    ai_copilot: "AI కోపైలట్",
    hi_there: "హలో 👋",
    ask_copilot: "కేసులు, అనుమానితులు లేదా విచారణల గురించి నన్ను ఏదైనా అడగండి.",
    chat_history: "చాట్ చరిత్ర",
    new_chat: "కొత్త చాట్",
    saved: "సేవ్ చేయబడింది",
    today: "నేడు",
    yesterday: "నిన్న",
    ask_anything_placeholder: "నన్ను ఏదైనా అడగండి...",
    all_sources: "అన్ని మూలాధారాలు",
    fir_database: "FIR డేటాబేస్",
    suspects: "అనుమానితులు",
    evidence: "ఆధారాలు",
    stations: "స్టేషన్లు",
    context: "సందర్భం",
    referenced_sources: "సూచించిన మూలాధారాలు",
    actions: "చర్యలు",
    related_cases: "సంబంధిత కేసులు",
    generate_report: "నివేదికను రూపొందించు",
    export_conversation: "సంభాషణను ఎగుమతి చేయి",
    save_to_case: "కేసుకు సేవ్ చేయి",
    share_with_team: "బృందంతో పంచుకోండి",
    robbery_indiranagar: "దోపిడీ — ఇందిరానగర్",
    theft_koramangala: "దొంగతనం — కోరమంగళ",
    cyber_fraud_ecity: "సైబర్ మోసం — ఎలక్ట్రానిక్ సిటీ",
    copilot_assistant_desc: "మీ AI విచారణ సహాయకుడు — కర్ణాటక పోలీసు ప్రోటోకాల్‌లు, నేర డేటాబేస్‌లు మరియు చట్టపరమైన ఫ్రేమ్‌వర్క్‌లపై శిక్షణ పొందారు.",
    quick_tasks: "శీఘ్ర పనులు",
    suggested_prompt: "సూచించిన ప్రాంప్ట్",
    task_analyze_connections: "అనుమానితుల కనెక్షన్లను విశ్లేషించు",
    task_generate_report: "విచారణ నివేదికను రూపొందించు",
    task_search_cross_district: "క్రాస్-డిస్ట్రిక్ట్ కేసులను శోధించు",
    suggested_prompt_text: "ఈ నెల బెంగళూరు జిల్లా వ్యాప్తంగా దొంగతనం కేసుల్లో సాధారణ MO నమూనాలు ఏమిటి?",
    theft_malleshwaram: "దొంగతనం — మల్లేశ్వరం, బెంగళూరు",
    suspect_linked_3_cases: "3 ఓపెన్ కేసులతో ముడిపడి ఉంది",
    cctv_footage_main_road: "CCTV ఫుటేజ్ — మెయిన్ రోడ్",
    captured_at_215_am: "ఉదయం 2:15 గంటలకు రికార్డ్ చేయబడింది",
    malleshwaram_bengaluru: "మల్లేశ్వరం, బెంగళూరు",
    crime_hotspot_zone: "క్రైమ్ హాట్‌స్పాట్ జోన్",

    // --- NEW GRAPH TRANSLATIONS ---
    all_connections: "అన్ని కనెక్షన్లు",
    criminal_network: "నేర నెట్‌వర్క్",
    gang_network: "గ్యాంగ్ నెట్‌వర్క్",
    evidence_links: "ఆధారాల లింకులు",
    select_node: "ఒక నోడ్ ఎంచుకోండి",
    click_node_desc: "వివరాలను వీక్షించడానికి గ్రాఫ్‌లోని ఏదైనా నోడ్‌పై క్లిక్ చేయండి",
    risk: "ప్రమాదం",
    cases: "కేసులు",
    connections: "కనెక్షన్లు",
    view_full_profile: "పూర్తి ప్రొఫైల్ వీక్షించండి",
    add_to_investigation: "విచారణకు జోడించండి",
    // Graph Suspects
    ravi_kumar: "రవి కుమార్",
    deepak_reddy: "దీపక్ రెడ్డి",
    mohammed_ali: "మహమ్మద్ అలీ",
    imran_khan: "ఇమ్రాన్ ఖాన్",
    venkatesh_reddy: "వెంకటేష్ రెడ్డి",
    rajesh_sharma: "రాజేష్ శర్మ",
    // Graph Evidence/Node type labels
    cctv_4521: "CCTV #4521",
    phone_records: "ఫోన్ రికార్డులు",
    fingerprint: "వేలిముద్ర",
    suspect: "అనుమానితుడు",
    vehicle: "వాహనం",
    phone: "ఫోన్",
    // Graph Edges
    accomplice: "సహచరుడు",
    fence: "ఫెన్స్",
    operational_head: "కార్యాచరణ అధిపతి",
    training: "శిక్షణ",
    logistics: "లాజిస్టిక్స్",
    cyber_ops: "సైబర్ ఆప్స్",
    parts_dealer: "విడిభాగాల డీలర్",
    identified: "గుర్తించబడింది",
    cell_tower: "సెల్ టవర్",
    partial_print: "పాక్షిక వేలిముద్ర",
    registered: "నమోదైంది",
    used_in_crime: "నేరంలో ఉపయోగించబడింది",
    primary: "ప్రాథమిక",
    burner: "బర్నర్",
    shared: "భాగస్వామ్యం చేయబడింది",

    // Chat History Titles
    fir_analysis_title: "FIR #4521 విశ్లేషణ",
    suspect_network_title: "అనుమానితుల నెట్‌వర్క్ — రవి కుమార్",
    mo_pattern_title: "MO పద్ధతి పరిశోధన",
    cross_district_title: "క్రాస్-డిస్ట్రిక్ట్ కేసు లింకింగ్",
    theft_pattern_title: "బెంగళూరు నార్త్ దొంగతనం నమూనా",
    whisper_investigation_title: "విస్పర్ అలర్ట్ విచారణ",
    evidence_report_title: "సాక్ష్యాల నివేదిక రూపకల్పన",
  },
  hi: {
    accept: "स्वीकार करें",
    dismiss: "अस्वीकार",
    view: "देखें",
    alert: "अलर्ट",
    priority: "प्राथमिकता",
    status: "स्थिति",
    alerts: "अलर्ट्स",
    alert_feed: "अलर्ट फ़ीड",
    all_alerts: "सभी अलर्ट्स",
    new_alerts: "नए अलर्ट्स",
    pending: "लंबित",
    resolved: "हल किया गया",
    total_alerts: "कुल अलर्ट्स",
    alerts_by_type: "प्रकार के आधार पर अलर्ट्स",
    recent_activity: "हाल की गतिविधि",
    crime_heatmap: "अपराध हीटमैप",
    whisper_alert: "व्हिस्पर अलर्ट",
    fir_match: "एफआईआर मिलान",
    cross_district: "क्रॉस-डिस्ट्रिक्ट",
    evidence_link: "साक्ष्य लिंक",
    ai_notification: "एआई अधिसूचना",
    intelligence_alerts: "खुफिया अलर्ट",
    monitor_intel: "सक्रिय खुफिया जानकारी की निगरानी करें और प्रतिक्रिया दें",
    performance_summary: "अलर्ट प्रदर्शन सारांश",
    pending_review: "समीक्षा लंबित",
    alert_trend: "अलर्ट ट्रेंड",
    alert_distribution: "अलर्ट वितरण",
    total: "कुल",
    recent_alerts: "हाल के अलर्ट",
    more_details: "अधिक विवरण",
    // Analytics & Charts Translation
    crime_breakdown: "अपराध प्रकार का विवरण",
    cases_label: "मामले",
    cases_by_crime_type: "अपराध प्रकार के अनुसार मामले",
    todays_cases: "आज के मामले",
    live: "लाइव",
    total_cases: "कुल मामले",
    theft: "चोरी",
    fraud: "धोखाधड़ी",
    cybercrime: "साइबर अपराध",
    assault: "हमला",
    other: "अन्य",
    top_districts: "शीर्ष जिले",
    by_case_count: "मामलों की संख्या के अनुसार",
    case_resolution: "मामले का समाधान",
    by_time_period: "समय अवधि के अनुसार",
    total_resolved: "कुल हल किए गए",
    avg_resolution: "औसत समाधान",
    case_trend: "मामले का ट्रेंड",
    time_interval: "समय अंतराल:",
    weekly: "साप्ताहिक",
    monthly: "मासिक",
    yearly: "वार्षिक",
    vs_30_days: "पिछले 30 दिनों की तुलना में",
    cases_by_district: "जिले के अनुसार मामले",
    investigation_calendar: "जांच कैलेंडर",
    hearings: "सुनवाई",
    shifts: "पालियों",
    cases_by_status: "स्थिति के अनुसार मामले",
    active: "सक्रिय",
    under_investigation: "जांच के अधीन",
    closed: "बंद",
    // Calendar Events
    court_hearing: "कोर्ट सुनवाई — FIR #4489",
    bail_review: "जमानत समीक्षा — केस #4512",
    shift_handover: "शिफ्ट हैंडओवर — सुबह",
    night_patrol: "रात्रि गश्त ब्रीफिंग",
    // Districts
    bengaluru_urban: "बेंगलुरु शहरी",
    bengaluru_rural: "बेंगलुरु ग्रामीण",
    mysuru: "मैसूरु",
    mangalaru: "मंगलुरु",
    hubballi: "हुबली",
    // Days/Periods
    days_label: "दिन",
    "0-30 days": "0-30 दिन",
    "31-60 days": "31-60 दिन",
    "61-90 days": "61-90 दिन",
    "91-180 days": "91-180 दिन",
    "180+ days": "180+ दिन",
    // Days
    Sun: "रवि",
    Mon: "सोम",
    Tue: "मंगल",
    Wed: "बुध",
    Thu: "गुरु",
    Fri: "शुक्र",
    Sat: "शनि",

    // --- NEW COPILOT TRANSLATIONS ---
    analyzing: "विश्लेषण किया जा रहा है...",
    ai_copilot: "एआई कोपायलट",
    hi_there: "नमस्ते 👋",
    ask_copilot: "मुझसे मामलों, संदिग्धों या जांच के बारे में कुछ भी पूछें।",
    chat_history: "चैट इतिहास",
    new_chat: "नया चैट",
    saved: "सहेजे गए",
    today: "आज",
    yesterday: "कल",
    ask_anything_placeholder: "मुझसे कुछ भी पूछें...",
    all_sources: "सभी स्रोत",
    fir_database: "एफआईआर डेटाबेस",
    suspects: "संदिग्ध",
    evidence: "साक्ष्य",
    stations: "थाने",
    context: "संदर्भ",
    referenced_sources: "संदर्भित स्रोत",
    actions: "कार्रवाई",
    related_cases: "संबंधित मामले",
    generate_report: "रिपोर्ट जनरेट करें",
    export_conversation: "बातचीत निर्यात करें",
    save_to_case: "केस में सहेजें",
    share_with_team: "टीम के साथ साझा करें",
    robbery_indiranagar: "डकैती — इंदिरा नगर",
    theft_koramangala: "चोरी — कोरमंगला",
    cyber_fraud_ecity: "साइबर धोखाधड़ी — इलेक्ट्रॉनिक सिटी",
    copilot_assistant_desc: "आपका एआई जांच सहायक — कर्नाटक पुलिस प्रोटोकॉल, आपराधिक डेटाबेस और कानूनी ढांचे पर प्रशिक्षित।",
    quick_tasks: "त्वरित कार्य",
    suggested_prompt: "सुझाया गया संकेत",
    task_analyze_connections: "संदिग्ध कनेक्शन का विश्लेषण करें",
    task_generate_report: "जांच रिपोर्ट जनरेट करें",
    task_search_cross_district: "क्रॉस-डिस्ट्रिक्ट मामलों की खोज करें",
    suggested_prompt_text: "इस महीने बेंगलुरु जिले में चोरी के मामलों में सामान्य एमओ पैटर्न क्या हैं?",
    theft_malleshwaram: "चोरी — मल्लेश्वरम, बेंगलुरु",
    suspect_linked_3_cases: "3 लंबित मामलों से जुड़ा हुआ है",
    cctv_footage_main_road: "सीसीटीवी फुटेज — मुख्य सड़क",
    captured_at_215_am: "सुबह 2:15 बजे कैप्चर किया गया",
    malleshwaram_bengaluru: "मल्लेश्वरम, बेंगलुरु",
    crime_hotspot_zone: "अपराध हॉटस्पॉट क्षेत्र",

    // --- NEW GRAPH TRANSLATIONS ---
    all_connections: "सभी कनेक्शन",
    criminal_network: "अपराधिक नेटवर्क",
    gang_network: "गैंग नेटवर्क",
    evidence_links: "साक्ष्य लिंक",
    select_node: "एक नोड चुनें",
    click_node_desc: "विवरण देखने के लिए ग्राफ़ में किसी भी नोड पर क्लिक करें",
    risk: "जोखिम",
    cases: "मामले",
    connections: "कनेक्शन",
    view_full_profile: "पूरा प्रोफाइल देखें",
    add_to_investigation: "जांच में जोड़ें",
    // Graph Suspects
    ravi_kumar: "रवि कुमार",
    deepak_reddy: "दीपक रेड्डी",
    mohammed_ali: "मोहम्मद अली",
    imran_khan: "इमरान खान",
    venkatesh_reddy: "वेंकटेश रेड्डी",
    rajesh_sharma: "राजेश शर्मा",
    // Graph Evidence/Node type labels
    cctv_4521: "सीसीटीवी #4521",
    phone_records: "फ़ोन रिकॉर्ड",
    fingerprint: "उंगली की छाप",
    suspect: "संदिग्ध",
    vehicle: "वाहन",
    phone: "फ़ोन",
    // Graph Edges
    accomplice: "सहयोगी",
    fence: "सौदागर (फेंस)",
    operational_head: "परिचालन प्रमुख",
    training: "प्रशिक्षण",
    logistics: "रसद (लॉजिस्टिक्स)",
    cyber_ops: "साइबर ऑप्स",
    parts_dealer: "पुर्जा विक्रेता",
    identified: "पहचाना गया",
    cell_tower: "सेल टॉवर",
    partial_print: "आंशिक छाप",
    registered: "पंजीकृत",
    used_in_crime: "अपराध में प्रयुक्त",
    primary: "प्राथमिक",
    burner: "बर्नर",
    shared: "साझा",

    // Chat History Titles
    fir_analysis_title: "एफआईआर #4521 विश्लेषण",
    suspect_network_title: "संदिग्ध नेटवर्क — रवि कुमार",
    mo_pattern_title: "कार्यप्रणाली (MO) अनुसंधान",
    cross_district_title: "क्रॉस-डिस्ट्रिक्ट केस लिंकिंग",
    theft_pattern_title: "बेंगलुरु उत्तर चोरी पैटर्न",
    whisper_investigation_title: "व्हिस्पर अलर्ट जांच",
    evidence_report_title: "साक्ष्य रिपोर्ट तैयार करना",
  },
};

/**
 * Translate a key based on the provided language code.
 * @param {string} key - The translation key.
 * @param {string} [lang='en'] - Language code (en, ta, kn, te, hi).
 * @returns {string} Translated string or the key if missing.
 */
export function t(key, lang = "en") {
  const langDict = translations[lang] || translations.en;
  return langDict[key] || key;
}

// Helper to translate alert type labels dynamically
export function translateAlertType(type, lang = "en") {
  const mapping = {
    whisper: "whisper_alert",
    "fir-match": "fir_match",
    "cross-district": "cross_district",
    evidence: "evidence_link",
    ai: "ai_notification",
  };
  const key = mapping[type];
  return key ? t(key, lang) : type;
}

// Helper to translate crime type labels dynamically
export function translateCrimeType(type, lang = "en") {
  const mapping = {
    theft: "theft",
    Theft: "theft",
    fraud: "fraud",
    Fraud: "fraud",
    cybercrime: "cybercrime",
    Cybercrime: "cybercrime",
    assault: "assault",
    Assault: "assault",
    other: "other",
    Other: "other",
  };
  const key = mapping[type];
  return key ? t(key, lang) : type;
}

// Helper to translate district names dynamically
export function translateDistrictName(name, lang = "en") {
  const mapping = {
    "Bengaluru Urban": "bengaluru_urban",
    "Bengaluru Rural": "bengaluru_rural",
    "Mysuru": "mysuru",
    "Mangaluru": "mangalaru",
    "Hubballi": "hubballi",
    "Other": "other",
  };
  const key = mapping[name];
  return key ? t(key, lang) : name;
}

// Helper to translate calendar days
export function translateCalendarDay(day, lang = "en") {
  const mapping = {
    Sun: "Sun",
    Mon: "Mon",
    Tue: "Tue",
    Wed: "Wed",
    Thu: "Thu",
    Fri: "Fri",
    Sat: "Sat",
  };
  const key = mapping[day];
  return key ? t(key, lang) : day;
}

// Helper to translate calendar event titles dynamically
export function translateCalendarEvent(title, lang = "en") {
  const mapping = {
    "Court Hearing — FIR #4489": "court_hearing",
    "Bail Review — Case #4512": "bail_review",
    "Shift Handover — Morning": "shift_handover",
    "Night Patrol Briefing": "night_patrol",
  };
  const key = mapping[title];
  return key ? t(key, lang) : title;
}

// Helper to translate cases status dynamically
export function translateStatus(status, lang = "en") {
  const mapping = {
    "Active": "active",
    "Pending Review": "pending_review",
    "Under Investigation": "under_investigation",
    "Closed": "closed",
  };
  const key = mapping[status];
  return key ? t(key, lang) : status;
}

// Helper to translate Node Labels in Knowledge Graph
export function translateNodeLabel(label, lang = "en") {
  const mapping = {
    "Ravi Kumar": "ravi_kumar",
    "Deepak Reddy": "deepak_reddy",
    "Mohammed Ali": "mohammed_ali",
    "Imran Khan": "imran_khan",
    "Venkatesh Reddy": "venkatesh_reddy",
    "Rajesh Sharma": "rajesh_sharma",
    "CCTV #4521": "cctv_4521",
    "Phone Records": "phone_records",
    "Fingerprint": "fingerprint",
  };
  const key = mapping[label];
  return key ? t(key, lang) : label;
}

// Helper to translate Edge Labels in Knowledge Graph
export function translateEdgeLabel(label, lang = "en") {
  const trimmed = label ? label.trim() : "";
  const mapping = {
    "Operational Head": "operational_head",
    "Training": "training",
    "Logistics": "logistics",
    "Cyber Ops": "cyber_ops",
    "Parts Dealer": "parts_dealer",
    "Identified": "identified",
    "Cell tower": "cell_tower",
    "Partial print": "partial_print",
    "Registered": "registered",
    "Used in crime": "used_in_crime",
    "Primary": "primary",
    "burner": "burner",
    "Shared": "shared",
  };
  const key = mapping[trimmed];
  return key ? t(key, lang) : label;
}

// Helper to translate Chat History Item Titles
export function translateChatTitle(title, lang = "en") {
  const mapping = {
    "FIR #4521 Analysis": "fir_analysis_title",
    "Suspect Network — Ravi Kumar": "suspect_network_title",
    "MO Pattern Research": "mo_pattern_title",
    "Cross-district case linking": "cross_district_title",
    "Theft pattern Bengaluru North": "theft_pattern_title",
    "Whisper alert investigation": "whisper_investigation_title",
    "Evidence report generation": "evidence_report_title",
  };
  const key = mapping[title];
  return key ? t(key, lang) : title;
}

// Export list of supported languages for UI selectors
export const supportedLanguages = ["en", "ta", "kn", "te", "hi"];
