// Simple translation utility for CrimeMatrix UI
// Languages: en (English), ta (Tamil), kn (Kannada), te (Telugu), hi (Hindi)

const translations = {
  en: {
    accept: "Accept",
    dismiss: "Dismiss",
    view: "View",
    alert: "Alert",
    priority: "Priority",
    status: "Status",
    alerts: "alerts",
    alert_feed: "Alert Feed",
    all_alerts: "All Alerts",
    new_alerts: "New Alerts",
    pending: "Pending",
    resolved: "Resolved",
    total_alerts: "Total Alerts",
    alerts_by_type: "Alerts by Type",
    recent_activity: "Recent Activity",
    crime_heatmap: "Crime Heatmap",
    whisper_alert: "Whisper Alert",
    fir_match: "FIR Match",
    cross_district: "Cross-District",
    evidence_link: "Evidence Link",
    ai_notification: "AI Notification",
    intelligence_alerts: "Intelligence Alerts",
    monitor_intel: "Monitor and respond to proactive intelligence",
    performance_summary: "Alert Performance Summary",
    pending_review: "Pending Review",
    alert_trend: "Alert Trend",
    alert_distribution: "Alert Distribution",
    total: "Total",
    recent_alerts: "Recent Alerts",
    more_details: "More details",
  },
  ta: {
    accept: "ஒப்புக்கொள்",
    dismiss: "நிராகரி",
    view: "பார்",
    alert: "எச்சரிக்கை",
    priority: "முன்னுரிமை",
    status: "நிலை",
    alerts: "அவசரங்கள்",
    alert_feed: "அவசரப் புலம்",
    all_alerts: "அனைத்து எச்சரிக்கைகள்",
    new_alerts: "புதிய எச்சரிக்கைகள்",
    pending: "நிலுவையில் உள்ளது",
    resolved: "தீர்க்கப்பட்டது",
    total_alerts: "மொத்த எச்சரிக்கைகள்",
    alerts_by_type: "வகை வாரியாக எச்சரிக்கைகள்",
    recent_activity: "சமீபத்திய நடவடிக்கை",
    crime_heatmap: "குற்ற வெப்ப வரைபடம்",
    whisper_alert: "விஸ்பர் எச்சரிக்கை",
    fir_match: "எஃப்.ஐ.ஆர் பொருத்தம்",
    cross_district: "மாவட்டங்களுக்கு இடையேயான",
    evidence_link: "ஆதார இணைப்பு",
    ai_notification: "செயற்கை நுண்ணறிவு அறிவிப்பு",
    intelligence_alerts: "உளவுத்துறை எச்சரிக்கைகள்",
    monitor_intel: "செயலில் உள்ள உளவுத்துறையை கண்காணித்து பதிலளிக்கவும்",
    performance_summary: "எச்சரிக்கை செயல்திறன் சுருக்கம்",
    pending_review: "மதிப்பாய்வு நிலுவையில் உள்ளது",
    alert_trend: "எச்சரிக்கை போக்கு",
    alert_distribution: "எச்சரிக்கை விநியோகம்",
    total: "மொத்தம்",
    recent_alerts: "சமீபத்திய எச்சரிக்கைகள்",
    more_details: "கூடுதல் விவரங்கள்",
  },
  kn: {
    accept: "ಸ್ವೀಕರಿಸಿ",
    dismiss: "ಮುಂದುವರಿಕೆ",
    view: "ವೀಕ್ಷಿಸು",
    alert: "ಎಚ್ಚರಿಕೆ",
    priority: "ಪ್ರಾಮುಖ್ಯತೆಯ",
    status: "ಸ್ಥಿತಿ",
    alerts: "ಎಚ್ಚರಿಕೆಗಳು",
    alert_feed: "ಎಚ್ಚರಿಕಾ ಫೀಡ್",
    all_alerts: "ಎಲ್ಲಾ ಎಚ್ಚರಿಕೆಗಳು",
    new_alerts: "ಹೊಸ ಎಚ್ಚರಿಕೆಗಳು",
    pending: "ಬಾಕಿ ಉಳಿದಿರುವ",
    resolved: "ಪರಿಹರಿಸಲಾಗಿದೆ",
    total_alerts: "ಒಟ್ಟು ಎಚ್ಚರಿಕೆಗಳು",
    alerts_by_type: "ಮಾದರಿ ಪ್ರಕಾರ ಎಚ್ಚರಿಕೆಗಳು",
    recent_activity: "ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ",
    crime_heatmap: "ಅಪರಾಧ ಶಾಖನಕ್ಷೆ",
    whisper_alert: "ವಿಸ್ಪರ್ ಎಚ್ಚರಿಕೆ",
    fir_match: "ಎಫ್‌ಐಆರ್ ಹೋಲಿಕೆ",
    cross_district: "ಅಂತರ-ಜಿಲ್ಲಾ",
    evidence_link: "ಸಾಕ್ಷ್ಯ ಲಿಂಕ್",
    ai_notification: "AI ಅಧಿಸೂಚನೆ",
    intelligence_alerts: "ಗುಪ್ತಚರ ಎಚ್ಚರಿಕೆಗಳು",
    monitor_intel: "ಸಕ್ರಿಯ ಗುಪ್ತಚರವನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ ಮತ್ತು ಪ್ರತಿಕ್ರಿಯಿಸಿ",
    performance_summary: "ಎಚ್ಚರಿಕೆ ಕಾರ್ಯಕ್ಷಮತೆಯ ಸಾರಾಂಶ",
    pending_review: "ಪರಿಶೀಲನೆ ಬಾಕಿ ಇದೆ",
    alert_trend: "ಎಚ್ಚರಿಕೆ ಪ್ರವೃತ್ತಿ",
    alert_distribution: "ಎಚ್ಚರಿಕೆ ವಿತರಣೆ",
    total: "ಒಟ್ಟು",
    recent_alerts: "ಇತ್ತೀಚಿನ ಎಚ್ಚರಿಕೆಗಳು",
    more_details: "ಹೆಚ್ಚಿನ ವಿವರಗಳು",
  },
  te: {
    accept: "అంగీకరించండి",
    dismiss: "నిరాకరించండి",
    view: "వీక్షించండి",
    alert: "అలర్ట్",
    priority: "ప్రాధాన్యత",
    status: "స్థితి",
    alerts: "అలర్ట్స్",
    alert_feed: "అలర్ట్ ఫీడ్",
    all_alerts: "అన్ని అలర్ట్స్",
    new_alerts: "కొత్త అలర్ట్స్",
    pending: "పెండింగ్",
    resolved: "పరిష్కరించబడింది",
    total_alerts: "మొత్తం అలర్ట్స్",
    alerts_by_type: "రకం ఆధారంగా అలర్ట్స్",
    recent_activity: "ఇటీవలి కార్యాచరణ",
    crime_heatmap: "క్రైమ్ హీట్‌మ్యాప్",
    whisper_alert: "విస్పర్ అలర్ట్",
    fir_match: "FIR సరిపోలిక",
    cross_district: "క్రాస్-డిస్ట్రిక్ట్",
    evidence_link: "ఆధారాల లింక్",
    ai_notification: "AI నోటిఫికేషన్",
    intelligence_alerts: "ఇంటెలిజెన్స్ అలర్ట్స్",
    monitor_intel: "క్రియాశీల ఇంటెలిజెన్స్‌ను పర్యవేక్షించండి మరియు స్పందించండి",
    performance_summary: "అలర్ట్ పనితీరు సారాంశం",
    pending_review: "సమీక్ష పెండింగ్",
    alert_trend: "అలర్ట్ ట్రెండ్",
    alert_distribution: "అలర్ట్ పంపిణీ",
    total: "మొత్తం",
    recent_alerts: "ఇటీవలి అలర్ట్స్",
    more_details: "మరిన్ని వివరాలు",
  },
  hi: {
    accept: "स्वीकार करें",
    dismiss: "अस्वीकार",
    view: "देखें",
    alert: "अलर्ट",
    priority: "प्राथमिकता",
    status: "स्थिति",
    alerts: "अलर्ट्स",
    alert_feed: "अलर्ट फ़ीड",
    all_alerts: "सभी अलर्ट्स",
    new_alerts: "नए अलर्ट्स",
    pending: "लंबित",
    resolved: "हल किया गया",
    total_alerts: "कुल अलर्ट्स",
    alerts_by_type: "प्रकार के आधार पर अलर्ट्स",
    recent_activity: "हाल की गतिविधि",
    crime_heatmap: "अपराध हीटमैप",
    whisper_alert: "व्हिस्पर अलर्ट",
    fir_match: "एफआईआर मिलान",
    cross_district: "क्रॉस-डिस्ट्रिक्ट",
    evidence_link: "साक्ष्य लिंक",
    ai_notification: "एआई अधिसूचना",
    intelligence_alerts: "खुफिया अलर्ट",
    monitor_intel: "सक्रिय खुफिया जानकारी की निगरानी करें और प्रतिक्रिया दें",
    performance_summary: "अलर्ट प्रदर्शन सारांश",
    pending_review: "समीक्षा लंबित",
    alert_trend: "अलर्ट ट्रेंड",
    alert_distribution: "अलर्ट वितरण",
    total: "कुल",
    recent_alerts: "हाल के अलर्ट",
    more_details: "अधिक विवरण",
  },
};

/**
 * Translate a key based on the provided language code.
 * @param {string} key - The translation key.
 * @param {string} [lang='en'] - Language code (en, ta, kn, te, hi).
 * @returns {string} Translated string or the key if missing.
 */
export function t(key, lang = "en") {
  const langDict = translations[lang] || translations.en;
  return langDict[key] || key;
}

// Helper to translate alert type labels dynamically
export function translateAlertType(type, lang = "en") {
  const mapping = {
    whisper: "whisper_alert",
    "fir-match": "fir_match",
    "cross-district": "cross_district",
    evidence: "evidence_link",
    ai: "ai_notification",
  };
  const key = mapping[type];
  return key ? t(key, lang) : type;
}

// Export list of supported languages for UI selectors
export const supportedLanguages = ["en", "ta", "kn", "te", "hi"];
