export const cases = [
  {
    id: 'FIR #4521',
    title: 'Theft at Malleshwaram residence',
    type: 'Theft',
    district: 'Bengaluru Urban',
    status: 'active',
    date: 'Jul 15, 2026',
    priority: 'High',
    officer: 'SI Karthik',
    description: 'Break-in at a residential property in Malleshwaram 3rd Block. Entry was gained through the rear door between 2:00 AM and 4:00 AM. Stolen items include gold jewelry worth approximately ₹5,00,000 and cash ₹50,000. CCTV footage from neighboring houses is being reviewed. No fingerprints recovered from the scene.',
    timeline: [
      { date: 'Jul 15, 2026', event: 'FIR registered by victim', type: 'filing' },
      { date: 'Jul 15, 2026', event: 'Scene investigation completed', type: 'investigation' },
      { date: 'Jul 15, 2026', event: 'CCTV footage collected from 3 neighbors', type: 'evidence' },
      { date: 'Jul 16, 2026', event: 'Suspect identified from footage — Ravi Kumar', type: 'suspect' },
      { date: 'Jul 16, 2026', event: 'Cell tower data analysis initiated', type: 'investigation' },
    ],
    suspects: [
      { name: 'Ravi Kumar', age: 32, status: 'At large', relation: 'Primary suspect', notes: 'Identified from CCTV, known repeat offender' },
    ],
    evidence: [
      { type: 'CCTV', description: 'Neighbor camera footage showing suspect at 2:15 AM', status: 'Analyzed' },
      { type: 'Phone Records', description: 'Cell tower data showing suspect near scene', status: 'Pending' },
      { type: 'Fingerprint', description: 'Partial print on rear door handle', status: 'Under review' },
    ],
    aiInsights: 'MO fingerprint matches 3 unsolved cases in Bengaluru North across the last 6 months. The entry method (rear door, same tool marks) and timing (2-4 AM) are consistent. Recommend cross-district alert for similar pattern.',
  },
  {
    id: 'FIR #4519',
    title: 'Vehicle accident — Mysuru Road',
    type: 'Accident',
    district: 'Mysuru',
    status: 'pending',
    date: 'Jul 15, 2026',
    priority: 'Medium',
    officer: 'SI Priya',
    description: 'Two-vehicle collision on Mysuru Road near the toll plaza. One person injured, admitted to hospital. Preliminary investigation suggests speeding. Both vehicles impounded for forensic examination.',
    timeline: [
      { date: 'Jul 15, 2026', event: 'Accident reported at 3:45 PM', type: 'filing' },
      { date: 'Jul 15, 2026', event: 'Victim admitted to hospital', type: 'investigation' },
      { date: 'Jul 15, 2026', event: 'Both vehicles impounded', type: 'evidence' },
    ],
    suspects: [],
    evidence: [
      { type: 'Vehicle', description: 'Both vehicles impounded for examination', status: 'Under review' },
      { type: 'Witness', description: '2 eyewitness statements collected', status: 'Analyzed' },
    ],
    aiInsights: 'No suspicious patterns detected. Standard accident investigation protocol recommended.',
  },
  {
    id: 'FIR #4515',
    title: 'Cyber fraud — Electronic City',
    type: 'Cybercrime',
    district: 'Bengaluru Urban',
    status: 'active',
    date: 'Jul 14, 2026',
    priority: 'High',
    officer: 'Inspector Deepak',
    description: 'Online payment fraud targeting employees of a tech company in Electronic City. Multiple victims reported unauthorized transactions from their bank accounts after receiving phishing emails. Total loss estimated at ₹12,00,000.',
    timeline: [
      { date: 'Jul 14, 2026', event: 'First complaint received', type: 'filing' },
      { date: 'Jul 14, 2026', event: '3 more victims came forward', type: 'filing' },
      { date: 'Jul 15, 2026', event: 'Phishing email analysis initiated', type: 'investigation' },
      { date: 'Jul 15, 2026', event: 'Bank transaction freeze requested', type: 'investigation' },
    ],
    suspects: [
      { name: 'Unknown', age: 0, status: 'Under investigation', relation: 'Primary suspect', notes: 'Operating through VPN, email traced to offshore servers' },
    ],
    evidence: [
      { type: 'Digital', description: 'Phishing email headers and content', status: 'Analyzed' },
      { type: 'Financial', description: 'Transaction records from 4 victim accounts', status: 'Under review' },
      { type: 'IP Address', description: 'VPN endpoint traced to Singapore', status: 'Pending' },
    ],
    aiInsights: 'Pattern matches recent phishing campaigns targeting tech companies in Bengaluru. Email template similar to known threat actor group. Recommend coordinated investigation with cybercrime cell.',
  },
  {
    id: 'FIR #4512',
    title: 'Missing person — Koramangala',
    type: 'Missing',
    district: 'Bengaluru Urban',
    status: 'active',
    date: 'Jul 14, 2026',
    priority: 'High',
    officer: 'SI Karthik',
    description: 'A 22-year-old engineering student has been missing since July 12. Last seen leaving college campus at 4:30 PM. Phone is switched off. Family reports no financial transactions since disappearance.',
    timeline: [
      { date: 'Jul 14, 2026', event: 'Missing person report filed', type: 'filing' },
      { date: 'Jul 14, 2026', event: 'Campus CCTV reviewed', type: 'evidence' },
      { date: 'Jul 15, 2026', event: 'Phone location analysis', type: 'investigation' },
    ],
    suspects: [],
    evidence: [
      { type: 'CCTV', description: 'Campus exit footage at 4:32 PM', status: 'Analyzed' },
      { type: 'Phone', description: 'Last cell tower ping at 4:45 PM, MG Road area', status: 'Under review' },
    ],
    aiInsights: 'Phone activity ceased abruptly. No prior history of similar incidents. Recommend checking nearby hospitals and shelters.',
  },
  {
    id: 'FIR #4508',
    title: 'Robbery attempt — Whitefield',
    type: 'Assault',
    district: 'Bengaluru Urban',
    status: 'closed',
    date: 'Jul 13, 2026',
    priority: 'Medium',
    officer: 'Inspector Deepak',
    description: 'Armed robbery attempt at a pharmacy in Whitefield. Suspect threatened staff with a knife but fled without taking anything when the alarm was triggered. Suspect arrested on Jul 14.',
    timeline: [
      { date: 'Jul 13, 2026', event: 'Robbery attempt at 9:15 PM', type: 'filing' },
      { date: 'Jul 13, 2026', event: 'Suspect description obtained', type: 'investigation' },
      { date: 'Jul 14, 2026', event: 'Suspect arrested at bus stand', type: 'investigation' },
      { date: 'Jul 14, 2026', event: 'Case closed — suspect in custody', type: 'filing' },
    ],
    suspects: [
      { name: 'Mohammed Ali', age: 28, status: 'Arrested', relation: 'Primary suspect', notes: 'Known drug user, arrested with weapon' },
    ],
    evidence: [
      { type: 'Weapon', description: 'Knife recovered from suspect', status: 'Analyzed' },
      { type: 'CCTV', description: 'Pharmacy interior footage', status: 'Analyzed' },
    ],
    aiInsights: 'Case resolved. Suspect has prior record for petty theft. No connection to organized crime detected.',
  },
  {
    id: 'FIR #4501',
    title: 'Theft at commercial complex',
    type: 'Theft',
    district: 'Bengaluru Rural',
    status: 'pending',
    date: 'Jul 12, 2026',
    priority: 'Medium',
    officer: 'SI Priya',
    description: 'Burglary at a jewelry shop in the commercial complex. Estimated loss of ₹8,00,000 in gold ornaments. Entry through the roof. Security guard was on break during the incident.',
    timeline: [
      { date: 'Jul 12, 2026', event: 'Theft discovered at 6:00 AM', type: 'filing' },
      { date: 'Jul 12, 2026', event: 'Scene secured, investigation initiated', type: 'investigation' },
    ],
    suspects: [],
    evidence: [
      { type: 'Physical', description: 'Tool marks on roof access point', status: 'Under review' },
      { type: 'CCTV', description: 'Parking lot footage under review', status: 'Pending' },
    ],
    aiInsights: 'MO suggests professional operation. Entry method similar to cases in Bengaluru Urban district. Recommend cross-district coordination.',
  },
  {
    id: 'FIR #4498',
    title: 'Fraud — online payment scam',
    type: 'Fraud',
    district: 'Mangaluru',
    status: 'active',
    date: 'Jul 11, 2026',
    priority: 'Medium',
    officer: 'Inspector Deepak',
    description: 'Online payment fraud targeting small business owners. Victims received fake payment confirmation messages and released goods before payment was verified. Total loss ₹3,50,000.',
    timeline: [
      { date: 'Jul 11, 2026', event: 'Complaint filed by 3 victims', type: 'filing' },
      { date: 'Jul 12, 2026', event: 'Fake payment gateway analyzed', type: 'investigation' },
    ],
    suspects: [
      { name: 'Unknown', age: 0, status: 'Under investigation', relation: 'Primary suspect', notes: 'Using cloned payment confirmation system' },
    ],
    evidence: [
      { type: 'Digital', description: 'Fake payment confirmation screenshots', status: 'Analyzed' },
      { type: 'Financial', description: 'Bank records showing no actual transfer', status: 'Analyzed' },
    ],
    aiInsights: 'Similar to recent fraud pattern in coastal Karnataka. Payment gateway clone technique matches known threat actor.',
  },
  {
    id: 'FIR #4495',
    title: 'Assault near bus stand',
    type: 'Assault',
    district: 'Hubballi',
    status: 'closed',
    date: 'Jul 10, 2026',
    priority: 'Low',
    officer: 'SI Priya',
    description: 'Physical altercation between two individuals near the bus stand. One person sustained minor injuries. Both parties have filed cross-complaints. Case closed as mutual settlement.',
    timeline: [
      { date: 'Jul 10, 2026', event: 'Incident reported', type: 'filing' },
      { date: 'Jul 10, 2026', event: 'Both parties interviewed', type: 'investigation' },
      { date: 'Jul 11, 2026', event: 'Mutual settlement reached', type: 'filing' },
    ],
    suspects: [],
    evidence: [],
    aiInsights: 'No further investigation required. Case closed by mutual agreement.',
  },
  {
    id: 'FIR #4489',
    title: 'Robbery — Indiranagar',
    type: 'Theft',
    district: 'Bengaluru Urban',
    status: 'active',
    date: 'Jul 9, 2026',
    priority: 'High',
    officer: 'SI Karthik',
    description: 'Armed robbery at a restaurant in Indiranagar. Two suspects on a motorcycle threatened staff and fled with ₹1,20,000 cash. Suspects were wearing helmets, partial plate number captured.',
    timeline: [
      { date: 'Jul 9, 2026', event: 'Robbery at 10:30 PM', type: 'filing' },
      { date: 'Jul 9, 2026', event: 'CCTV footage collected', type: 'evidence' },
      { date: 'Jul 10, 2026', event: 'Vehicle number partially identified', type: 'investigation' },
    ],
    suspects: [
      { name: 'Unknown (2 suspects)', age: 0, status: 'At large', relation: 'Primary suspects', notes: 'On motorcycle, wearing helmets' },
    ],
    evidence: [
      { type: 'CCTV', description: 'Restaurant entrance footage', status: 'Analyzed' },
      { type: 'Vehicle', description: 'Partial plate number: KA-01-AB-****', status: 'Under review' },
    ],
    aiInsights: 'MO matches robbery series in Bengaluru Urban. Same motorcycle-based approach, helmet use, and targeting of cash-heavy businesses.',
  },
  {
    id: 'FIR #4485',
    title: 'Cybercrime — phishing attack',
    type: 'Cybercrime',
    district: 'Bengaluru Urban',
    status: 'pending',
    date: 'Jul 8, 2026',
    priority: 'Medium',
    officer: 'Inspector Deepak',
    description: 'Targeted phishing attack on a financial firm. Employee credentials compromised, leading to unauthorized data access. No financial loss yet, but sensitive client data may be exposed.',
    timeline: [
      { date: 'Jul 8, 2026', event: 'Security breach detected', type: 'filing' },
      { date: 'Jul 8, 2026', event: 'Affected systems isolated', type: 'investigation' },
      { date: 'Jul 9, 2026', event: 'Forensic analysis initiated', type: 'investigation' },
    ],
    suspects: [
      { name: 'Unknown', age: 0, status: 'Under investigation', relation: 'Primary suspect', notes: 'Advanced persistent threat suspected' },
    ],
    evidence: [
      { type: 'Digital', description: 'Phishing email and malicious link', status: 'Analyzed' },
      { type: 'Log', description: 'System access logs showing unauthorized entry', status: 'Under review' },
    ],
    aiInsights: 'Sophisticated attack using social engineering. Link to known APT group based on TTP analysis. Recommend engaging national cybercrime cell.',
  },
  {
    id: 'FIR #4480',
    title: 'Theft from parking lot',
    type: 'Theft',
    district: 'Mysuru',
    status: 'closed',
    date: 'Jul 7, 2026',
    priority: 'Low',
    officer: 'SI Priya',
    description: 'Motorcycle stolen from a mall parking lot. Vehicle recovered within 24 hours from a nearby area. Suspect identified and arrested.',
    timeline: [
      { date: 'Jul 7, 2026', event: 'Theft reported', type: 'filing' },
      { date: 'Jul 7, 2026', event: 'CCTV review initiated', type: 'investigation' },
      { date: 'Jul 8, 2026', event: 'Vehicle recovered, suspect arrested', type: 'investigation' },
    ],
    suspects: [
      { name: 'Venkatesh R', age: 24, status: 'Arrested', relation: 'Primary suspect', notes: 'Known petty thief, confessed to crime' },
    ],
    evidence: [
      { type: 'CCTV', description: 'Parking lot entry/exit footage', status: 'Analyzed' },
      { type: 'Vehicle', description: 'Recovered motorcycle', status: 'Analyzed' },
    ],
    aiInsights: 'Isolated incident. Suspect acted alone. No connection to larger theft ring.',
  },
  {
    id: 'FIR #4475',
    title: 'Fraud — insurance claim',
    type: 'Fraud',
    district: 'Bengaluru Rural',
    status: 'active',
    date: 'Jul 6, 2026',
    priority: 'Medium',
    officer: 'Inspector Deepak',
    description: 'Suspected insurance fraud involving staged vehicle accident. Multiple claims filed from different insurance companies for the same incident. Investigation initiated.',
    timeline: [
      { date: 'Jul 6, 2026', event: 'Suspicious claim pattern detected', type: 'filing' },
      { date: 'Jul 7, 2026', event: 'Cross-insurer data sharing initiated', type: 'investigation' },
    ],
    suspects: [
      { name: 'Rajesh Sharma', age: 45, status: 'Under investigation', relation: 'Primary suspect', notes: 'Filed claims with 3 different insurers' },
    ],
    evidence: [
      { type: 'Document', description: 'Multiple insurance claim forms', status: 'Under review' },
      { type: 'Medical', description: 'Injury reports from different hospitals', status: 'Pending' },
    ],
    aiInsights: 'Insurance fraud ring suspected. Multiple claimants using similar documentation patterns. Recommend expanding investigation scope.',
  },
  {
    id: 'FIR #4470',
    title: 'Assault — domestic dispute',
    type: 'Assault',
    district: 'Mangaluru',
    status: 'pending',
    date: 'Jul 5, 2026',
    priority: 'Medium',
    officer: 'SI Priya',
    description: 'Domestic violence complaint filed. Victim sustained injuries and was hospitalized. Protection order requested. Investigation ongoing.',
    timeline: [
      { date: 'Jul 5, 2026', event: 'Complaint filed', type: 'filing' },
      { date: 'Jul 5, 2026', event: 'Victim statement recorded', type: 'investigation' },
      { date: 'Jul 6, 2026', event: 'Protection order hearing scheduled', type: 'filing' },
    ],
    suspects: [
      { name: 'Suresh Patel', age: 38, status: 'Under investigation', relation: 'Spouse', notes: 'Denied allegations' },
    ],
    evidence: [
      { type: 'Medical', description: 'Hospital injury report', status: 'Analyzed' },
      { type: 'Witness', description: 'Neighbor testimony', status: 'Under review' },
    ],
    aiInsights: 'Standard domestic violence protocol. Recommend victim support services and follow-up.',
  },
  {
    id: 'FIR #4465',
    title: 'Missing juvenile — Hebbal',
    type: 'Missing',
    district: 'Bengaluru Urban',
    status: 'active',
    date: 'Jul 4, 2026',
    priority: 'High',
    officer: 'SI Karthik',
    description: '16-year-old student missing from home since July 3. Left a note mentioning personal issues. No financial transactions or phone activity since disappearance.',
    timeline: [
      { date: 'Jul 4, 2026', event: 'Missing report filed', type: 'filing' },
      { date: 'Jul 4, 2026', note: 'Note found at home', type: 'evidence' },
      { date: 'Jul 5, 2026', event: 'Social media accounts reviewed', type: 'investigation' },
    ],
    suspects: [],
    evidence: [
      { type: 'Document', description: 'Handwritten note found at home', status: 'Analyzed' },
      { type: 'Digital', description: 'Social media activity analysis', status: 'Under review' },
    ],
    aiInsights: 'Juvenile may be at risk. Social media analysis shows recent distress signals. Recommend issuing missing person alert to all stations.',
  },
  {
    id: 'FIR #4460',
    title: 'Cybercrime — data breach',
    type: 'Cybercrime',
    district: 'Hubballi',
    status: 'closed',
    date: 'Jul 3, 2026',
    priority: 'Medium',
    officer: 'Inspector Deepak',
    description: 'Data breach at a local hospital. Patient records exposed. Vulnerability identified and patched. Breach contained with minimal data exposure.',
    timeline: [
      { date: 'Jul 3, 2026', event: 'Breach detected', type: 'filing' },
      { date: 'Jul 3, 2026', event: 'Systems isolated, vulnerability patched', type: 'investigation' },
      { date: 'Jul 4, 2026', event: 'Impact assessment completed', type: 'investigation' },
      { date: 'Jul 5, 2026', event: 'Case closed — vulnerability remediated', type: 'filing' },
    ],
    suspects: [],
    evidence: [
      { type: 'Digital', description: 'Server logs showing intrusion path', status: 'Analyzed' },
      { type: 'Technical', description: 'Vulnerability assessment report', status: 'Analyzed' },
    ],
    aiInsights: 'Opportunistic attack exploiting known vulnerability. No evidence of targeted data exfiltration. Recommend regular security audits.',
  },
]

export function getCaseById(id) {
  return cases.find((c) => c.id === id)
}
