export const getCases = (t) => [
  {
    id: 'FIR #4521',
    title: t('Theft at Malleshwaram residence'),
    type: t('Theft'),
    district: t('Bengaluru Urban'),
    status: t('active'),
    date: t('Jul 15, 2026'),
    priority: t('High'),
    officer: t('SI Karthik'),
    description: t('Break-in at a residential property in Malleshwaram 3rd Block. Entry was gained through the rear door between 2:00 AM and 4:00 AM. Stolen items include gold jewelry worth approximately ₹5,00,000 and cash ₹50,000. CCTV footage from neighboring houses is being reviewed. No fingerprints recovered from the scene.'),
    timeline: [
      { date: t('Jul 15, 2026'), event: t('FIR registered by victim'), type: t('filing') },
      { date: t('Jul 15, 2026'), event: t('Scene investigation completed'), type: t('investigation') },
      { date: t('Jul 15, 2026'), event: t('CCTV footage collected from 3 neighbors'), type: t('evidence') },
      { date: t('Jul 16, 2026'), event: t('Suspect identified from footage — Ravi Kumar'), type: t('suspect') },
      { date: t('Jul 16, 2026'), event: t('Cell tower data analysis initiated'), type: t('investigation') },
    ],
    suspects: [
      { name: 'Ravi Kumar', age: 32, status: t('At large'), relation: t('Primary suspect'), notes: t('Identified from CCTV, known repeat offender') },
    ],
    evidence: [
      { type: t('CCTV'), description: t('Neighbor camera footage showing suspect at 2:15 AM'), status: t('Analyzed') },
      { type: t('Phone Records'), description: t('Cell tower data showing suspect near scene'), status: t('Pending') },
      { type: t('Fingerprint'), description: t('Partial print on rear door handle'), status: t('Under review') },
    ],
    aiInsights: t('MO fingerprint matches 3 unsolved cases in Bengaluru North across the last 6 months. The entry method (rear door, same tool marks) and timing (2-4 AM) are consistent. Recommend cross-district alert for similar pattern.'),
  },
  {
    id: 'FIR #4519',
    title: t('Vehicle accident — Mysuru Road'),
    type: t('Accident'),
    district: t('Mysuru'),
    status: t('pending'),
    date: t('Jul 15, 2026'),
    priority: t('Medium'),
    officer: t('SI Priya'),
    description: t('Two-vehicle collision on Mysuru Road near the toll plaza. One person injured, admitted to hospital. Preliminary investigation suggests speeding. Both vehicles impounded for forensic examination.'),
    timeline: [
      { date: t('Jul 15, 2026'), event: t('Accident reported at 3:45 PM'), type: t('filing') },
      { date: t('Jul 15, 2026'), event: t('Victim admitted to hospital'), type: t('investigation') },
      { date: t('Jul 15, 2026'), event: t('Both vehicles impounded'), type: t('evidence') },
    ],
    suspects: [],
    evidence: [
      { type: t('Vehicle'), description: t('Both vehicles impounded for examination'), status: t('Under review') },
      { type: t('Witness'), description: t('2 eyewitness statements collected'), status: t('Analyzed') },
    ],
    aiInsights: t('No suspicious patterns detected. Standard accident investigation protocol recommended.'),
  },
  {
    id: 'FIR #4515',
    title: t('Cyber fraud — Electronic City'),
    type: t('Cybercrime'),
    district: t('Bengaluru Urban'),
    status: t('active'),
    date: t('Jul 14, 2026'),
    priority: t('High'),
    officer: t('Inspector Deepak'),
    description: t('Online payment fraud targeting employees of a tech company in Electronic City. Multiple victims reported unauthorized transactions from their bank accounts after receiving phishing emails. Total loss estimated at ₹12,00,000.'),
    timeline: [
      { date: t('Jul 14, 2026'), event: t('First complaint received'), type: t('filing') },
      { date: t('Jul 14, 2026'), event: t('3 more victims came forward'), type: t('filing') },
      { date: t('Jul 15, 2026'), event: t('Phishing email analysis initiated'), type: t('investigation') },
      { date: t('Jul 15, 2026'), event: t('Bank transaction freeze requested'), type: t('investigation') },
    ],
    suspects: [
      { name: 'Unknown', age: 0, status: t('Under investigation'), relation: t('Primary suspect'), notes: t('Operating through VPN, email traced to offshore servers') },
    ],
    evidence: [
      { type: t('Digital'), description: t('Phishing email headers and content'), status: t('Analyzed') },
      { type: t('Financial'), description: t('Transaction records from 4 victim accounts'), status: t('Under review') },
      { type: t('IP Address'), description: t('VPN endpoint traced to Singapore'), status: t('Pending') },
    ],
    aiInsights: t('Pattern matches recent phishing campaigns targeting tech companies in Bengaluru. Email template similar to known threat actor group. Recommend coordinated investigation with cybercrime cell.'),
  },
  {
    id: 'FIR #4512',
    title: t('Missing person — Koramangala'),
    type: t('Missing'),
    district: t('Bengaluru Urban'),
    status: t('active'),
    date: t('Jul 14, 2026'),
    priority: t('High'),
    officer: t('SI Karthik'),
    description: t('A 22-year-old engineering student has been missing since July 12. Last seen leaving college campus at 4:30 PM. Phone is switched off. Family reports no financial transactions since disappearance.'),
    timeline: [
      { date: t('Jul 14, 2026'), event: t('Missing person report filed'), type: t('filing') },
      { date: t('Jul 14, 2026'), event: t('Campus CCTV reviewed'), type: t('evidence') },
      { date: t('Jul 15, 2026'), event: t('Phone location analysis'), type: t('investigation') },
    ],
    suspects: [],
    evidence: [
      { type: t('CCTV'), description: t('Campus exit footage at 4:32 PM'), status: t('Analyzed') },
      { type: t('Phone'), description: t('Last cell tower ping at 4:45 PM, MG Road area'), status: t('Under review') },
    ],
    aiInsights: t('Phone activity ceased abruptly. No prior history of similar incidents. Recommend checking nearby hospitals and shelters.'),
  },
  {
    id: 'FIR #4508',
    title: t('Robbery attempt — Whitefield'),
    type: t('Assault'),
    district: t('Bengaluru Urban'),
    status: t('closed'),
    date: t('Jul 13, 2026'),
    priority: t('Medium'),
    officer: t('Inspector Deepak'),
    description: t('Armed robbery attempt at a pharmacy in Whitefield. Suspect threatened staff with a knife but fled without taking anything when the alarm was triggered. Suspect arrested on Jul 14.'),
    timeline: [
      { date: t('Jul 13, 2026'), event: t('Robbery attempt at 9:15 PM'), type: t('filing') },
      { date: t('Jul 13, 2026'), event: t('Suspect description obtained'), type: t('investigation') },
      { date: t('Jul 14, 2026'), event: t('Suspect arrested at bus stand'), type: t('investigation') },
      { date: t('Jul 14, 2026'), event: t('Case closed — suspect in custody'), type: t('filing') },
    ],
    suspects: [
      { name: 'Mohammed Ali', age: 28, status: t('Arrested'), relation: t('Primary suspect'), notes: t('Known drug user, arrested with weapon') },
    ],
    evidence: [
      { type: t('Weapon'), description: t('Knife recovered from suspect'), status: t('Analyzed') },
      { type: t('CCTV'), description: t('Pharmacy interior footage'), status: t('Analyzed') },
    ],
    aiInsights: t('Case resolved. Suspect has prior record for petty theft. No connection to organized crime detected.'),
  },
  {
    id: 'FIR #4501',
    title: t('Theft at commercial complex'),
    type: t('Theft'),
    district: t('Bengaluru Rural'),
    status: t('pending'),
    date: t('Jul 12, 2026'),
    priority: t('Medium'),
    officer: t('SI Priya'),
    description: t('Burglary at a jewelry shop in the commercial complex. Estimated loss of ₹8,00,000 in gold ornaments. Entry through the roof. Security guard was on break during the incident.'),
    timeline: [
      { date: t('Jul 12, 2026'), event: t('Theft discovered at 6:00 AM'), type: t('filing') },
      { date: t('Jul 12, 2026'), event: t('Scene secured, investigation initiated'), type: t('investigation') },
    ],
    suspects: [],
    evidence: [
      { type: t('Physical'), description: t('Tool marks on roof access point'), status: t('Under review') },
      { type: t('CCTV'), description: t('Parking lot footage under review'), status: t('Pending') },
    ],
    aiInsights: t('MO suggests professional operation. Entry method similar to cases in Bengaluru Urban district. Recommend cross-district coordination.'),
  },
  {
    id: 'FIR #4498',
    title: t('Fraud — online payment scam'),
    type: t('Fraud'),
    district: t('Mangaluru'),
    status: t('active'),
    date: t('Jul 11, 2026'),
    priority: t('Medium'),
    officer: t('Inspector Deepak'),
    description: t('Online payment fraud targeting small business owners. Victims received fake payment confirmation messages and released goods before payment was verified. Total loss ₹3,50,000.'),
    timeline: [
      { date: t('Jul 11, 2026'), event: t('Complaint filed by 3 victims'), type: t('filing') },
      { date: t('Jul 12, 2026'), event: t('Fake payment gateway analyzed'), type: t('investigation') },
    ],
    suspects: [
      { name: 'Unknown', age: 0, status: t('Under investigation'), relation: t('Primary suspect'), notes: t('Using cloned payment confirmation system') },
    ],
    evidence: [
      { type: t('Digital'), description: t('Fake payment confirmation screenshots'), status: t('Analyzed') },
      { type: t('Financial'), description: t('Bank records showing no actual transfer'), status: t('Analyzed') },
    ],
    aiInsights: t('Similar to recent fraud pattern in coastal Karnataka. Payment gateway clone technique matches known threat actor.'),
  },
  {
    id: 'FIR #4495',
    title: t('Assault near bus stand'),
    type: t('Assault'),
    district: t('Hubballi'),
    status: t('closed'),
    date: t('Jul 10, 2026'),
    priority: t('Low'),
    officer: t('SI Priya'),
    description: t('Physical altercation between two individuals near the bus stand. One person sustained minor injuries. Both parties have filed cross-complaints. Case closed as mutual settlement.'),
    timeline: [
      { date: t('Jul 10, 2026'), event: t('Incident reported'), type: t('filing') },
      { date: t('Jul 10, 2026'), event: t('Both parties interviewed'), type: t('investigation') },
      { date: t('Jul 11, 2026'), event: t('Mutual settlement reached'), type: t('filing') },
    ],
    suspects: [],
    evidence: [],
    aiInsights: t('No further investigation required. Case closed by mutual agreement.'),
  },
  {
    id: 'FIR #4489',
    title: t('Robbery — Indiranagar'),
    type: t('Theft'),
    district: t('Bengaluru Urban'),
    status: t('active'),
    date: t('Jul 9, 2026'),
    priority: t('High'),
    officer: t('SI Karthik'),
    description: t('Armed robbery at a restaurant in Indiranagar. Two suspects on a motorcycle threatened staff and fled with ₹1,20,000 cash. Suspects were wearing helmets, partial plate number captured.'),
    timeline: [
      { date: t('Jul 9, 2026'), event: t('Robbery at 10:30 PM'), type: t('filing') },
      { date: t('Jul 9, 2026'), event: t('CCTV footage collected'), type: t('evidence') },
      { date: t('Jul 10, 2026'), event: t('Vehicle number partially identified'), type: t('investigation') },
    ],
    suspects: [
      { name: 'Unknown (2 suspects)', age: 0, status: t('At large'), relation: t('Primary suspects'), notes: t('On motorcycle, wearing helmets') },
    ],
    evidence: [
      { type: t('CCTV'), description: t('Restaurant entrance footage'), status: t('Analyzed') },
      { type: t('Vehicle'), description: t('Partial plate number: KA-01-AB-****'), status: t('Under review') },
    ],
    aiInsights: t('MO matches robbery series in Bengaluru Urban. Same motorcycle-based approach, helmet use, and targeting of cash-heavy businesses.'),
  },
  {
    id: 'FIR #4485',
    title: t('Cybercrime — phishing attack'),
    type: t('Cybercrime'),
    district: t('Bengaluru Urban'),
    status: t('pending'),
    date: t('Jul 8, 2026'),
    priority: t('Medium'),
    officer: t('Inspector Deepak'),
    description: t('Targeted phishing attack on a financial firm. Employee credentials compromised, leading to unauthorized data access. No financial loss yet, but sensitive client data may be exposed.'),
    timeline: [
      { date: t('Jul 8, 2026'), event: t('Security breach detected'), type: t('filing') },
      { date: t('Jul 8, 2026'), event: t('Affected systems isolated'), type: t('investigation') },
      { date: t('Jul 9, 2026'), event: t('Forensic analysis initiated'), type: t('investigation') },
    ],
    suspects: [
      { name: 'Unknown', age: 0, status: t('Under investigation'), relation: t('Primary suspect'), notes: t('Advanced persistent threat suspected') },
    ],
    evidence: [
      { type: t('Digital'), description: t('Phishing email and malicious link'), status: t('Analyzed') },
      { type: t('Log'), description: t('System access logs showing unauthorized entry'), status: t('Under review') },
    ],
    aiInsights: t('Sophisticated attack using social engineering. Link to known APT group based on TTP analysis. Recommend engaging national cybercrime cell.'),
  },
  {
    id: 'FIR #4480',
    title: t('Theft from parking lot'),
    type: t('Theft'),
    district: t('Mysuru'),
    status: t('closed'),
    date: t('Jul 7, 2026'),
    priority: t('Low'),
    officer: t('SI Priya'),
    description: t('Motorcycle stolen from a mall parking lot. Vehicle recovered within 24 hours from a nearby area. Suspect identified and arrested.'),
    timeline: [
      { date: t('Jul 7, 2026'), event: t('Theft reported'), type: t('filing') },
      { date: t('Jul 7, 2026'), event: t('CCTV review initiated'), type: t('investigation') },
      { date: t('Jul 8, 2026'), event: t('Vehicle recovered, suspect arrested'), type: t('investigation') },
    ],
    suspects: [
      { name: 'Venkatesh R', age: 24, status: t('Arrested'), relation: t('Primary suspect'), notes: t('Known petty thief, confessed to crime') },
    ],
    evidence: [
      { type: t('CCTV'), description: t('Parking lot entry/exit footage'), status: t('Analyzed') },
      { type: t('Vehicle'), description: t('Recovered motorcycle'), status: t('Analyzed') },
    ],
    aiInsights: t('Isolated incident. Suspect acted alone. No connection to larger theft ring.'),
  },
  {
    id: 'FIR #4475',
    title: t('Fraud — insurance claim'),
    type: t('Fraud'),
    district: t('Bengaluru Rural'),
    status: t('active'),
    date: t('Jul 6, 2026'),
    priority: t('Medium'),
    officer: t('Inspector Deepak'),
    description: t('Suspected insurance fraud involving staged vehicle accident. Multiple claims filed from different insurance companies for the same incident. Investigation initiated.'),
    timeline: [
      { date: t('Jul 6, 2026'), event: t('Suspicious claim pattern detected'), type: t('filing') },
      { date: t('Jul 7, 2026'), event: t('Cross-insurer data sharing initiated'), type: t('investigation') },
    ],
    suspects: [
      { name: 'Rajesh Sharma', age: 45, status: t('Under investigation'), relation: t('Primary suspect'), notes: t('Filed claims with 3 different insurers') },
    ],
    evidence: [
      { type: t('Document'), description: t('Multiple insurance claim forms'), status: t('Under review') },
      { type: t('Medical'), description: t('Injury reports from different hospitals'), status: t('Pending') },
    ],
    aiInsights: t('Insurance fraud ring suspected. Multiple claimants using similar documentation patterns. Recommend expanding investigation scope.'),
  },
  {
    id: 'FIR #4470',
    title: t('Assault — domestic dispute'),
    type: t('Assault'),
    district: t('Mangaluru'),
    status: t('pending'),
    date: t('Jul 5, 2026'),
    priority: t('Medium'),
    officer: t('SI Priya'),
    description: t('Domestic violence complaint filed. Victim sustained injuries and was hospitalized. Protection order requested. Investigation ongoing.'),
    timeline: [
      { date: t('Jul 5, 2026'), event: t('Complaint filed'), type: t('filing') },
      { date: t('Jul 5, 2026'), event: t('Victim statement recorded'), type: t('investigation') },
      { date: t('Jul 6, 2026'), event: t('Protection order hearing scheduled'), type: t('filing') },
    ],
    suspects: [
      { name: 'Suresh Patel', age: 38, status: t('Under investigation'), relation: t('Spouse'), notes: t('Denied allegations') },
    ],
    evidence: [
      { type: t('Medical'), description: t('Hospital injury report'), status: t('Analyzed') },
      { type: t('Witness'), description: t('Neighbor testimony'), status: t('Under review') },
    ],
    aiInsights: t('Standard domestic violence protocol. Recommend victim support services and follow-up.'),
  },
  {
    id: 'FIR #4465',
    title: t('Missing juvenile — Hebbal'),
    type: t('Missing'),
    district: t('Bengaluru Urban'),
    status: t('active'),
    date: t('Jul 4, 2026'),
    priority: t('High'),
    officer: t('SI Karthik'),
    description: t('16-year-old student missing from home since July 3. Left a note mentioning personal issues. No financial transactions or phone activity since disappearance.'),
    timeline: [
      { date: t('Jul 4, 2026'), event: t('Missing report filed'), type: t('filing') },
      { date: t('Jul 4, 2026'), note: 'Note found at home', type: t('evidence') },
      { date: t('Jul 5, 2026'), event: t('Social media accounts reviewed'), type: t('investigation') },
    ],
    suspects: [],
    evidence: [
      { type: t('Document'), description: t('Handwritten note found at home'), status: t('Analyzed') },
      { type: t('Digital'), description: t('Social media activity analysis'), status: t('Under review') },
    ],
    aiInsights: t('Juvenile may be at risk. Social media analysis shows recent distress signals. Recommend issuing missing person alert to all stations.'),
  },
  {
    id: 'FIR #4460',
    title: t('Cybercrime — data breach'),
    type: t('Cybercrime'),
    district: t('Hubballi'),
    status: t('closed'),
    date: t('Jul 3, 2026'),
    priority: t('Medium'),
    officer: t('Inspector Deepak'),
    description: t('Data breach at a local hospital. Patient records exposed. Vulnerability identified and patched. Breach contained with minimal data exposure.'),
    timeline: [
      { date: t('Jul 3, 2026'), event: t('Breach detected'), type: t('filing') },
      { date: t('Jul 3, 2026'), event: t('Systems isolated, vulnerability patched'), type: t('investigation') },
      { date: t('Jul 4, 2026'), event: t('Impact assessment completed'), type: t('investigation') },
      { date: t('Jul 5, 2026'), event: t('Case closed — vulnerability remediated'), type: t('filing') },
    ],
    suspects: [],
    evidence: [
      { type: t('Digital'), description: t('Server logs showing intrusion path'), status: t('Analyzed') },
      { type: t('Technical'), description: t('Vulnerability assessment report'), status: t('Analyzed') },
    ],
    aiInsights: t('Opportunistic attack exploiting known vulnerability. No evidence of targeted data exfiltration. Recommend regular security audits.'),
  },
]

export function getCaseById(id, t) {
  return getCases(t).find((c) => c.id === id)
}
